coverage:
  range: "10...80"

ignore:
  - "config" # ignore configs
  - "**/__mocks__/*" # ignore mocks
  - "*.constants.tsx"
  - "*.constants.ts"
  - "*.styles.ts"
  - "module.tsx"
  - "module.ts"
  - "types.ts"
