export const baseUrl = 'http://host.docker.internal/'
export const qanUrl = baseUrl+'graph/d/pmm-qan/pmm-query-analytics'
export const pmmSettingsUrl = baseUrl+'graph/d/pmm-settings/pmm-settings'
export const username = 'admin'
export const password = 'admin'
