version: "3"
services:
  pmm-server:
    container_name: pmm-server
    image: perconalab/pmm-server:dev-latest
    volumes:
      - "./dist:/srv/grafana/plugins/pmm-app/dist"
      - "../../grafana/public:/usr/share/grafana/public"
    ports:
      - 80:80
      - 443:443
      - 29000:9000
      - 9933:9933
    restart: always
    environment:
      - ENABLE_BACKUP_MANAGEMENT=1
      - NODE_ENV=production
      - PERCONA_TEST_DBAAS=1
      - PERCONA_TEST_VERSION_SERVICE_URL=https://check-dev.percona.com/versions/v1
      - ENABLE_DBAAS=1
      - PERCONA_TEST_SAAS_HOST=check-dev.percona.com
      - PERCONA_TEST_CHECKS_PUBLIC_KEY=RWTkF7Snv08FCboTne4djQfN5qbrLfAjb8SY3/wwEP+X5nUrkxCEvUDJ

  mysql:
    image: ${MYSQL_IMAGE:-percona:5.7}
    container_name: pmm-agent_mysql
    command: >
      --sql-mode="ANSI_QUOTES"
      --performance-schema --innodb_monitor_enable=all
      --slow_query_log --slow_query_log_file=/mysql/slowlogs/slow.log --long_query_time=0
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=pmm-agent
      - MYSQL_PASSWORD=pmm-agent-password
      - UMASK=0777  # for slowlog file

#  postgres:
#    image: ${POSTGRES_IMAGE:-perconalab/percona-distribution-postgresql:13.2-2}
#    container_name: pmm-agent_postgres
#    command: >
#      -c shared_preload_libraries=pg_stat_monitor,pg_stat_statements
#      -c track_activity_query_size=2048
#      -c pg_stat_statements.max=10000
#      -c pg_stat_statements.track=all
#      -c pg_stat_statements.save=off
#      -c track_io_timing=on
#      -c pg_stat_monitor.pgsm_normalized_query=1
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: pmm-agent
#      POSTGRES_PASSWORD: pmm-agent-password
#      POSTGRES_DB: postgres
#
#  pgadmin:
#    image: thajeztah/pgadmin4
#    links:
#      - postgres
#    depends_on:
#      - postgres
#    ports:
#      - 5050:5050
