// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using

process.env.TZ = 'GMT';

module.exports = {
  ...standard.jestConfig(),
  snapshotSerializers: ['enzyme-to-json/serializer'],
  verbose: true,
  collectCoverage: true,
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!**/node_modules/**',
    '!**/*styles.{ts,tsx}',
    '!**/*constants.{ts,tsx}',
    '!**/*module.{ts,tsx}',
    '!**/*types.ts',
  ],
};
