{
 "title": "clickhouse dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "array_var",
    "query": "SELECT DISTINCT [service_name, ' test array'] FROM default.test_grafana"
   },
   {
    "name": "remote_host",
    "query": "SELECT DISTINCT concat(host_name, ':', toString(port)) AS remote_host FROM system.clusters"
   },
   {
    "name": "cluster_name",
    "query": "SELECT DISTINCT cluster FROM system.clusters"
   },
   {
    "name": "repeated_service",
    "query": "SELECT DISTINCT service_name FROM default.test_grafana"
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Array template variable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(service_name,\r\n    count() c\r\n)\r\nFROM $table  WHERE [service_name, ' test array'] IN (${array_var}) AND $timeFilter\r\n",
     "rawQuery": "SELECT t, groupArray((service_name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, service_name, count() c FROM default.test_grafana WHERE event_time >= toDateTime(1593992068) AND     [service_name     ,     ' test array'] IN (['mysql',' test array'],['postgresql',' test array'])     AND event_time >= toDateTime(1593992068)     AND service_name LIKE '%sql%' GROUP BY t, service_name ORDER BY t, service_name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "remote and array",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(service_name,\r\n    count() c\r\n)\r\nFROM remote('${remote_host}',default.test_grafana)  WHERE [service_name, ' test array'] IN (${array_var}) AND $timeFilter",
     "rawQuery": "SELECT t, groupArray((service_name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, service_name, count() c FROM remote('localhost:9000',default.test_grafana) WHERE event_time >= toDateTime(1593992191) AND     [service_name     ,     ' test array'] IN (['mysql',' test array'],['postgresql',' test array'])     AND event_time >= toDateTime(1593992191) GROUP BY t, service_name ORDER BY t, service_name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "cluster and array",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(service_name,\r\n    count() c\r\n)\r\nFROM cluster('${cluster_name}',default.test_grafana)  WHERE [service_name, ' test array'] IN (${array_var}) AND $timeFilter\r\n",
     "rawQuery": "SELECT t, groupArray((service_name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, service_name, count() c FROM cluster('test_shard_localhost',default.test_grafana)  WHERE event_time >= toDateTime(1593725203) AND [service_name, ' test array'] IN (['postgresql', ' test array'],['mysql', ' test array']) AND event_time >= toDateTime(1593725203) GROUP BY t, service_name ORDER BY t, service_name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "Repeated ${repeated_service}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "repeated_service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(service_name,\r\n    count() c\r\n)\r\nFROM $table  WHERE service_name IN (${repeated_service}) AND $timeFilter",
     "rawQuery": "SELECT t, groupArray((service_name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, service_name, count() c FROM default.test_grafana WHERE event_time >= toDateTime(1593992104) AND     service_name IN ('mysql')     AND event_time >= toDateTime(1593992104)     AND service_name LIKE '%sql%' GROUP BY t, service_name ORDER BY t, service_name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "Repeated ${repeated_service}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(service_name,\r\n    count() c\r\n)\r\nFROM $table  WHERE service_name IN (${repeated_service}) AND $timeFilter",
     "rawQuery": "SELECT t, groupArray((service_name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, service_name, count() c FROM default.test_grafana WHERE event_time >= toDateTime(1593992104) AND     service_name IN ('mysql')     AND event_time >= toDateTime(1593992104)     AND service_name LIKE '%sql%' GROUP BY t, service_name ORDER BY t, service_name) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "merge() table function",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    $timeSeries AS t,\r\n    service_name,\r\n    _table,\r\n    count() c\r\nFROM merge('default','^test_grafana$')\r\nWHERE service_name IN (${repeated_service}) AND $timeFilter\r\nGROUP BY t, service_name, _table\r\nORDER BY t\r\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t,     service_name,     _table,     count() c FROM merge('default','^test_grafana$') WHERE     service_name IN (['mysql','postgresql'])     AND event_time >= toDateTime(1593991951) GROUP BY     t,     service_name,     _table ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "subquery example",
   "type": "graph",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/127",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\r\n  SELECT\r\n      $timeSeries as t,\r\n      count() as c\r\n  FROM $table\r\n  WHERE $timeFilter\r\n  GROUP BY t\r\n)\r\nORDER BY t",
     "rawQuery": "SELECT * FROM (     SELECT         (intDiv(toUInt32(event_time), 20) * 20) * 1000 as t,         count() as c     FROM default.test_grafana     WHERE         event_time >= toDateTime(1594103238)         AND service_name LIKE '%sql%'     GROUP BY t ) ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "multi-value variable",
   "type": "graph",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/252",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\r\n  SELECT\r\n      $timeSeries as t,\r\n      count() as c\r\n  FROM $table\r\n  WHERE service_name IN ($repeated_service) AND $timeFilter\r\n  GROUP BY t\r\n)\r\nORDER BY t",
     "rawQuery": "SELECT * FROM (     SELECT         (intDiv(toUInt32(event_time), 20) * 20) * 1000 as t,         count() as c     FROM default.test_grafana     WHERE         service_name IN ('mysql','postgresql')         AND event_time >= toDateTime(1595669272)         AND service_name LIKE '%sql%'     GROUP BY t ) ORDER BY t",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "turn off skip_comments example",
   "type": "graph",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/265",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "/* test comment1 */\r\n-- test comment2\r\n/* \r\n  test multiline comment3\r\n*/  \r\n$rate(countIf(service_name='mysql' AND from_user='bob') AS mysql_bob, countIf(service_name='postgres') AS postgres) \r\nFROM $table\r\nWHERE from_user='bob'\r\n\r\n/* comment4 */\r\n-- comment 5",
     "rawQuery": " /* test comment1 */\n-- test comment2\r\n/* \r\n  test multiline comment3\r\n*/\n\nSELECT t, mysql_bob/runningDifference(t/1000) mysql_bobRate, postgres/runningDifference(t/1000) postgresRate FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, countIf(service_name = 'mysql' AND from_user = 'bob') AS mysql_bob, countIf(service_name = 'postgres') AS postgres FROM default.test_grafana\n\nWHERE event_time >= toDateTime(1597214196) AND\n    from_user = 'bob'/* comment4 */\n-- comment 5\n\n    AND service_name LIKE '%sql%' GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "$rate + from in field name example",
   "type": "graph",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/256",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rate(\r\n countIf(service_name='mysql' AND from_user='bob') AS mysql_bob, countIf(service_name='postgres') AS postgres\r\n) \r\nFROM $table\r\nWHERE from_user IN ('bob','alice')",
     "rawQuery": "SELECT t, mysql_bob/runningDifference(t/1000) mysql_bobRate, postgres/runningDifference(t/1000) postgresRate FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, countIf(service_name = 'mysql' AND from_user = 'bob') AS mysql_bob, countIf(service_name = 'postgres') AS postgres FROM default.test_grafana\n\nWHERE event_time >= toDateTime(1597272895) AND\n    from_user IN ('bob','alice')\n    AND service_name LIKE '%sql%' GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "$rateColumns + subquery",
   "type": "graph",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/276",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumns(\n    'User.' || toString(from_user) || ', Serv.' || toString(service_name) as key,\n    sum(count) as value\n) FROM\n(\n    SELECT\n        toStartOfMinute(event_time) AS event_time,\n        service_name,\n        from_user,\n        count() as count\n    FROM $table\n\n    WHERE\n        $timeFilter\n    GROUP BY\n        event_time,\n        from_user,\n        service_name\n)",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM (SELECT t, groupArray((key, value)) AS groupArr FROM ( SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, 'User.' || toString(from_user) || ', Serv.' || toString(service_name) as key, sum(count) as value FROM\n(\n    SELECT\n        toStartOfMinute(event_time) AS event_time,\n        service_name,\n        from_user,\n        count() as count\n    FROM default.test_grafana\n\n    WHERE event_time >= toDateTime(1597272789) AND\n        event_time >= toDateTime(1597272789)\n        AND service_name LIKE '%sql%'\n    GROUP BY\n        event_time,\n        from_user,\n        service_name\n) GROUP BY t, key ORDER BY t, key) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "$columns + ARRAY JOIN",
   "type": "graph",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/284",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\r\n  substring(concat(JobName as JobName,' # ' , Metrics.Name as MetricName), 1, 50) as JobSource,\r\n  sum(rand() % (Metrics.Value+1)) as Kafka_lag_max\r\n)\r\nFROM $table\r\nARRAY JOIN Metrics",
     "rawQuery": "SELECT t, groupArray((JobSource, Kafka_lag_max)) AS groupArr FROM ( SELECT (intDiv(toUInt32(\"d\"), 20) * 20) * 1000 AS t, substring(concat(JobName as JobName, ' # ', Metrics.Name as MetricName), 1, 50) as JobSource, sum(rand() %(Metrics.Value + 1)) as Kafka_lag_max FROM default.test_array_join_nested\n\nARRAY JOIN Metrics\n \n WHERE \"d\" >= toDateTime(1599014729) GROUP BY t, JobSource ORDER BY t, JobSource) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_array_join_nested"
    }
   ]
  }
 ]
}