export enum InventoryType {
  externalExporter = 'externalExporter',
  mongodbExporter = 'mongodbExporter',
  mysqldExporter = 'mysqldExporter',
  postgresExporter = 'postgresExporter',
  proxysqlExporter = 'proxysqlExporter',
  nodeExporter = 'nodeExporter',
  pmmAgent = 'pmm_agent',
  qanMongodb_profiler_agent = 'qan_mongodb_profiler_agent',
  qanMysql_perfschema_agent = 'qan_mysql_perfschema_agent',
  qanMysql_slowlog_agent = 'qan_mysql_slowlog_agent',
  qanPostgresql_pgstatements_agent = 'qan_postgresql_pgstatements_agent',
  rdsExporter = 'rdsExporter',
  container = 'container',
  generic = 'generic',
  remote = 'remote',
  remote_rds = 'remote_rds',
  amazonRdsMysql = 'amazon_rds_mysql',
  mongodb = 'mongodb',
  mysql = 'mysql',
  postgresql = 'postgresql',
  proxysql = 'proxysql',
}
