{
 "title": "MongoDB PBM Details",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "rs_nm",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\"}, set)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Configured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(cluster) (mongodb_pbm_cluster_backup_configured{cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR min by(cluster) (mongodb_pbm_cluster_backup_configured{cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Agent Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "min by(host) (mongodb_pbm_agent_status{cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR min by(host) (mongodb_pbm_agent_status{cluster=~\"$cluster\", replica_set=~\"$rs_nm\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PITR Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(cluster) (mongodb_pbm_cluster_pitr_backup_enabled{cluster=~\"$cluster\", replication_set=~\"$rs_nm\"}) OR min by(cluster) (mongodb_pbm_cluster_pitr_backup_enabled{cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Size Bytes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min by(name) (mongodb_pbm_backup_size_bytes{cluster=~\"$cluster\", replication_set=~\"$rs_nm\",status=~\"done\"}) OR min by(name) (mongodb_pbm_backup_size_bytes{cluster=~\"$cluster\",status=~\"done\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(name) (mongodb_pbm_backup_duration_seconds{cluster=~\"$cluster\", replication_set=~\"$rs_nm\",status=~\"done\"}) OR avg by(name) (mongodb_pbm_backup_duration_seconds{cluster=~\"$cluster\",status=~\"done\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Backup history",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "min by(name, status) (mongodb_pbm_backup_size_bytes{cluster=~\"$cluster\", replication_set=~\"$rs_nm\",status=~\"done|error\"}) OR min by(name, status) (mongodb_pbm_backup_size_bytes{cluster=~\"$cluster\",status=~\"done|error\"})"
    }
   ]
  },
  {
   "title": "Last Successful Backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (name) (mongodb_pbm_backup_size_bytes{cluster=~\"$cluster\", replication_set=~\"$rs_nm\",status=~\"done\"}) OR min by(name) (mongodb_pbm_backup_size_bytes{cluster=~\"$cluster\",status=~\"done\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}