{
 "title": "MySQL MyRocks Details",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mysql_global_variables_rocksdb_block_cache_size{service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mysql_global_variables_rocksdb_block_cache_size, service_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "query_result(mysql_version_info{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MyRocks Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_hit{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_hit{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_miss{service_name=~\"$service_name\"}[$interval]) or  irate(mysql_global_status_rocksdb_block_cache_miss{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_add{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Added"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_add_failures{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add_failures{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Added Failures"
    }
   ]
  },
  {
   "title": "MyRocks Cache Data Bytes R/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_bytes_read{service_name=~\"$service_name\"}[$interval])  or irate(mysql_global_status_rocksdb_block_cache_bytes_read{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_bytes_write{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_bytes_write{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "MyRocks Cache Index Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_index_hit{service_name=~\"$service_name\"}[$interval])  or irate(mysql_global_status_rocksdb_block_cache_index_hit{service_name=~\"$service_name\"}[5m])) ",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_index_miss{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_miss{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_index_add{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_add{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Added"
    }
   ]
  },
  {
   "title": "MyRocks Cache Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_index_bytes_insert{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_insert{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_index_bytes_evict{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_evict{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "MyRocks Cache Filter Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_filter_hit{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_hit{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_filter_miss{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_miss{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_filter_add{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_add{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Added"
    }
   ]
  },
  {
   "title": "MyRocks Cache Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "MyRocks Cache Data Bytes Inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_block_cache_data_bytes_insert{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_data_bytes_insert{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "MyRocks Bloom Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_bloom_filter_useful{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_bloom_filter_useful{service_name=~\"$service_name\"}[5m])) ",
     "legendFormat": "Useful"
    }
   ]
  },
  {
   "title": "MyRocks Memtable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_memtable_hit{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_memtable_hit{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_memtable_miss{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_memtable_miss{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Memtable Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_rocksdb_memtable_total{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_rocksdb_memtable_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_rocksdb_memtable_unflushed{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_rocksdb_memtable_unflushed{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Unflushed"
    }
   ]
  },
  {
   "title": "MyRocks Number Of Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_keys_read{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_keys_read{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_keys_written{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_keys_written{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_keys_updated{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_keys_updated{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "MyRocks Cache L0/L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_get_hit_l0{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l0{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "L0"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_get_hit_l1{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l1{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "MyRocks Number of DB ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_db_seek{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_seek{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Seek"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_db_seek_found{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_seek_found{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Seek Found"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_db_next{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_next{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Next"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_db_next_found{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_next_found{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Next Found"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_db_prev{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_prev{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Prev"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_db_prev_found{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_prev_found{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Prev Found"
    }
   ]
  },
  {
   "title": "MyRocks R/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_bytes_read{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_bytes_read{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_bytes_written{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_bytes_written{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "MyRocks Bytes Read by Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_iter_bytes_read{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_iter_bytes_read{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "MyRocks Write ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_write_self{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_write_self{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Self"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_write_other{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_write_other{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Other"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_write_timeout{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_write_timeout{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Timeout"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_write_wal{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_write_wal{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "MyRocks WAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_wal_synced{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_wal_synced{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Syncs"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_wal_bytes{service_name=~\"$service_name\"}[$interval])  or irate(mysql_global_status_rocksdb_wal_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "MyRocks Number Reseeks in Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_number_reseeks_iteration{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_number_reseeks_iteration{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Reseeks"
    }
   ]
  },
  {
   "title": "RocksDB Row Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_rows_inserted{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_rows_inserted{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows Inserted"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_rows_updated{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_rows_updated{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows Updated"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_rows_deleted{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_rows_deleted{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows Deleted"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_rows_read{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_rows_read{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows Read"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_rows_expired{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_rows_expired{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Rows Expired"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_system_rows_deleted{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_system_rows_deleted{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "System Rows Deleted"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_system_rows_inserted{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_system_rows_inserted{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "System Rows Inserted"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_system_rows_read{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_system_rows_read{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "System Rows Read"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_system_rows_updated{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_rocksdb_system_rows_updated{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "System Rows Updated"
    }
   ]
  },
  {
   "title": "MyRocks File Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_no_file_opens{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_no_file_opens{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Open"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_no_file_closes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_no_file_closes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Closes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_no_file_errors{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_rocksdb_no_file_errors{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "RocksDB Stalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_rocksdb_stall_total_stops{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_rocksdb_stall_total_stops{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Total Stops"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_rocksdb_stall_total_slowdowns{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_rocksdb_stall_total_slowdowns{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Total Slowdowns"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_rocksdb_stall_micros{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_rocksdb_stall_micros{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Micros"
    }
   ]
  },
  {
   "title": "RocksDB Stops/Slowdowns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_stall_l0_file_count_limit_slowdowns{service_name=~\"$service_name\"}[$interval]) or\nirate(mysql_global_status_rocksdb_stall_l0_file_count_limit_slowdowns{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "L0 File count limit slowdowns"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_stall_l0_file_count_limit_stops{service_name=~\"$service_name\"}[$interval]) or\nirate(mysql_global_status_rocksdb_stall_l0_file_count_limit_stops{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "L0 File count limit stops"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_stall_locked_l0_file_count_limit_slowdowns{service_name=~\"$service_name\"}[$interval]) or\nirate(mysql_global_status_rocksdb_stall_locked_l0_file_count_limit_slowdowns{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Locked L0 File count limit slowdowns"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_stall_locked_l0_file_count_limit_stops{service_name=~\"$service_name\"}[$interval]) or\nirate(mysql_global_status_rocksdb_stall_locked_l0_file_count_limit_stops{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Locked L0 File count limit stops"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_stall_memtable_limit_slowdowns{service_name=~\"$service_name\"}[$interval]) or\nirate(mysql_global_status_rocksdb_stall_memtable_limit_slowdowns{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Memtable limit slowdowns"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_rocksdb_stall_memtable_limit_stops{service_name=~\"$service_name\"}[$interval]) or\nirate(mysql_global_status_rocksdb_stall_memtable_limit_stops{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Memtable limit stops"
    }
   ]
  },
  {
   "title": "MySQL Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Uptime",
     "type": "stat",
     "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_status_uptime{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 89 },
     "options": {
      "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
     }
    },
    {
     "title": "Current QPS",
     "type": "stat",
     "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (rate(mysql_global_status_queries{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_queries{service_name=~\"$service_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "File Handlers Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) ((sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[5m]))) / (sum\r(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[5m]))\r))"
      }
     ]
    },
    {
     "title": "Table Open Cache Miss Ratio",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (1-((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[5m])))))"
      }
     ]
    },
    {
     "title": "Table Open Cache Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_open_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Table Definition Cache Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_definition_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Service",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 89 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/mysql-instance-summary/mysql-instance-summary?var-service_name=$service_name\" target=\"_blank\">$service_name</h5>"
     }
    },
    {
     "title": "MySQL Connections",
     "type": "timeseries",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL Client Thread Activity",
     "type": "timeseries",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Running"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "timeseries",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,handler) (rate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "timeseries",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/8.4/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/8.4/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/8.4/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/8.4/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(10, avg by (service_name,command) (rate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[$interval]))>0 or \navg by (service_name,command) (irate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[5m]))>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "Process States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,state) (max_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "MySQL Network Traffic",
     "type": "timeseries",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name)  (time() - container_start_time_seconds{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "stat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \nmax by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_max(avg by () (container_memory_usage_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"} * 100 / container_spec_memory_limit_bytes{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"}),100) or  \navg by () (((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"}) * 100 or (100 - azure_memory_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "stat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}+container_spec_memory_swap_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or\nmax by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "stat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (container_fs_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \navg by () (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "stat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100 or \n(100 - azure_storage_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 117 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$node_name</a></h5>"
     }
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_system_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[5m]))),100)",
       "legendFormat": "system"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_user_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[5m]))),100)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "timeseries",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "((sum(avg_over_time(container_processes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]))-1) / avg by () (machine_cpu_cores)) or\navg by () ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(sum(rate(container_cpu_usage_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or rate(container_cpu_usage_seconds_total{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m])) or\nmax by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "timeseries",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or\navg by () (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or\navg by () ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by () (rate(container_memory_swap{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or \nirate(container_memory_swap{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5s])) or \navg by () (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(container_network_receive_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_receive_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[5m])) or\nsum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(container_network_transmit_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_transmit_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[5m])) or \nsum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}