{
 "title": "PostgreSQL Patroni Details",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "max_worker_processes",
    "query": {
     "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_parallel_workers",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_work_mem",
    "query": {
     "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(patroni_version, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(patroni_version{environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "work_mem",
    "query": {
     "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(patroni_version{service_name=~\"$service_name\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(patroni_version{environment=~\"$environment\",cluster=~\"$cluster\"}, service_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pg_static{service_name=~\"$service_name\"},version)"
    }
   },
   {
    "name": "max_connections",
    "query": {
     "query": "query_result(pg_settings_max_connections{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "shared_buffers",
    "query": {
     "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_buffers",
    "query": {
     "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_segment_size",
    "query": {
     "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "maintenance_work_mem",
    "query": {
     "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "block_size",
    "query": {
     "query": "query_result(pg_settings_block_size{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "checkpoint_segments",
    "query": {
     "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "checkpoint_timeout",
    "query": {
     "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "fsync",
    "query": {
     "query": "query_result(pg_settings_fsync{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "default_statistics_target",
    "query": {
     "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "seq_page_cost",
    "query": {
     "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "random_page_cost",
    "query": {
     "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "effective_cache_size",
    "query": {
     "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "effective_io_concurrency",
    "query": {
     "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum",
    "query": {
     "query": "query_result(pg_settings_autovacuum{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_max_workers",
    "query": {
     "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_naptime",
    "query": {
     "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_compression",
    "query": {
     "query": "query_result(pg_settings_wal_compression{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "logging_collector",
    "query": {
     "query": "query_result(pg_settings_logging_collector{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_min_duration_statement",
    "query": {
     "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_duration",
    "query": {
     "query": "query_result(pg_settings_log_duration{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_lock_waits",
    "query": {
     "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_wal_senders",
    "query": {
     "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_wal_size",
    "query": {
     "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "min_wal_size",
    "query": {
     "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(pg_up{service_name=\"$service_name\"}, service_id)"
    }
   },
   {
    "name": "scope_name",
    "label": "Scope Name",
    "query": {
     "query": "label_values(patroni_version{environment=~\"$environment\",cluster=~\"$cluster\",service_name=\"$service_name\"}, scope)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_version{service_name=~\"$service_name\",cluster=~\"$cluster\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Patroni Version",
   "type": "stat",
   "description": "Reports Patroni version number.",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_version{service_name=~\"$service_name\",scope=~\"$scope_name\"}",
     "legendFormat": "Original"
    }
   ]
  },
  {
   "title": "Patroni DCS Last Seen",
   "type": "stat",
   "description": "Last time Patroni contacted the distributed configuration store (DCS).",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_dcs_last_seen{service_name=~\"$service_name\",scope=~\"$scope_name\"}*1000"
    }
   ]
  },
  {
   "title": "Patroni Leader",
   "type": "stat",
   "description": "Is the selected Service Name node the primary cluster leader?",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_primary{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Replica",
   "type": "stat",
   "description": "Is the selected Service Name node a replica?",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_replica{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Standby Leader",
   "type": "stat",
   "description": "Is the selected Service Name node the Standby cluster leader?",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_standby_leader{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Autofailover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_is_paused{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Cluster Unlocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Falisafe Mode Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_failsafe_mode_is_active{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  { "title": "Patroni", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Patroni Nodes State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (service_name) (patroni_primary{environment=~\"$environment\",cluster=~\"$cluster\",scope=~\"$scope_name\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node_name,service_name) (pg_up[1m])*0 + on(node_name) group_left(node_name)(min by (node_name) (patroni_postgres_server_version{scope=~\"patroni_cls\",service_name=~\"$service_name\",cluster=~\"$cluster\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Reports PostgreSQL version number.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_server_version{service_name=~\"$service_name\",scope=~\"$scope_name\"}",
     "legendFormat": "Original"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postmaster_start_time{service_name=~\"$service_name\",scope=~\"$scope_name\"}*1000"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_running{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_timeline{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Pending Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_pending_restart{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "WAL Replay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_xlog_paused{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "In Archive Recovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_in_archive_recovery{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_streaming{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Sync Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_sync_standby{service_name=~\"$service_name\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Primary WAL Location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node_name,service_name) (pg_up[1m])*0 + on(node_name) group_left(node_name) patroni_xlog_location{environment=~\"$environment\",cluster=~\"$cluster\",scope=~\"$scope_name\",service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replicas Received WAL Location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node_name,service_name) (pg_up[1m])*0 + on(node_name) group_left(node_name) patroni_xlog_received_location{environment=~\"$environment\",cluster=~\"$cluster\",scope=~\"$scope_name\",service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replicas Replayed WAL Location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node_name,service_name) (pg_up[1m])*0 + on(node_name) group_left(node_name) patroni_xlog_replayed_location{environment=~\"$environment\",cluster=~\"$cluster\",scope=~\"$scope_name\",service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "WAL Replay Paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (node_name,service_name) (pg_up[1m])*0 + on(node_name) group_left(node_name) patroni_xlog_paused{environment=~\"$environment\",cluster=~\"$cluster\",scope=~\"$scope_name\",service_name=~\"$service_name\"}",
     "legendFormat": "{{cluster}} {{service_name}}"
    }
   ]
  }
 ]
}