{
 "title": "PostgreSQL Instances Overview",
 "tags": [
  "Percona",
  "PostgreSQL",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "service_type", "label": "Engine", "query": "postgresql" },
   { "name": "qthres", "label": "Query Time", "query": "0.001,0.010,0.100,1,10" },
   {
    "name": "slowq",
    "label": "slowq",
    "query": "SELECT count(*)\n   FROM pmm.metrics\n   WHERE service_type = '${service_type}'\n     AND ( period_start  >= $__fromTime AND period_start <= $__toTime )\n    AND m_query_time_cnt > 0 AND m_query_time_sum/m_query_time_cnt > ${qthres}"
   },
   {
    "name": "srvcnt",
    "query": "select count(*) from services where service_type = '${service_type}';"
   },
   {
    "name": "rangeCustom",
    "query": "select ($__toTime - $__fromTime)/60"
   },
   {
    "name": "clustercnt",
    "query": "select count(distinct(cluster)) from services where service_type = '${service_type}' and cluster <> '';"
   },
   {
    "name": "withoutcluster",
    "query": "select count(*) from services where service_type = '${service_type}' and cluster = '';"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"pg_up\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\", cluster=~\"$cluster\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up{node_name=~\"$node_name\", environment=~\"$environment\", cluster=~\"$cluster\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases Monitored",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n    color: #F9A100; \n    font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue, Helvetica, Arial, sans-serif; \n    letter-spacing: 0.011em; \n    font-weight: 600;\n    font-size: 16px;\n    -webkit-font-smoothing: antialiased;\n    border: 0px solid #ffffff;\n    border-radius: 10px;\n    background: #FFEFBA;  /* fallback for old browsers */\n    background: -webkit-linear-gradient(to right, #FFFFFF, #FFEFBA);  /* Chrome 10-25, Safari 5.1-6 */\n    background: linear-gradient(to right, #FFFFFF, #FFEFBA); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n    padding: 10px;\n    display: block;\n    width: 100%;\n    height: auto;\n    text-align: center;\n\">\n    <span style=\"color: #400004; font-size: 20px;\">${clustercnt} - Cluster</span><br/>\n    <span style=\"color: #400004; font-size: 20px;\">${srvcnt} - Nodes</span><br/>\n    <span style=\"color: #400004; font-size: 20px;\">${withoutcluster} - Nodes without cluster</span><br/>\n    <a href=\"/graph/inventory/services\" target=\"_blank\">Databases monitored</a>\n</div>\n"
   }
  },
  {
   "title": "Executed Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, avg by (service_name) (irate(mysql_global_status_questions{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(5, avg by (service_name) (rate(pg_stat_database_xact_commit{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval])) or \navg by (service_name) (irate(pg_stat_database_xact_commit{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(5, avg by (service_name) (rate(mongodb_op_counters_total{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\",type!=\"command\"}[$interval])) or \navg by (service_name) (irate(mongodb_op_counters_total{service_type=~\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\",type!=\"command\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "text",
   "description": "*Not real time. QAN is expected to have some minutes of lag",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": {
    "content": " <div style=\"\n          color: #FFFFFF; \n          font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue,Helvetica,Arial,sans-serif; \n          letter-spacing: 0.011em; \n          font-weight: 600;\n          font-size: 15px;\n          -webkit-font-smoothing: antialiased;\n          border: 0px solid #ffffff;\n          border-radius: 10px;\n          background: #23074d;  /* fallback for old browsers */\n          background: -webkit-linear-gradient(to right, #cc5333, #23074d);  /* Chrome 10-25, Safari 5.1-6 */\n          background: linear-gradient(to right, #cc5333, #23074d); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n          padding: 8px;\n          display:block;\n          width:100%;\n          height:80px;\n          \"> <span style=\"\n          color: #FBEEC1; \n          font-size: 20px;\n          \"> ${slowq} </span>Queries slower than ${qthres} sec(s) in the last ${rangeCustom} minutes*\n          </br></div>"
   }
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT period_start, service_name, avgIf(m_query_time_sum/m_query_time_cnt, m_query_time_cnt > 0) \"Execution_time\"\nFROM pmm.\"metrics\" WHERE   ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type like '%$service_type%' AND (service_name IN ($service_name)) GROUP BY period_start, service_name ORDER BY period_start ASC "
    }
   ]
  },
  {
   "title": "Transactions per Second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{service_type=\"$service_type\",service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\", datname!~\"template1|template0\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lowest Uptime (top 3)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "bottomk(3,range_last(mysql_global_status_uptime{service_type=\"$service_type\",service_name=~\"$service_name\"}[30s]))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "bottomk(3,range_last(pg_postmaster_uptime_seconds{service_type=\"$service_type\",service_name=~\"$service_name\"}[30s]))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "bottomk(3,range_last(mongodb_instance_uptime_seconds{service_type=\"$service_type\",service_name=~\"$service_name\"}[30s]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(period_start) as time, \r\nservice_name \"Service\", username, fingerprint \"Query\", avgIf(m_query_time_sum/m_query_time_cnt, m_query_time_cnt > 0) \"Execution_time\" FROM pmm.\"metrics\" WHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) AND ( service_type LIKE '%$service_type%' ) AND (service_name IN ($service_name)) GROUP BY service_name, username, fingerprint , m_query_time_sum, time ORDER BY time DESC LIMIT 10000"
    }
   ]
  }
 ]
}