{
 "title": "PostgreSQL Checkpoints, Buffers and WAL Usage",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "work_mem",
    "query": {
     "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{service_name=~\"$service_name\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up, service_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pg_static{service_name=~\"$service_name\"},version)"
    }
   },
   {
    "name": "max_connections",
    "query": {
     "query": "query_result(pg_settings_max_connections{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "shared_buffers",
    "query": {
     "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_buffers",
    "query": {
     "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_segment_size",
    "query": {
     "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "maintenance_work_mem",
    "query": {
     "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "block_size",
    "query": {
     "query": "query_result(pg_settings_block_size{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "checkpoint_segments",
    "query": {
     "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "checkpoint_timeout",
    "query": {
     "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "fsync",
    "query": {
     "query": "query_result(pg_settings_fsync{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "default_statistics_target",
    "query": {
     "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "seq_page_cost",
    "query": {
     "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "random_page_cost",
    "query": {
     "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "effective_cache_size",
    "query": {
     "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "effective_io_concurrency",
    "query": {
     "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum",
    "query": {
     "query": "query_result(pg_settings_autovacuum{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_max_workers",
    "query": {
     "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_naptime",
    "query": {
     "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "logging_collector",
    "query": {
     "query": "query_result(pg_settings_logging_collector{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_min_duration_statement",
    "query": {
     "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_duration",
    "query": {
     "query": "query_result(pg_settings_log_duration{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "log_lock_waits",
    "query": {
     "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_wal_senders",
    "query": {
     "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_wal_size",
    "query": {
     "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "min_wal_size",
    "query": {
     "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "wal_compression",
    "query": {
     "query": "query_result(pg_settings_wal_compression{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_worker_processes",
    "query": {
     "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "max_parallel_workers",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_work_mem",
    "query": {
     "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(pg_up{service_name=\"$service_name\"}, service_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Checkpointing and WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Checkpoint Timeout",
   "type": "stat",
   "description": "Maximum time between automatic WAL checkpoints.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\"}[5m])) "
    }
   ]
  },
  {
   "title": "Checkpoint Completion Target",
   "type": "stat",
   "description": "Specifies the target of checkpoint completion, as a fraction of total time between checkpoints.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_checkpoint_completion_target{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_checkpoint_completion_target{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Checkpoint Flush After",
   "type": "stat",
   "description": "Whenever more than this amount of data has been written while performing a checkpoint, attempt to force the OS to issue these writes to the underlying storage.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_checkpoint_flush_after_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_checkpoint_flush_after_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Log Checkpoints",
   "type": "stat",
   "description": "Causes checkpoints and restartpoints to be logged in the server log. Some statistics are included in the log messages, including the number of buffers written and the time spent writing them.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_log_checkpoints{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_log_checkpoints{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Log Checkpoint Warning",
   "type": "stat",
   "description": "Write a message to the server log if checkpoints caused by the filling of WAL segment files happen closer together than this amount of time (which suggests that max_wal_size ought to be raised). ",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_checkpoint_warning_seconds{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_checkpoint_warning_seconds{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "fsync",
   "type": "stat",
   "description": "If this parameter is on, the PostgreSQL server will try to make sure that updates are physically written to disk, by issuing fsync() system calls or various equivalent methods (see wal_sync_method). This ensures that the database cluster can recover to a consistent state after an operating system or hardware crash.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_fsync{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_fsync{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Min WAL Size",
   "type": "stat",
   "description": "As long as WAL disk usage stays below this setting, old WAL files are always recycled for future use at a checkpoint, rather than removed. This can be used to ensure that enough WAL space is reserved to handle spikes in WAL usage, for example when running large batch jobs.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "description": "Maximum size to let the WAL grow during automatic checkpoints. This is a soft limit; WAL size can exceed max_wal_size under special circumstances, such as heavy load, a failing archive_command or archive_library, or a high wal_keep_size setting.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "WAL Buffers",
   "type": "stat",
   "description": "The amount of shared memory used for WAL data that has not yet been written to disk. The default setting of -1 selects a size equal to 1/32nd (about 3%) of shared_buffers, but not less than 64kB nor more than the size of one WAL segment, typically 16MB.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "WAL Keep Size",
   "type": "stat",
   "description": "Specifies the minimum size of past log file segments kept in the pg_wal directory, in case a standby server needs to fetch them for streaming replication.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_wal_keep_size_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_wal_keep_size_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Full Page Writes",
   "type": "stat",
   "description": "When this parameter is on, the PostgreSQL server writes the entire content of each disk page to WAL during the first modification of that page after a checkpoint. Turning this parameter off speeds normal operation, but might lead to either unrecoverable data corruption, or silent data corruption, after a system failure.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_full_page_writes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_full_page_writes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk I/O and Swap Activity",
   "type": "timeseries",
   "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
     "legendFormat": "Disk Reads (Page In)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
     "legendFormat": "Disk Writes (Page Out)"
    },
    {
     "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "description": "A requested checkpoint happens when there is a forced checkpoint due to insufficient max_wal_size, or  when the server is stopped. \\\nA scheduled checkpoint can happen due to checkpoint_timeout being depleted, or to a CHECKPOINT command.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoints_timed{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoints_timed{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Scheduled Checkpoints"
    },
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoints_req{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoints_req{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Requested Checkpoints"
    }
   ]
  },
  {
   "title": "Background Writer Sync and Write Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "WAL Writes",
   "type": "timeseries",
   "description": "Writes to WAL log files.\\\nA custom query collector is needed for this metric to be populated by the pmm-client node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (\n  rate(pg_stat_replication_pg_current_wal_lsn_bytes{service_name=~\"$service_name\"}[$interval])\n  or\n  irate(pg_stat_replication_pg_current_wal_lsn_bytes{service_name=~\"$service_name\"}[5m])\n)",
     "legendFormat": "WAL writes"
    }
   ]
  },
  {
   "title": "WAL Writes Per Checkpoint Timeout",
   "type": "timeseries",
   "description": "Writes to WAL log files, grouped by checkpoint_timeout seconds. If the grouped average is greater than the max_wal_size value, then increasing it should yield less forced checkpointing.\\\nA custom query collector is needed for this metric to be populated by the pmm-client node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (service_name) (increase(pg_stat_replication_pg_current_wal_lsn_bytes{service_name=\"$service_name\"}[$checkpoint_timeout]))",
     "legendFormat": "WAL bytes written per checkpoint timeout"
    },
    {
     "expr": "pg_settings_max_wal_size_bytes{service_name=\"$service_name\"}",
     "legendFormat": "Max WAL size"
    }
   ]
  },
  { "title": "Buffers and Background Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\"}[5m])) "
    }
   ]
  },
  {
   "title": "BgWriter LRU Max Pages",
   "type": "stat",
   "description": "Background writer maximum number of LRU pages to flush per round.\nSmaller values of bgwriter_lru_maxpages and bgwriter_lru_multiplier reduce the extra I/O load caused by the background writer, but make it more likely that server processes will have to issue writes for themselves, delaying interactive queries.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_bgwriter_lru_maxpages{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_bgwriter_lru_maxpages{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "BgWriter Delay",
   "type": "stat",
   "description": "Specifies the delay between activity rounds for the background writer. \nIf this value is specified without units, it is taken as milliseconds.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_bgwriter_delay_seconds{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_bgwriter_delay_seconds{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "BgWriter Flush After",
   "type": "stat",
   "description": "Whenever more than this amount of data has been written by the background writer, attempt to force the OS to issue these writes to the underlying storage. Doing so will limit the amount of dirty data in the kernel's page cache, reducing the likelihood of stalls when an fsync is issued at the end of a checkpoint, or when the OS writes data back in larger batches in the background.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_bgwriter_flush_after_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_bgwriter_flush_after_bytes{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "BgWriter LRU Multiplier",
   "type": "stat",
   "description": "The number of dirty buffers written in each round is based on the number of new buffers that have been needed by server processes during recent rounds. The average recent need is multiplied by bgwriter_lru_multiplier to arrive at an estimate of the number of buffers that will be needed during the next round.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_bgwriter_lru_multiplier{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(pg_settings_bgwriter_lru_multiplier{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "BgWriter Stats Reset",
   "type": "stat",
   "description": "The last time the background writer statistics were reset.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_stats_reset{service_name=~\"$service_name\"}*1000"
    }
   ]
  },
  {
   "title": "Buffers Read",
   "type": "timeseries",
   "description": "Buffers read into the shared memory buffers. These reads could come from the page cache (memory) or I/O subsystem.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (\n  (rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service_name\"}[$interval]) * on(service_name)(pg_settings_block_size{service_name=~\"$service_name\"}))\n  or\n  (irate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service_name\"}[5m]) * on(service_name) \n(pg_settings_block_size{service_name=~\"$service_name\"})\n))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffers Written",
   "type": "timeseries",
   "description": "Buffers written to disk during checkpoints, by the background writer, or by backend processes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (\n  (rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service_name\"}[$interval]) * on(service_name) (pg_settings_block_size{service_name=~\"$service_name\"}[$interval]))\n  or\n  (irate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service_name\"}[5m]) * on(service_name) (pg_settings_block_size{service_name=~\"$service_name\"}[5m])\n))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (\n  (rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service_name\"}[$interval]) * on(service_name) (pg_settings_block_size{service_name=~\"$service_name\"}[$interval]))\n  or\n  (irate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service_name\"}[5m]) * on(service_name) (pg_settings_block_size{service_name=~\"$service_name\"}[5m]))\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "By the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (\n  (rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service_name\"}[$interval]) * on(service_name) (pg_settings_block_size{service_name=~\"$service_name\"}[$interval]))\n  or\n  (irate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service_name\"}[5m]) * on(service_name) (pg_settings_block_size{service_name=~\"$service_name\"}[5m]))\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "During checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Fsync Backend Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service_name\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service_name\"}[5m])) * 8192",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Background Writer Stops due to LRU max Reached",
   "type": "timeseries",
   "description": "The background writer was forced to stop due to reaching the max page limit (bgwriter_lru_maxpages).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(pg_stat_bgwriter_maxwritten_clean{service_name=~'$service_name'}[$interval]) or\nirate(pg_stat_bgwriter_maxwritten_clean{service_name=~'$service_name'}[5m]))",
     "legendFormat": "Stops due to LRU max"
    }
   ]
  }
 ]
}