import { apiRequestManagement } from 'shared/components/helpers/api';
import {
  Kubernetes,
  KubernetesListAPI,
  NewKubernetesCluster,
  NewKubernetesClusterAPI,
} from './Kubernetes.types';

export const KubernetesService = {
  getKubernetes() {
    return apiRequestManagement.post<KubernetesListAPI, any>('/DBaaS/Kubernetes/List', {});
  },
  deleteKubernetes(kubernetes: Kubernetes) {
    return apiRequestManagement.post<any, any>('/DBaaS/Kubernetes/Unregister', toAPI(kubernetes));
  },
  getKubernetesConfig(kubernetes: Kubernetes) {
    return  {
      apiVersion: 'v1',
      clusters: [
        {
          cluster: {
            'certificate-authority-data':
              'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01URXhOakE0TURZeU0xb1hEVE13TVRFeE5UQTRNRFl5TTFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSy9FCjFsbS9mWmY4T3pDVjN4bHBZNXNmN3BSYkN4M2JDYnpwMXlsUE1LRkRMYW56UW0wRjJQOXU5NERGMGtKU3pTeGQKbVNTdkdjd3dxQkxRVnhqM1hkSEhDZ0dFY09tUmhWd3YxaytqTzVCYWQzdHZwS1l4eXQ2Y2lnWitMRDhaZnF3OQpqNFk1ekZ1SFhtOVlvYXRidDFjaUlnTGthcFdEZ1JtMm9mZjRkVC9KYnZ3bFpjOWs2NWovUkhYN00xL1VoN244CjJndlY5eVBJZ0xzQjQ3eE9SdDZudXJXWjFEU3VhOEtFMDlHdkJaYmsxcGtyaGxja01PSllud25DZEtpaFdsUGkKWnpoR2VSVUpJWHkwd3hmYm9aWnBqaExCY252QVd6UVBpdmxnSDZ1R0FYd09XV0d4aTRITTRnUjlOZHZtZ1grZQpERU9KNXZyUlJ6ZjZpNUdOZ1ZrQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSUFFsK2VjN080emlaS1Q5MEQ5ZTNTbGt4N3RqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvR0pXMWVCbwpUcU9DenNoWjF3SElNbWlBV0QySDFKcG9CNWpIRTdIQ2dRZFBhU3RXKzEyR2xEVmcxQ1F1ai9sOFlDMXVHVk9tCmh6ckhxSWZnKzBSNWVyYThlamVDZGxXc2ZOTU1ST1RuclQ5TXlSYU9lUC9MVXB5eElpWFQ5QjNvTDhtL3o0N0oKelFpSjdjaVN1SGdwalhQeDZrNmRxTWQ4Qmk1YXdDVi9RZWVJUHhEU0dmOERFMTY1bGU0MHBlbXJwQy9XVGRBZgpJRjNEZzlseExlalpmTFVHWmFtSnN3NjE0WGk0VkxQWmNZZmd0azJFYVhYMm5PVEdDbjZVUUV6YmhCczR3YTN1CjdKZXNyaUZEYkdyY2hsRnpjWTFwS0duTi9FMmZaMFVFVXFka29QT2lEV0VuYjVVbDk3WjQrRVdlMThIcmhCb0cKVnlxMGhRZFFPK0dodUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==',
            server: 'https://127.0.0.1:32768',
          },
          name: 'minikube',
        },
      ],
      contexts: [
        {
          context: {
            cluster: 'minikube',
            namespace: 'default',
            user: 'minikube',
          },
          name: 'minikube',
        },
      ],
      'current-context': 'minikube',
      kind: 'Config',
      preferences: {},
      users: [
        {
          name: 'minikube',
          user: {
            'client-certificate-data':
              'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01URXhPVEE0TlRZMU1sb1hEVEl4TVRFeU1EQTROVFkxTWxvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ3pldjloQlc5a0I1MHQrMGVpdndzNnVGTk9QS2QKRXkzRXlmWGlFWkViK21vTGUrcGUvU3ZQWmRBVndpZ1NYVThzMmhpb2R6NzN0eWpTOW9XK1ptOVU5eU9aRVB5eQpiSGtERjNVT2U5N1dTRHJraTVORER0SFY3L2RjSnF0VTBDV1hzbFhpNDdUK3R4aHl6R0lxWkxNbTE3Z2VuOXFuCjc4ZDF0dkczWHdheUpjVEtXbW0vWkxmTlNaREZTMUFuTUNCMzA5RnVhNXM4dG5XV09yYWVpUHphQVNOdVlqU3oKSTFpNlJoNzVnZHByWktxK0NPMHVBYU03V0VRT1h0Sm5GeTJ0MWtLV1lYNE9HbkI1Q2NwOU5GdnE2NGdCT1MwVQpiTWZGR2xQc3owREk5NE5PR0dlNjVHWmlWaWN1VDhZdDA0eHZ6eDRXWFJvaklRWmFCR0NvMkhHbkFnTUJBQUdqCllEQmVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSUFFsK2VjN080emlaS1Q5MEQ5ZTNTbGt4Nwp0akFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVU56dnZuR0dleTdOdXBDR3FDbUlzZVFkaWhXR1diOTAxSjBtCnFXRzQzTHdGdTA1Qis2RTBkdWRvMFZrQjZJT3FPVzF3b2JuanMvdndGL0VaMy83QXRWZDk5T2xBQU1CQkhZMXUKVUdBOEgyOGQxbldYS00vNUZHaUlGZUhFS1NtaDdKeU5uK3d1S0thWjIzOWY1MXpSekx5SXY4NW1qdWRveDU4MgpNK0dZcExiOHRLbVFXKzNwejMrREVjeGh2cU9RcUtHdERZUmthQllveFhBYi8vdGFvSDRKekNOV2tUMy9odVNVCk1YbkhoOThrTXBOdE9nN3laa1QrQTBEQ1RIaW5uYjh2RkFScVRGbHB2VzJBVHZuY2V6amJpa2pIc25wdmxvUCsKRlRXczg1UUtFdUEwM2VwSFhkSDBDZjVyN2VKOWF2citrSkRjOWpxZEN2S3U5S3lvSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==',
            'client-key-data':
              'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBd3Mzci9ZUVZ2WkFlZExmdEhvcjhMT3JoVFRqeW5STXR4TW4xNGhHUkcvcHFDM3ZxClh2MHJ6MlhRRmNJb0VsMVBMTm9ZcUhjKzk3Y28wdmFGdm1adlZQY2ptUkQ4c214NUF4ZDFEbnZlMWtnNjVJdVQKUXc3UjFlLzNYQ2FyVk5BbGw3SlY0dU8wL3JjWWNzeGlLbVN6SnRlNEhwL2FwKy9IZGJieHQxOEdzaVhFeWxwcAp2MlMzelVtUXhVdFFKekFnZDlQUmJtdWJQTFoxbGpxMm5vajgyZ0VqYm1JMHN5Tll1a1llK1lIYWEyU3F2Z2p0CkxnR2pPMWhFRGw3U1p4Y3RyZFpDbG1GK0RocHdlUW5LZlRSYjZ1dUlBVGt0Rkd6SHhScFQ3TTlBeVBlRFRoaG4KdXVSbVlsWW5May9HTGRPTWI4OGVGbDBhSXlFR1dnUmdxTmh4cHdJREFRQUJBb0lCQVFEQWpGMjRaYmcvZUpaQgo5QktTWC9wR1E1dVNncmw3L0pyK3FrazV2UGRiV2pjN1JxNHdXYm5WOCtLcnZ3OXdwMzQ4N1EzMlpuZDh6ak94CjRpM3NOci9Ra2I5RDZvQjdzN0FoR0N5QnRucFovMmNHdzljNUx3ckZsYjAvL3BEVzhpNVdOTldqd0VNRWllSEcKaHJKNUNMUHpyc0cwczNpakNlUnpPL0xMdDBlZENQR1NuOEpTWFJBcXNxOFV2NkdPQlJCSCtMdnlTc2tDeHVOcQpXT05kWmRDbnFQVE11SFJtZDErSHQ5VUtYNUdjcHdzQk9Ja1g3ZFpWbE53bTBxN29NTWhaNkRtSmVjMW9PcU9SCkcwNy9SS1pPT0t5OXlHc3p1M1JIUTdPd3dVMzNPNGZ5YzJLa0ZRcTQzODBQUTJiVzJyZHZ6MEcvMDA1R1dEU3IKQ3lVUVpSdGhBb0dCQU8zcjhpUklpWkhINWVqZ0FMWG9rZ2pGT241L0FFWjFOZ0VrRzgzTmJuNWhwVU9xWUFyMwptRDdHWGlhRVRsbjltOU1VWm9ibzNSeFN0bnZOZVBQd0dEbC9tbGYxV0lLak0vc2p5UU02SWhScWxGTW40TzBXCjJWOUhGZWZocExyRVlKNGFLeCs4UjFkb2ZLeXNTQTNHRUVmOFNJOGRtVW1kVW8vMFljK1FnTFR2QW9HQkFOR2IKUWgyS2hmOWRLcldBSkdUT3ZqaUd4SWJ3WDJ3M1ZhK2VGc3NTdjYrS0xRU1JUTU4vNnNjLzc3cXNEVTFXU0pwTApxcUJRaTFzZGkwSFRMaXJPS1Zzd2pERGZVaER1a2toTUtQcXd4WEp1bGFiSVBHNmpqQzhYVm1uY1BwaTdkdUU2CkxISHRUaUIxczZ5alpnK2p6WHhxdGNNdVJTOTdVdkduVjA0a2o3N0pBb0dCQU9vUUIwVyt2dWhXT2s3aG9KRlYKWGVXVzhyYmpob2ZLWS9pM1owc09ZVGVnSkkvdkcxRnV4NjVxUk5HcnM5RkFlSDR1UWJkVGU4T1RjOGRVR3p3UQo1aVFhN3VLOWtmZmpTdzQwNUZweVpIaWxhWXB0WHhDZ08vVkozN2toK1lkc0Rvazd3VlVWU3pJb3J3N0k1cEgyCldxb1cvZU1lQVdHMGpqYmsreHpTVW15dEFvR0FLakh3RUZSWGZ6MjVJRXFJaVFhWmduV1cwSGRKTGxiQldCWWkKRG9WYXN6TEV0enVzMFZwSjRBeDk3UDAvdkViWFhNQkl1L2NhNXArKzdlUmVVZDJvczZQRlJQMWYzdXEzNWZmMgo4K2hzQndvOTlCSXhJRENxUXJ5Vzk3NlBsMTE5by85Ni9RQkJqd1ZDdzBrdGZZNkRDajNORTFxWU1PUEpvYjRICk5FTGw4UWtDZ1lCdzhSSytndWFiT0M1ZlVSbnNHLzY2YlRRRTlLNEV2dGNrRk5FWHFzUlJhWHUwNjhRRlJQNjMKaFR5S0pNWU1kMVg3VnZkbCsyN3daN1BjQnF1ZC9iVkRNRnBHaEFOWStGWk85ekFFbWk1MzMzMERqaENmRGFHMwpVWGhoOWZ0djlWRlVEVTR6RVgrNzJoVVdUcU9TTjFxL2J0dVdabzhqaHBMU2RoM0V5aXdEQnc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=',
          },
        },
      ],
    };
    return apiRequestManagement.post<any, any>('/DBaaS/Kubernetes/GetKuberneteCluster', toAPI(kubernetes));
  },
  addKubernetes(kubernetes: NewKubernetesCluster) {
    return apiRequestManagement.post<NewKubernetesClusterAPI, any>(
      '/DBaaS/Kubernetes/Register',
      newClusterToApi(kubernetes),
    );
  },
};

const toAPI = (kubernetes: Kubernetes) => ({
  kubernetes_cluster_name: kubernetes.kubernetesClusterName,
});

const newClusterToApi = (newCluster: NewKubernetesCluster): NewKubernetesClusterAPI => ({
  kubernetes_cluster_name: newCluster.name,
  kube_auth: {
    kubeconfig: newCluster.kubeConfig,
  },
});
