{
 "title": "Databases on Kubernetes - Summary",
 "description": "Dashboard for DB Clusters managed with Percona Kubernetes Operators",
 "tags": [
  "Percona",
  "Operators",
  "Kubernetes"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "k8s_cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "label_values(container_cpu_system_seconds_total,k8s_cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_app_kubernetes_io_managed_by=~\"percona-xtradb-cluster-operator|percona-postgresql-operator|percona-server-mongodb-operator|percona-server-mysql-operator\",k8s_cluster_id=\"$k8s_cluster\"}, namespace)"
    }
   },
   {
    "name": "k8s_db_type",
    "label": "Operator",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\"},label_app_kubernetes_io_managed_by)"
    }
   },
   {
    "name": "k8s_db_cr",
    "label": "Database Name",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_id=\"$k8s_cluster\",label_app_kubernetes_io_managed_by=\"$k8s_db_type\",namespace=\"$namespace\"},label_app_kubernetes_io_instance)"
    }
   },
   {
    "name": "k8s_db_pods",
    "label": "DB Pods",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",label_app_kubernetes_io_managed_by=\"$k8s_db_type\",label_app_kubernetes_io_instance=\"$k8s_db_cr\",label_app_kubernetes_io_component=~\"cfg|mongod|pxc|pg\"}, pod)"
    }
   },
   {
    "name": "k8s_proxy_pods",
    "label": "DB Proxy Pods",
    "query": {
     "query": "label_values(kube_pod_labels{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",label_app_kubernetes_io_managed_by=\"$k8s_db_type\",label_app_kubernetes_io_instance=\"$k8s_db_cr\",label_app_kubernetes_io_component=~\"mongos|haproxy|proxysql|pgbouncer\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database Generic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "state-timeline",
   "description": "Custom resource status",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(kube_pxc_status_state{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"${namespace}\",name=\"${k8s_db_cr}\"}) by (state) if \"${k8s_db_type}\"==\"percona-xtradb-cluster-operator\") !=0",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "(sum(kube_psmdb_status_state{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"${namespace}\",name=\"${k8s_db_cr}\"}) by (state) if \"${k8s_db_type}\"==\"percona-server-mongodb-operator\") !=0\n",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "(sum(kube_pg_status_state{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"${namespace}\",name=\"${k8s_db_cr}\"}) by (state) if \"${k8s_db_type}\"==\"percona-postgresql-operator\") !=0\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "table",
   "description": "Shows the list of backups for the cluster and their statuses",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "(kube_pxc_backup_status_state{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",dbcluster=\"$k8s_db_cr\"} if \"${k8s_db_type}\"==\"percona-xtradb-cluster-operator\") !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kube_pg_backup_status_state{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",dbcluster=\"$k8s_db_cr\"} if \"${k8s_db_type}\"==\"percona-postgresql-operator\") !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kube_psmdb_backup_status_state{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",dbcluster=\"$k8s_db_cr\"} if \"${k8s_db_type}\"==\"percona-server-mongodb-operator\") !=0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Number of vCPU cores used by a container. \nCPU Limit is shown only if it is set in the Custom Resource (recommended).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\"}[$__rate_interval])) by (container,pod)",
     "legendFormat": "{{pod}} - CPU cores"
    },
    {
     "expr": "(max(label_replace(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\",resource=\"cpu\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-.{1}\")) by (pod_set) if \"${k8s_db_type}\"==\"percona-server-mongodb-operator\") !=0",
     "legendFormat": "CPU Limit - {{pod_set}}"
    },
    {
     "expr": "(max(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\",resource=\"cpu\"})if \"${k8s_db_type}\"==\"percona-xtradb-cluster-operator\") !=0",
     "legendFormat": "CPU Limit "
    },
    {
     "expr": "(max(label_replace(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\",resource=\"cpu\"}, \"pod_set\", \"$1\", \"pod\", \"${k8s_db_cr}-(.*)-.{4}-.{1}\")) by (pod_set) if \"${k8s_db_type}\"==\"percona-postgresql-operator\") !=0",
     "legendFormat": "CPU Limit - {{pod_set}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Number of bytes used by a container. \nMemory Limit is shown only if it is set in the Custom Resource (recommended).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\"}) by (container,pod)",
     "legendFormat": "{{pod}} - Bytes"
    },
    {
     "expr": "(max(label_replace(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\",resource=\"memory\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-.{1}\")) by (pod_set) if \"${k8s_db_type}\"==\"percona-server-mongodb-operator\") !=0",
     "legendFormat": "Memory Limit - {{pod_set}}"
    },
    {
     "expr": "(max(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\",resource=\"memory\"})if \"${k8s_db_type}\"==\"percona-xtradb-cluster-operator\") !=0",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "(max(label_replace(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_db_pods}\", container=~\"mongod|pxc|database\",resource=\"memory\"}, \"pod_set\", \"$1\", \"pod\", \"${k8s_db_cr}-(.*)-.{4}-.{1}\")) by (pod_set) if \"${k8s_db_type}\"==\"percona-postgresql-operator\") !=0",
     "legendFormat": "Memory Limit - {{pod_set}}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "description": "Persistent Volume Claim storage usage in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"${namespace}\"}) by (persistentvolumeclaim) and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{k8s_cluster_id=\"$k8s_cluster\",label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Storage Utilization ",
   "type": "timeseries",
   "description": "Percentage of how much of a storage capacity is utilized",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(kubelet_volume_stats_used_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=~\"${namespace}\"}) by (persistentvolumeclaim) and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"})\n/ (sum(kubelet_volume_stats_capacity_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=~\"${namespace}\"}) by (persistentvolumeclaim) and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Database Pods Status",
   "type": "timeseries",
   "description": "Status of Pods - shows if they were restarted and when",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",pod=~\"$k8s_db_pods\",phase=\"Running\"}) by (phase,pod) ",
     "legendFormat": "{{pod}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Proxy Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Number of vCPU cores used by a container. \nCPU Limit is shown only if it is set in the Custom Resource (recommended).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_proxy_pods}\", container=~\"pgbouncer|haproxy|proxysql|mongos\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}} - CPU cores"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_proxy_pods}\", container=~\"pgbouncer|haproxy|proxysql|mongos\",resource=\"cpu\"})",
       "legendFormat": "CPU Limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Number of bytes used by a container. \nMemory Limit is shown only if it is set in the Custom Resource (recommended).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_proxy_pods}\", container=~\"pgbouncer|haproxy|proxysql|mongos\"}) by (container,pod)",
       "legendFormat": "{{pod}} - Bytes"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"${k8s_proxy_pods}\", container=~\"pgbouncer|haproxy|proxysql|mongos\", resource=\"memory\"}) ",
       "legendFormat": "Memory Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=~\"${namespace}\",pod=~\"$k8s_db_pods\",container!~\"logs|logrotate\"} and on (pod) kube_pod_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"}",
       "legendFormat": "{{pod}} ( {{container}} )"
      }
     ]
    },
    {
     "title": "Last Terminated Reason",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"${namespace}\",reason=\"ContainerCannotRun\"} and on (pod) kube_pod_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"}",
       "legendFormat": "{{pod}} ( {{container}} )"
      },
      {
       "expr": "(kube_pod_container_status_last_terminated_reason{namespace=\"${namespace}\" ,reason=\"OOMKilled\"} and on (pod) kube_pod_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"})+1",
       "legendFormat": "{{pod}} ( {{container}} )"
      },
      {
       "expr": "(kube_pod_container_status_last_terminated_reason{namespace=\"${namespace}\" ,reason=\"Completed\"} and on (pod) kube_pod_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"})+2",
       "legendFormat": "{{pod}} ( {{container}} )"
      },
      {
       "expr": "(kube_pod_container_status_last_terminated_reason{namespace=\"${namespace}\" ,reason=\"Error\"} and on (pod) kube_pod_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"})+3",
       "legendFormat": "{{pod}} ( {{container}} )"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PVC Stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_keep((kube_persistentvolumeclaim_info{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\"} and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"}),\"persistentvolumeclaim\",\"storageclass\")"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_id=\"$k8s_cluster\",namespace=~\"${namespace}\"} and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{k8s_cluster_id=\"$k8s_cluster\",namespace=\"$namespace\",label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"},\"namespace\")"
      },
      {
       "expr": "label_keep(kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\"} and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"},\"persistentvolumeclaim\",\"phase\") !=0",
       "legendFormat": "{{Status}}"
      }
     ]
    },
    {
     "title": "Volume Usage Rate /min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{k8s_cluster_id=\"${k8s_cluster}\",namespace=~\"${namespace}\"} and on (persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_app_kubernetes_io_managed_by=\"${k8s_db_type}\",label_app_kubernetes_io_instance=\"${k8s_db_cr}\"}[60s])",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Database - Network - Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Recieved)"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Transmitted)"
      }
     ]
    },
    {
     "title": "Database - Network - Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} (Received )"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} {Transmitted)"
      }
     ]
    },
    {
     "title": "Database - Network - Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Received)"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_dropped_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Transmitted)"
      }
     ]
    },
    {
     "title": "Database - Network - Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Received)"
      },
      {
       "expr": "- sum(rate(container_network_transmit_errors_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_db_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Transmitted)"
      }
     ]
    },
    {
     "title": "Proxy - Network - Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Recieved)"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Transmitted)"
      }
     ]
    },
    {
     "title": "Proxy - Network - Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} (Received )"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}} {Transmitted)"
      }
     ]
    },
    {
     "title": "Proxy - Network - Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Received)"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_dropped_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Transmitted)"
      }
     ]
    },
    {
     "title": "Proxy - Network - Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Received)"
      },
      {
       "expr": "- sum(rate(container_network_transmit_errors_total{k8s_cluster_id=\"${k8s_cluster}\",namespace=\"$namespace\", pod=~\"$k8s_proxy_pods\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}(Transmitted)"
      }
     ]
    }
   ]
  }
 ]
}