{
 "title": "Kubernetes Cluster Summary",
 "tags": [ "Percona" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WARNING! Experimental Dashboard. Expand to read more.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experimental Dashboard",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "options": {
      "content": "## Disclaimer \n\nThis Experimental Dashboard is not a part of the official Percona Monitoring and Management (PMM) deployment and might be updated. \nWe ship this Dashboard to obtain feedback from our users. \n\nOnce we officially release this Dashboard, it will be moved to the appropriate folder. \n\n## About Dashboard\n\nThis Dashboard is a part of the [DBaaS solution](https://per.co.na/dbaas) in PMM.\nThis Dashboard displays the resource consumption in the K8s Cluster.\n\nTo provide feedback on the Dashboard, visit [our forum](https://forums.percona.com/c/percona-monitoring-and-management-pmm/pmm-unofficial-dashboards-and-plugins/67)."
     }
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "description": "Total number of Pods in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total containers",
   "type": "stat",
   "description": "Total number of containers in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_container_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total PVCs",
   "type": "stat",
   "description": "Total number of Persistent Volume Claims in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "description": "Number of CPU cores available in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU requests",
   "type": "stat",
   "description": "Cores requested by containers",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "description": "CPU utilization of the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[$interval])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total available memory in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory requests",
   "type": "stat",
   "description": "Memory requested by containers",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "description": "Memory utilization of the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$node_name\"}[$interval])) / sum (machine_cpu_cores{node=~\"$node_name\"}) * 100",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\",node=~\"$node_name\"}) / sum(machine_cpu_cores{node=~\"$node_name\"}) * 100",
     "legendFormat": "CPU Request %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\",node=~\"$node_name\"}) / sum(machine_cpu_cores{node=~\"$node_name\"}) * 100",
     "legendFormat": "CPU Limit %"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$node_name\"}) / sum (machine_memory_bytes{node=~\"$node_name\"}) * 100",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\",node=~\"$node_name\"}) / sum(machine_memory_bytes{node=~\"$node_name\"}) * 100",
     "legendFormat": "Memory Requests % "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\",node=~\"$node_name\"}) / sum(machine_memory_bytes{node=~\"$node_name\"}) * 100",
     "legendFormat": "Memory Limit  %"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",node=~\"$node_name\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\",node=~\"$node_name\"})",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "PV and PVC Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Bound\"})",
     "legendFormat": "PVC Bound"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Pending\"})",
     "legendFormat": "PVC Pending"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Lost\"})",
     "legendFormat": "PVC Lost"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Available\"})",
     "legendFormat": "PV Available"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Bound\"})",
     "legendFormat": "PV Bound"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Pending\"})",
     "legendFormat": "PV Pending"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Released\"})",
     "legendFormat": "PV Released"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Failed\"})",
     "legendFormat": "PV Failed"
    }
   ]
  },
  {
   "title": "Pod containers by waiting reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Cluster Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"$node_name\"})[$interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{node=~\"$node_name\"})[$interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "sum(kube_job_status_active)", "legendFormat": "Active" },
    { "expr": "sum(kube_job_status_succeeded)", "legendFormat": "Succeeded" },
    { "expr": "sum(kube_job_status_failed)", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase='Running'})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=~\"$namespace\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{namespace=~\"$namespace\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=~\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "PVC Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 53 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  }
 ]
}