{
 "title": "Valkey/Redis Persistence Details",
 "description": "Valkey/Redis Persistence Details Dashboard",
 "tags": [
  "Valkey",
  "Redis",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "service_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Master AOF persistence ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_enabled{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Appendfsync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_config_key_value{key=\"appendfsync\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Loading Dump",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_loading_dump_file{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Delayed fsyncs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_delayed_fsync{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Last rewrite duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_last_rewrite_duration_sec{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Last COW size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_last_cow_size_bytes{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Last rewrite success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_last_write_status{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Async Loading",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_async_loading{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Base, current, last COW size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_aof_base_size_bytes{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "redis_aof_current_size_bytes{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "redis_aof_last_cow_size_bytes{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Master RDB persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Last bgsave timestamp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_rdb_last_save_timestamp_seconds{service_name=~\"$service_name\"} * 1000 and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Last bgsave success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_status{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Changes since lastsave",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_rdb_changes_since_last_save{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "Save config",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "redis_config_key_value{key=\"save\", service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  },
  {
   "title": "RDB saves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_rdb_saves_total{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"master\"}"
    }
   ]
  }
 ]
}