{
 "title": "Valkey/Redis Clients",
 "description": "Valkey/Redis Clients Dashboard",
 "tags": [
  "Redis",
  "Valkey",
  "Percona"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{cluster=~\"$cluster\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up{node_name=~\"$node_name\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connected Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service_name - Connected/Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name)(redis_connected_clients{service_name=~\"$service_name\"})",
     "legendFormat": "Connected - {{service_name}}"
    },
    {
     "expr": "sum by(service_name)(redis_blocked_clients{service_name=~\"$service_name\"})",
     "legendFormat": "Blocked - {{service_name}}"
    }
   ]
  },
  {
   "title": "Config Max Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_config_maxclients{service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_evicted_clients_total{service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$service_name - client Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(redis_client_recent_max_input_buffer_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "(rate(redis_client_recent_max_output_buffer_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Output"
    }
   ]
  }
 ]
}