{
 "title": "Valkey/Redis Memory",
 "description": "Valkey/Redis Memory Dashboard",
 "tags": [
  "Redis",
  "Valkey",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{cluster=~\"$cluster\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up{node_name=~\"$node_name\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (redis_memory_used_bytes{service_name=~\"$service_name\"}  / redis_memory_max_bytes{service_name=~\"$service_name\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Eviction Policy",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_instance_info{service_name=~\"$service_name\"} and on(service_name) redis_instance_info{role=\"primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Keys",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "min by (service_name) (redis_db_keys{service_name=~\"$service_name\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{service_name=~\"$service_name\"}",
     "legendFormat": "used, {{ service_name}}"
    },
    {
     "expr": "redis_memory_max_bytes{service_name=~\"$service_name\"}",
     "legendFormat": "max, {{ service_name}}"
    }
   ]
  },
  { "title": "Expiry and Eviction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Expired/Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{service_name=~\"$service_name\"}[5m])) by (service_name)",
     "legendFormat": "expired, {{ service_name}}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{service_name=~\"$service_name\"}[5m])) by (service_name)",
     "legendFormat": "evicted, {{ service_name}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{service_name=~\"$service_name\"}) by (service_name) - sum (redis_db_keys_expiring{service_name=~\"$service_name\"}) by (service_name)",
     "legendFormat": "not expiring, {{ service_name}}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{service_name=~\"$service_name\"}) by (service_name)",
     "legendFormat": "expiring, {{ service_name }}"
    }
   ]
  }
 ]
}