{
 "title": "Valkey Sentinel",
 "description": "Valkey Sentinel Dashboard",
 "tags": [
  "Valkey",
  "Redis",
  "Percona"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(node_name) (redis_uptime_in_seconds{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq|nice\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq|nice\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node_name - Total Commands / sec",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(node_name) (rate(redis_commands_total{node_name=~\"$node_name\"}[$__interval]))",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "$node_name - read and Write rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(node_name) (rate(redis_total_reads_processed{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Reads_{{label_name}}"
      },
      {
       "expr": "sum by(node_name) (rate(redis_total_writes_processed{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$node_name - command ops/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(redis_commands_total{node_name=~\"$node_name\"} [1m])) by (node_name,cmd)",
       "legendFormat": "{{ node_name,  cmd }}"
      }
     ]
    },
    {
     "title": "$node_name - Hits / Misses per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{node_name=~\"$node_name\"}[5m])",
       "legendFormat": "hits, {{ node_name }}"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{node_name=~\"$node_name\"}[5m])",
       "legendFormat": "misses, {{ node_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(100 * (redis_memory_used_bytes{node_name=~\"$node_name\"}  / redis_memory_max_bytes{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 3, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_memory_used_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "used, {{ node_name }}"
      },
      {
       "expr": "redis_memory_max_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "max, {{ node_name }}"
      }
     ]
    },
    {
     "title": "Eviction Policy",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 14, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_instance_info{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Keys",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
     "targets": [
      {
       "expr": "redis_db_keys{db=\"db0\", node_name=~\"$node_name\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - network I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rate(redis_net_input_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{ input }}"
      },
      {
       "expr": "(rate(redis_net_output_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{ output }}"
      }
     ]
    },
    {
     "title": "Connected/Blocked Clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(node_name)(redis_connected_clients{node_name=~\"$node_name\"})",
       "legendFormat": "connected_{{node_name}}"
      },
      {
       "expr": "sum by(node_name)(redis_blocked_clients{node_name=~\"$node_name\"})",
       "legendFormat": "blocked_{{node_name}}"
      }
     ]
    },
    {
     "title": "$node_name - client Buffers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rate(redis_client_recent_max_input_buffer_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{ input }}"
      },
      {
       "expr": "(rate(redis_client_recent_max_output_buffer_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{ output }}"
      }
     ]
    },
    {
     "title": "Config Max Clients",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_config_maxclients{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Evicted Clients",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_evicted_clients_total{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Expiry and Eviction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired/Evicted Keys",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(redis_expired_keys_total{node_name=~\"$node_name\"}[5m])) by (node_name)",
       "legendFormat": "expired, {{ node_name}}"
      },
      {
       "expr": "sum(rate(redis_evicted_keys_total{node_name=~\"$node_name\"}[5m])) by (node_name)",
       "legendFormat": "evicted, {{ node_name}}"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{instance=~\"$node_name\"}) by (node_name) - sum (redis_db_keys_expiring{node_name=~\"$node_name\"}) by (node_name)",
       "legendFormat": "not expiring, {{ instance }}"
      },
      {
       "expr": "sum (redis_db_keys_expiring{node_name=~\"$node_name\"}) by (node_name)",
       "legendFormat": "expiring, {{ node_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Command Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - top 10 total time by command",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 8, "x": 0, "y": 47 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk by() (10, sum by(node_name, cmd) (redis_commands_duration_seconds_total{node_name=~\"$node_name\"}) != 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$node_name - total Time Spent by Command / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(cmd, node_name) (irate(redis_commands_duration_seconds_total{node_name=~\"$node_name\"}[1m])) != 0",
       "legendFormat": "{{ node_name, cmd }}"
      }
     ]
    },
    {
     "title": "Commands Totals",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by(node_name) (redis_total_reads_processed{node_name=~\"$node_name\"})",
       "legendFormat": "reads_{{node_name}}"
      },
      {
       "expr": "sum by(node_name) (redis_total_writes_processed{node_name=~\"$node_name\"})",
       "legendFormat": "writes_{{node_name}}"
      },
      {
       "expr": "sum(redis_errors_total{node_name=\"$node_name\"})",
       "legendFormat": "errors_{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 48 },
     "repeat": "node_name",
     "targets": [
      {
       "expr": "redis_instance_info{node_name=~\"$node_name\"}",
       "legendFormat": "{{node_name}}_role"
      }
     ]
    },
    {
     "title": "Replica vs Master offsets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_connected_slave_offset_bytes{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "redis_master_repl_offset{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}",
       "legendFormat": "__auto"
      },
      { "expression": "$B- $A", "type": "math" }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 57 },
     "targets": [
      {
       "expr": "redis_connected_slaves{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backlog first byte offset",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_repl_backlog_first_byte_offset{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backlog History Bytes",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 17, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_repl_backlog_history_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backlog Size",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_replication_backlog_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connected Replicas",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 17, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_connected_slaves{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replica Resync Info",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "redis_replica_resyncs_full{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "redis_replica_partial_resync_accepted{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "redis_replica_partial_resync_denied{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Partial resyncs",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_replica_partial_resync_accepted{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Full resyncs",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 17, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_replica_resyncs_full{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO thread R/W per Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(redis_io_threaded_reads_processed{node_name=~\"$node_name\"}[5m])",
       "legendFormat": "reads"
      },
      {
       "expr": "irate(redis_io_threaded_writes_processed{node_name=~\"$node_name\"}[5m])",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "IO threads active",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(node_name) (redis_io_threads_active{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "IO threads configured",
     "type": "table",
     "gridPos": { "h": 7, "w": 2, "x": 22, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_config_io_threads{node_name=~\"$node_name\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Master AOF persistence ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Base, current, last COW size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "redis_aof_base_size_bytes{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}"
      },
      {
       "expr": "redis_aof_current_size_bytes{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "redis_aof_last_cow_size_bytes{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Enabled",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 19, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_aof_enabled{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Delayed fsyncs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_aof_delayed_fsync{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Appendfsync",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 19, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_config_key_value{key=\"appendfsync\"} and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Last rewrite duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_aof_last_rewrite_duration_sec{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Loading Dump",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 19, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_loading_dump_file{node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Last COW size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_aof_last_cow_size_bytes{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Async Loading",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 19, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_async_loading{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Last rewrite success",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_aof_last_write_status{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Master RDB persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last bgsave timestamp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_rdb_last_save_timestamp_seconds{node_name=~\"$node_name\"} * 1000 and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Last bgsave success",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_rdb_last_bgsave_status{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Changes since lastsave",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_rdb_changes_since_last_save{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Save config",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 51 },
     "targets": [
      {
       "expr": "redis_config_key_value{key=\"save\", node_name=~\"$node_name\"} and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "RDB saves",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_rdb_saves_total{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    },
    {
     "title": "Last COW size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_rdb_last_cow_size_bytes{node_name=~\"$node_name\"}and on(node_name) redis_instance_info{role=\"master\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - command percentiles",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 52 },
     "repeat": "node_name",
     "targets": [
      {
       "expr": "redis_latency_percentiles_usec{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "get latency",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"get\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "set latency",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 73 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"set\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "hset latency",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 73 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"hset\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpop latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"rpop\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "lpop latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"lpop\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "lrange latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"lrange\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpush latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"rpush\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "lpush latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"lpush\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "hset latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"hset\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "psync latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{node_name=~\"$node_name\", cmd=\"psync\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Slowlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowlog length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_slowlog_length{node_name=~\"$node_name\"}"
      },
      { "expr": "redis_slowlog_last_id", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Slowlog",
     "type": "barchart",
     "gridPos": { "h": 16, "w": 17, "x": 0, "y": 61 },
     "targets": [
      { "command": "slowlogGet", "size": 10, "type": "command" }
     ]
    },
    {
     "title": "Slowlog slower than (ms)",
     "type": "table",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_config_value{key=\"slowlog-log-slower-than\", node_name=~\"$node_name\"} / 1000"
      }
     ]
    },
    {
     "title": "Slowlog maxlength",
     "type": "table",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_config_value{key=\"slowlog-max-len\", node_name=~\"$node_name\"}"
      }
     ]
    }
   ]
  }
 ]
}