{
 "title": "Valkey/Redis Cluster Detail",
 "description": "Valkey Cluster Detail Dashboard",
 "tags": [
  "Valkey",
  "Redis",
  "Percona"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up,service_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{cluster=~\"$cluster\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "slots status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min(redis_cluster_slots_ok{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(redis_cluster_slots_fail{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(redis_cluster_slots_pfail{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$node_name - cluster state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "min(redis_cluster_state{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "redis_cluster_messages_sent_total{node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_cluster_messages_received_total{node_name=~\"$node_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$node_name - cluster connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(node_name) (redis_cluster_connections{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$node_name - known nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "redis_cluster_known_nodes{node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replication Roles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "panels": [
    {
     "title": "$node_name",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "repeat": "node_name",
     "targets": [
      {
       "expr": "redis_instance_info{node_name=~\"$node_name\"}",
       "legendFormat": "{{node_name}}_role"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - Replica vs Master offsets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "repeat": "node_name",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_master_repl_offset{node_name=~\"$node_name\"} - on(node_name) redis_connected_slave_offset_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(redis_connected_slaves{node_name=~\"$node_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connected Replicas",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_connected_slaves{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Partial resyncs",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_replica_partial_resync_accepted{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Full resyncs",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_replica_resyncs_full{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backlog Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_replication_backlog_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backlog History Bytes",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_repl_backlog_history_bytes{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backlog first byte offset",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_repl_backlog_first_byte_offset{node_name=~\"$node_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replica Resync Info",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "redis_replica_resyncs_full{node_name=~\"$node_name\"}",
       "legendFormat": "{{node_name}}_full_resyncs"
      },
      {
       "expr": "redis_replica_partial_resync_accepted{node_name=~\"$node_name\"}",
       "legendFormat": "{{node_name}}_partial_resyncs"
      },
      {
       "expr": "redis_replica_partial_resync_denied{node_name=~\"$node_name\"}",
       "legendFormat": "{{node_name}}_partial_resync_denies"
      }
     ]
    }
   ]
  }
 ]
}