{
 "title": "Valkey/Redis Slowlog",
 "description": "Valkey/Redis Slowlog Dashboard",
 "tags": [
  "Valkey",
  "Redis",
  "Percona"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up,node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up,service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Slowlog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slowlog length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_slowlog_length{node_name=~\"$node_name\"}"
    },
    { "expr": "redis_slowlog_last_id", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slowlog",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "command": "slowlogGet",
     "expr": "sum by(node_name) (redis_slowlog_length{node_name=~\"$node_name\"})",
     "legendFormat": "__auto",
     "size": 10,
     "type": "command"
    }
   ]
  },
  {
   "title": "Slowlog slower than (ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_config_value{key=\"slowlog-log-slower-than\", node_name=~\"$node_name\"} / 1000"
    }
   ]
  },
  {
   "title": "Slowlog maxlength",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_config_value{key=\"slowlog-max-len\", node_name=~\"$node_name\"}"
    }
   ]
  }
 ]
}