{
 "title": "Valkey/Redis Command Detail",
 "description": "Valkey/Redis Command Detail Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up,service_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "service_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{cluster=~\"$cluster\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Commands/sec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service_name - Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(redis_commands_total{service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Read and Write Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$service_name - Read and Write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(redis_total_reads_processed{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Reads - {{service_name}}"
    },
    {
     "expr": "sum by(service_name) (rate(redis_total_writes_processed{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Writes - {{service_name}}"
    }
   ]
  },
  { "title": "Operations/sec by command", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$service_name - command ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{service_name=~\"$service_name\"} [1m])) by (service_name,cmd)",
     "legendFormat": "{{cmd}} - {{ service_name}}"
    }
   ]
  },
  { "title": "Command Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$service_name - top 10 total time by command",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(service_name, cmd) (redis_commands_duration_seconds_total{service_name=~\"$service_name\"}) != 0)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "$service_name - total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(cmd, service_name) (irate(redis_commands_duration_seconds_total{service_name=~\"$service_name\"}[1m])) != 0",
     "legendFormat": "{{cmd}} - {{ service_name}}"
    }
   ]
  },
  {
   "title": "Commands Totals",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (redis_total_reads_processed{service_name=~\"$service_name\"})",
     "legendFormat": "reads - {{service_name}}"
    },
    {
     "expr": "sum by(service_name) (redis_total_writes_processed{service_name=~\"$service_name\"})",
     "legendFormat": "writes - {{service_name}}"
    },
    {
     "expr": "sum by (service_name)(redis_errors_total{service_name=~\"$service_name\"})",
     "legendFormat": "errors - {{service_name}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - command percentiles",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "redis_latency_percentiles_usec{service_name=~\"$service_name\",service_name=~\"$service_name\"}",
       "legendFormat": "{{cmd}} - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency by command",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - get latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"get\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - set latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"set\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - hset latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"hset\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - rpop latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"rpop\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - lpop latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"lpop\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - lrange latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"lrange\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpush latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"rpush\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "lpush latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"lpush\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - hset latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"hset\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$service_name - psync latency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
     "repeat": "service_name",
     "targets": [
      {
       "expr": "sort(redis_commands_latencies_usec_bucket{service_name=~\"$service_name\", cmd=\"psync\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}