{
 "title": "Valkey/Redis Load",
 "description": "Valkey/Redis Load Dashboard",
 "tags": [
  "Valkey",
  "Redis",
  "Load"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up,service_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{cluster=~\"$cluster\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Commands/sec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$node_name - Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node_name) (rate(redis_commands_total{service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Read and Write Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$service_name - Read and Write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(redis_total_reads_processed{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Reads - $service_name"
    },
    {
     "expr": "sum by(service_name) (rate(redis_total_writes_processed{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Writes - $service_name"
    }
   ]
  },
  { "title": "Operations/sec by command", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$node_name - command ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{service_name=~\"$service_name\"} [1m])) by (service_name,cmd)",
     "legendFormat": "{{cmd}} - {{service_name}}"
    }
   ]
  },
  { "title": "Hits and Misses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "$node_name - Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{service_name=~\"$service_name\"}[5m])",
     "legendFormat": "hits - {{ service_name}}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{node_name=~\"$service_name\"}[5m])",
     "legendFormat": "misses - {{ service_name}}"
    }
   ]
  },
  { "title": "IO Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "IO thread R/W per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_io_threaded_reads_processed{service_name=~\"$service_name\"}[5m])",
     "legendFormat": "reads - {{service_name}}"
    },
    {
     "expr": "irate(redis_io_threaded_writes_processed{service_name=~\"$service_name\"}[5m])",
     "legendFormat": "writes - {{service_name}}"
    }
   ]
  },
  {
   "title": "IO threads configured",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_config_io_threads{service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "IO threads active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_io_threads_active{service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}