{
 "title": "Valkey/Redis Replication",
 "description": "Valkey/Redis Replication details",
 "tags": [
  "Valkey",
  "Redis",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"redis_up\"},environment)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(redis_up,service_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(redis_up{cluster=~\"$cluster\", environment=~\"$environment\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replication Roles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service_name",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "targets": [
    {
     "expr": "redis_instance_info{service_name=~\"$service_name\", node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}_role"
    }
   ]
  },
  { "title": "Replication Offsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$node_name - Replica vs Master offsets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_master_repl_offset{node_name=~\"$node_name\", service_name=~\"$service_name\"}\r\n- on(node_name, service_name) group_left(slave_ip, slave_port)\r\nredis_connected_slave_offset_bytes{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}_{{slave_ip}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{node_name=~\"$node_name\", service_name=~\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Replicas",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_slaves{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full resyncs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_replica_resyncs_full{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backlog Size",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_replication_backlog_bytes{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backlog first byte offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_first_byte_offset{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partial resyncs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_replica_partial_resync_accepted{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backlog History Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_history_bytes{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Resync Info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "redis_replica_resyncs_full{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}_full_resyncs"
    },
    {
     "expr": "redis_replica_partial_resync_accepted{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}_partial_resyncs"
    },
    {
     "expr": "redis_replica_partial_resync_denied{node_name=~\"$node_name\", service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}_partial_resync_denies"
    }
   ]
  }
 ]
}