{
 "title": "Clickhouse",
 "description": "Clickhouse metrics",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "pmmhost", "query": "pmm-server" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$pmmhost</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "DB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(clickhouse_uptime[$interval]) or max_over_time(clickhouse_uptime[5m]) "
    }
   ]
  },
  {
   "title": "RW Lock Readers Wait",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_over_time(clickhouse_rw_lock_readers_wait_milliseconds_total[$interval]) or max_over_time(clickhouse_rw_lock_readers_wait_milliseconds_total[5m])"
    }
   ]
  },
  {
   "title": "Disk Space Reserved for Merge",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(clickhouse_disk_space_reserved_for_merge[$interval]) or max_over_time(clickhouse_disk_space_reserved_for_merge[5m])"
    }
   ]
  },
  {
   "title": "Data Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(clickhouse_read[$interval]) or max_over_time(clickhouse_read[5m]) ",
     "legendFormat": "Read"
    },
    {
     "expr": "max_over_time(clickhouse_write[$interval]) or max_over_time(clickhouse_write[5m])",
     "legendFormat": "Write"
    },
    {
     "expr": "max_over_time(clickhouse_merge[$interval]) or max_over_time(clickhouse_merge[5m])",
     "legendFormat": "Merge"
    },
    {
     "expr": "max_over_time(clickhouse_background_pool_task[$interval]) or max_over_time(clickhouse_background_pool_task[5m])",
     "legendFormat": "Background Pool"
    },
    {
     "expr": "max_over_time(clickhouse_revision[$interval]) or max_over_time(clickhouse_revision[5m])",
     "legendFormat": "Revision"
    },
    {
     "expr": "rate(clickhouse_seek_total[$interval]) or irate(clickhouse_seek_total[5m])",
     "legendFormat": "Seek"
    },
    {
     "expr": "max_over_time(clickhouse_delayed_inserts[$interval]) or max_over_time(clickhouse_delayed_inserts[5m])",
     "legendFormat": "Delayed Inserts"
    }
   ]
  },
  {
   "title": "Clickhouse Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query_total[$interval]) or rate(clickhouse_query_total[5m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Mark Cache",
   "type": "graph",
   "description": "Mark cache - Cache of 'marks' for StorageMergeTree. Marks is an index structure that addresses ranges in column file, corresponding to ranges of primary key",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_mark_cache_misses_total[$interval]) or irate(clickhouse_mark_cache_misses_total[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(clickhouse_mark_cache_hits_total[$interval]) or irate(clickhouse_mark_cache_hits_total[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(clickhouse_mark_cache_bytes[$interval])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total[1m])",
     "legendFormat": "Size"
    },
    {
     "expr": "clickhouse_compressed_read_buffer_blocks_total",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(clickhouse_tcp_connection[$interval]) or max_over_time(clickhouse_tcp_connection[5m])",
     "legendFormat": "TCP"
    },
    {
     "expr": "max_over_time(clickhouse_http_connection[$interval]) or max_over_time(clickhouse_http_connection[5m])",
     "legendFormat": "HTTP"
    },
    {
     "expr": "clickhouse_interserver_connection",
     "legendFormat": "Interserver"
    }
   ]
  },
  {
   "title": "Memory Tracking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(clickhouse_memory_tracking[$interval]) or max_over_time(clickhouse_memory_tracking[5m])",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "File Opens",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_file_open_total[$interval]) or irate(clickhouse_file_open_total[5m])",
     "legendFormat": "Operations"
    }
   ]
  }
 ]
}