{
 "title": "Disk Details",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values({__name__=~\"node_disk_reads_completed_total|aws_rds_disk_queue_depth_average|rdsosmetrics_diskIO_readLatency\"}, node_name)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values({__name__=~\"node_disk_reads_completed_total|rdsosmetrics_diskIO_util\",node_name=~\"$node_name\", device!~\"dm-.+\"}, device)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Mountpoint Usage",
   "type": "graph",
   "description": "Shows the percentage of disk space utilization for every mountpoint defined on the system. Having some of the mountpoints close to 100% space utilization is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case when the mountpoint is close to 100% consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name,mountpoint) (1 - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) / \n(max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or\nmax_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Shows information about the disk space usage of the specified mountpoint.\n\n**Used** is the amount of space used.\n\n**Free** is the amount of space not in use.\n\n**Used+Free** is the total disk space allocated to the mountpoint.\n\nHaving *Free* close to 0 B is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case Free is close to 0 B consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name,mountpoint) ((max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name,mountpoint) (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", mountpoint=\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", mountpoint=\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]))",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name,mountpoint) (1 - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) / (max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) \nor max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Shows information about the disk space usage of the specified mountpoint.\n\n**Used** is the amount of space used.\n\n**Free** is the amount of space not in use.\n\n**Used+Free** is the total disk space allocated to the mountpoint.\n\nHaving *Free* close to 0 B is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case Free is close to 0 B consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name,mountpoint) ((max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name,mountpoint) (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", mountpoint=\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", mountpoint=\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]))",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name,mountpoint) (1 - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) / (max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) \nor max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "Total Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or\navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[5m])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[5m])/1000 or vector(0)\n)",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or \n(avg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[5m])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[5m])/1000)\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=\"$node_name\"}[5m])) \n))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) or \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=\"$node_name\"}[5m]) \n))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_written_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[5m]) or\nrate(node_disk_written_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[5m]) or\nrate(node_disk_read_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\nrate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])\n)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name) (rate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\n(max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[5m]))/100)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Avg Disks Operations Merge Ratio",
   "type": "graph",
   "description": "Shows how effectively Operating System is able to merge logical IO requests into physical requests.  This is a good measure of the IO locality which can be used for workload characterization.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg(\n(1 + rate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0\n)",
     "legendFormat": "Read Ratio"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg(\n(1 + rate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0\n)",
     "legendFormat": "Write Ratio"
    }
   ]
  },
  {
   "title": "Disk IO Size",
   "type": "graph",
   "description": "Shows average size of a single disk operation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or \n(irate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / \nirate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
     "legendFormat": "Read size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or \n(irate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / \nirate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
     "legendFormat": "Write size"
    }
   ]
  },
  {
   "title": "Device $device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "repeat": "device",
   "collapsed": true,
   "panels": [
    {
     "title": "$device - Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or\navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[5m])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[5m])/1000)",
       "legendFormat": "Read: {{device}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or \n(avg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[5m])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[5m])/1000))",
       "legendFormat": "Write: {{device}}"
      }
     ]
    },
    {
     "title": "$device - Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=\"$node_name\"}[5m]))) ",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=\"$node_name\"}[5m]))) ",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_read_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_read_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{device=~\"$device\",node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_written_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_written_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{device=~\"$device\",node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk IO Utilization",
     "type": "graph",
     "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\n(max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[5m]))/100)",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk Operations Merge Ratio",
     "type": "graph",
     "description": "Shows how effectively Operating System is able to merge logical IO requests into physical requests.  This is a good measure of the IO locality which can be used for workload characterization.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(1 + rate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 \n)",
       "legendFormat": "Read Ratio: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(1 + rate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0\n)",
       "legendFormat": "Write Ratio: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk IO Size",
     "type": "graph",
     "description": "Shows average size of a single disk operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(rate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / rate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or (irate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / irate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
       "legendFormat": "Read size: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(rate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / rate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or (irate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / irate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
       "legendFormat": "Write size: {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}