{
 "title": "Environment Overview",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(node_load1, region)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values(node_load1{region=~\"$region\"}, node_type)"
   },
   {
    "name": "host",
    "label": "Hosts",
    "query": "label_values(node_load1{region=~\"$region\",node_type=~\"$node_type\"}, node_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_boot_time_seconds{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\",region=~\"$region\",node_type=~\"$node_type\"}) or \n(1-absent(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\",region=~\"$region\",node_type=~\"$node_type\"}))) + \nsum(rdsosmetrics_General_numVCPUs{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"} or up * 0)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by () (avg_over_time(node_load1{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}[$interval]) or \navg_over_time(node_load1{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}[5m]))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Mem Avail",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by () ((node_memory_MemAvailable_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"} or \n(node_memory_MemFree_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"} + node_memory_Buffers_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"} + \nnode_memory_Cached_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}) * 100,100)"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}+node_memory_SwapTotal_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by () (sum(avg(node_filesystem_size_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",fstype=~\"(ext.|xfs|vfat)\"}) without (mountpoint)) without (device,fstype))"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max((min(node_filesystem_free_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/\nnode_filesystem_size_bytes{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100),100)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top 5 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5,(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",\nnode_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"total\"}[5m]))))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by () (sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",\nnode_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"steal\",mode!=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"total\"}[5m])))",
     "legendFormat": "Average by All Hosts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "clamp_max(sum by (node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[5m])) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"total\"}[5m])),100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU Steal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5,(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m]))))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by () (sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m])))",
     "legendFormat": "Average by All Hosts"
    }
   ]
  },
  {
   "title": "CPU Steal",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "clamp_max(sum by (node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"steal\"}[5m])) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"steal\"}[5m])),100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU I/O Wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5,(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m]))))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by () (sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",\nnode_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m]),1)) ) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m])))",
     "legendFormat": "Average by All Hosts"
    }
   ]
  },
  {
   "title": "CPU I/O Wait",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "clamp_max(sum by (node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\",mode=\"iowait\"}[5m])) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\", mode=\"iowait\"}[5m])),100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "topk(5,(avg_over_time(node_procs_running{node_name=~\"$host\"}[$interval])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$host\"}[5m])-1) / \nscalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg((avg_over_time(node_procs_running{node_name=~\"$host\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$host\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})))",
     "legendFormat": "Average of All Hosts"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "(avg_over_time(node_procs_running{node_name=~\"$host\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})) or \n(avg_over_time(node_procs_running{node_name=~\"$host\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5,rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$host\"}[5m]))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by () (rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or \nirate(node_context_switches_total{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Average by All Hosts"
    }
   ]
  },
  {
   "title": "Switches",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Runnable Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(topk(5,(max_over_time(node_procs_running{node_name=~\"$host\"}[$interval]) - 1) or \n(max_over_time(node_procs_running{node_name=~\"$host\"}[5m]) -1)))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by () (sum by (node_name) (max_over_time(node_procs_running{node_name=~\"$host\"}[$interval]) - 1) or \n(max_over_time(node_procs_running{node_name=~\"$host\"}[5m]) -1))",
     "legendFormat": "Average by All Hosts"
    }
   ]
  },
  {
   "title": "Runnable Processes",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "(max_over_time(node_procs_running{node_name=~\"$host\"}[$interval]) - 1) or \n(max_over_time(node_procs_running{node_name=~\"$host\"}[5m]) -1)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Blocked Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,(max_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$host\"}[5m])))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by () (max_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Average by All Hosts"
    }
   ]
  },
  {
   "title": "Blocked Processes",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "(max_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$host\"}[5m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Memory Percent",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[5m])) * 100 /\n(max_over_time(node_memory_MemTotal_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_MemTotal_bytes{node_name=~\"$host\"}[$interval]))),100)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Available Virtual Memory Percent",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "clamp_max(((node_memory_MemAvailable_bytes{node_name=~\"$host\"} or \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$host\"} * 100) / \n(node_memory_MemTotal_bytes{node_name=~\"$host\"} + node_memory_SwapTotal_bytes{node_name=~\"$host\"}),100)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Free Swap Space Percent",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[$interval]) or \nmax_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[5m])) * 100) / \n(max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[$interval]) or \nmax_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[5m])),100)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Used Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(node_memory_MemTotal_bytes{node_name=~\"$host\"} - \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (node_memory_MemTotal_bytes{node_name=~\"$host\"} - \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + \nnode_memory_Buffers_bytes{node_name=~\"$host\"} + \nnode_memory_Cached_bytes{node_name=~\"$host\"}))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Free Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Used Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,(node_memory_MemTotal_bytes{node_name=~\"$host\"} + node_memory_SwapTotal_bytes{node_name=~\"$host\"} - \n((node_memory_MemAvailable_bytes{node_name=~\"$host\"} or \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$host\"})))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (node_memory_MemTotal_bytes{node_name=~\"$host\"} + node_memory_SwapTotal_bytes{node_name=~\"$host\"} - \n((node_memory_MemAvailable_bytes{node_name=~\"$host\"} or \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$host\"}))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Available Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,((node_memory_MemAvailable_bytes{node_name=~\"$host\"} or \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$host\"}))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() ((node_memory_MemAvailable_bytes{node_name=~\"$host\"} or \n(node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) + \nnode_memory_SwapFree_bytes{node_name=~\"$host\"})",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Used Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(node_memory_SwapTotal_bytes{node_name=~\"$host\"} - node_memory_SwapFree_bytes{node_name=~\"$host\"}))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (node_memory_SwapTotal_bytes{node_name=~\"$host\"} - node_memory_SwapFree_bytes{node_name=~\"$host\"})",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Free Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(node_memory_SwapFree_bytes{node_name=~\"$host\"}))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by()(node_memory_SwapFree_bytes{node_name=~\"$host\"})",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Swap In (Reads)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(rate(node_vmstat_pswpin{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$host\"}[5m]) * 4096))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (rate(node_vmstat_pswpin{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$host\"}[5m]) * 4096)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Top 5 Swap Out (Writes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(rate(node_vmstat_pswpout{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$host\"}[5m]) * 4096))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by () (rate(node_vmstat_pswpout{node_name=~\"$host\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{node_name=~\"$host\"}[5m]) * 4096)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Disk I/O Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,\n(sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m]))) + \n(sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m])) + \n(sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m]))))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Disk I/O Load",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m])) + \nsum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m]))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5,(\nsum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) > 0  or \n(rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) /\nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) > 0 or \n(rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) /\nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[5m])/1000))\n))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) > 0  or \n(rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) /\nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) > 0 or \n(rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) /\nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[5m])/1000)))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": " Disk Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum by (node_name) ((rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) > 0  or \n(rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) /\nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) > bool 0) +\nsum by (node_name) ((rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) > 0 or \n(rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) /\nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) > bool 0) or\n((avg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[5m])/1000) + \n(avg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[5m])/1000))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Disk Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$host\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$host\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$host\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$host\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$host\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$host\"}[5m])))\n))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$host\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$host\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$host\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$host\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$host\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$host\"}[5m])))\n)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": " Disk Bandwidth",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "(sum by (node_name) ((rate(node_disk_read_bytes_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$host\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$host\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{node_name=~\"$host\"}[5m])) +\nrate(node_disk_written_bytes_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$host\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$host\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{node_name=~\"$host\"}[5m])))\n)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 I/O Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,((rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024)\n))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() ((rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024)\n)",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "I/O Activity",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "(rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024)",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m])) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m])))\n))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m])) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "(sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m])) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Local Network Errors",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$host\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$host\", device!=\"lo\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$host\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$host\", device!=\"lo\"}[5m])))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "(sum by (node_name) (rate(node_network_receive_errs_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_errs_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum by (node_name) (irate(node_network_receive_errs_total{node_name=~\"$host\", device!=\"lo\"}[5m]) + irate(node_network_transmit_errs_total{node_name=~\"$host\", device!=\"lo\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk(5,(rate(node_netstat_Tcp_RetransSegs{node_name=~\"$host\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$host\"}[5m])))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (rate(node_netstat_Tcp_RetransSegs{node_name=~\"$host\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$host\"}[5m]))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Retransmission",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "(rate(node_netstat_Tcp_RetransSegs{node_name=~\"$host\"}[$interval]) or \nirate(node_netstat_Tcp_RetransSegs{node_name=~\"$host\"}[5m]))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Local Network Drop",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (node_name) (rate(node_network_receive_drop_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) + \nrate(node_network_transmit_drop_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or\nsum by (node_name) (irate(node_network_receive_drop_total{node_name=~\"$host\", device!=\"lo\"}[5m]) + \nirate(node_network_transmit_drop_total{node_name=~\"$host\", device!=\"lo\"}[5m]))))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg by() (sum by (node_name) (rate(node_network_receive_drop_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) + \nrate(node_network_transmit_drop_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or\nsum by (node_name) (irate(node_network_receive_drop_total{node_name=~\"$host\", device!=\"lo\"}[5m]) + \nirate(node_network_transmit_drop_total{node_name=~\"$host\", device!=\"lo\"}[5m])))",
       "legendFormat": "Average by All Hosts"
      }
     ]
    },
    {
     "title": "Drop",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "targets": [
      {
       "expr": "(sum by (node_name) (rate(node_network_receive_drop_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) + \nrate(node_network_transmit_drop_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or\nsum by (node_name) (irate(node_network_receive_drop_total{node_name=~\"$host\", device!=\"lo\"}[5m]) + \nirate(node_network_transmit_drop_total{node_name=~\"$host\", device!=\"lo\"}[5m])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Environment Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Regions",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "count(node_boot_time_seconds{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}) by (region)"
      }
     ]
    },
    {
     "title": "Types",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 64 },
     "targets": [
      {
       "expr": "count(node_boot_time_seconds{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}) by (node_type)"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 64 },
     "targets": [
      {
       "expr": "node_time_seconds{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"} - node_boot_time_seconds{node_name=~\"$host\",region=~\"$region\",node_type=~\"$node_type\"}"
      }
     ]
    }
   ]
  }
 ]
}