{
 "title": "MongoDB MMAPv1",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",engine=\"mmapv1\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",node_name=~\"$host\",engine=\"mmapv1\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "MMAPv1 Lock Wait Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(increase(mongodb_mongod_locks_time_acquiring_global_microseconds_total{service_name=~\"$service\",database=\"Database\"}[$interval])) by (instance) / (increase(mongodb_mongod_instance_uptime_seconds{service_name=~\"$service\"}[$interval])*1000000)) or mongodb_mongod_global_lock_ratio{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "MMAPv1 Write Lock Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{service_name=~\"$service\",database=\"Global\",type=\"write\"}[$interval]) or irate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{service_name=~\"$service\",database=\"Global\",type=\"write\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{node_name=~\"$host\"} or (node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "Document Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "ttl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    }
   ]
  },
  {
   "title": "MMAPv1 Lock Ratios",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(mongodb_mongod_locks_time_locked_global_microseconds_total{service_name=~\"$service\",database=\"Database\"}[$interval])) by (instance) / (increase(mongodb_mongod_instance_uptime_seconds{service_name=~\"$service\"}[$interval])*1000000)) or mongodb_mongod_global_lock_ratio{service_name=~\"$service\"}",
     "legendFormat": "Lock (pre-3.2 only)"
    },
    {
     "expr": "(sum(increase(mongodb_mongod_locks_time_acquiring_global_microseconds_total{service_name=~\"$service\",database=\"Database\"}[$interval])) by (instance) / (increase(mongodb_mongod_instance_uptime_seconds{service_name=~\"$service\"}[$interval])*1000000)) or mongodb_mongod_global_lock_ratio{service_name=~\"$service\"}",
     "legendFormat": "Lock Wait"
    }
   ]
  },
  {
   "title": "MMAPv1 Lock Wait Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{service_name=~\"$service\",database=~\"(Global|Database|MMAPV1Journal)\"}[$interval]) or irate(mongodb_mongod_locks_time_acquiring_global_microseconds_total{service_name=~\"$service\",database=~\"(Global|Database|MMAPV1Journal)\"}[5m])",
     "legendFormat": "{{database}} {{type}}"
    }
   ]
  },
  {
   "title": "MMAPv1 Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "MMAPv1 Journal Write Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_durability_journaled_megabytes{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_durability_journaled_megabytes{service_name=~\"$service\"}[5m])",
     "legendFormat": "Journaled"
    },
    {
     "expr": "rate(mongodb_mongod_durability_write_to_data_files_megabytes{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_durability_write_to_data_files_megabytes{service_name=~\"$service\"}[5m])",
     "legendFormat": "Write to Data Files"
    }
   ]
  },
  {
   "title": "MMAPv1 Journal Commit Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_durability_commits{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_durability_commits{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "MMAPv1 Journaling Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_durability_time_milliseconds_sum{service_name=~\"$service\",stage!=\"dt\"}[$interval]) or irate(mongodb_mongod_durability_time_milliseconds_sum{service_name=~\"$service\",stage!=\"dt\"}[5m])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "MMAPv1 Journaling Time - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_durability_time_milliseconds{service_name=~\"$service\",quantile=\"0.99\",stage!=\"dt\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "MMAPv1 Background Flushing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_background_flushing_average_milliseconds{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_background_flushing_average_milliseconds{service_name=~\"$service\"}[5m])",
     "legendFormat": "Background Flushing"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Client Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "MMAPv1 Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{service_name=~\"$service\"}-node_memory_Mapped_bytes{service_name=~\"$service\"}",
     "legendFormat": "Unmapped"
    },
    {
     "expr": "node_memory_Mapped_bytes{service_name=~\"$service\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_SwapCached_bytes{service_name=~\"$service\"}",
     "legendFormat": "Swap Cached"
    }
   ]
  },
  {
   "title": "MMAPv1 Memory Dirty Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_vmstat_nr_dirty{service_name=~\"$service\"}",
     "legendFormat": "Total Dirty Pages"
    },
    {
     "expr": "node_vmstat_nr_dirty_background_threshold{service_name=~\"$service\"}",
     "legendFormat": "Soft Dirty Page Threshold"
    },
    {
     "expr": "node_vmstat_nr_dirty_threshold{service_name=~\"$service\"}",
     "legendFormat": "Hard Dirty Page Threshold"
    }
   ]
  }
 ]
}