{
 "title": "MongoDB Services Compare",
 "tags": [
  "MongoDB_Compare",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(mongodb_up{node_name=~\"$host\"}, region)"
   },
   {
    "name": "host",
    "label": "Node Name",
    "query": "label_values(mongodb_up, node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(mysql_up{node_name=~\"$host\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mysql_up{node_name=~\"$host\"}, cluster)"
   },
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(mongodb_up{node_name=~\"$host\"}, service_name)"
   },
   {
    "name": "node_id",
    "label": "Node_ID",
    "query": "label_values(mysql_up{node_name=\"$host\"}, node_id)"
   },
   {
    "name": "agent_id",
    "label": "Agent_ID",
    "query": "label_values(mysql_up{node_name=\"$host\"}, instance)"
   },
   {
    "name": "service_id",
    "label": "Service_ID",
    "query": "label_values(mysql_up{service_name=~\"$service\"}, service_id)"
   },
   {
    "name": "az",
    "label": "Az",
    "query": "label_values(mysql_up{node_name=\"$host\"}, az)"
   },
   {
    "name": "node_type",
    "label": "Node_type",
    "query": "label_values(mysql_up{node_name=\"$host\"}, node_type)"
   },
   {
    "name": "node_model",
    "label": "Node_model",
    "query": "label_values(mysql_up{node_name=\"$host\"}, node_model)"
   },
   {
    "name": "replication_set",
    "label": "Replication_Set",
    "query": "label_values(mysql_up{service_name=~\"$service\"}, replication_set)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "$service - Service Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "repeat": "service",
   "targets": [
    {
     "expr": "mongodb_version_info{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Service Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "mongodb_version_info{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - MySQL Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "repeat": "service",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mongodb_instance_uptime_seconds{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - MySQL Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mongodb_instance_uptime_seconds{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Current QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "repeat": "service",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service - Current QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service - DB Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{service_name=~\"$service\",state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service\",state=\"current\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service - DB Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{service_name=~\"$service\",state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service\",state=\"current\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service - Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 12 },
   "repeat": "service",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[$interval]) / rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[$interval]) or irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[5m]) / irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[$interval]) / rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[$interval]) or irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[5m]) / irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Opened Cursors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
   "repeat": "service",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\"} or mongodb_mongod_cursors{service_name=~\"$service\"} or mongodb_mongos_metrics_cursor_open{service_name=~\"$service\"} or mongodb_mongos_cursors{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "$service - Opened Cursors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\"} or mongodb_mongod_cursors{service_name=~\"$service\"} or mongodb_mongos_metrics_cursor_open{service_name=~\"$service\"} or mongodb_mongos_cursors{service_name=~\"$service\"})"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$service - Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=~\"current|available\"}[5m]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=~\"current|available\"}[5m]) or \nmax_over_time(mongodb_connections{service_name=~\"$service\", state=~\"current|available\"}[$interval]) or \nmax_over_time(mongodb_connections{service_name=~\"$service\", state=~\"current|available\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service - Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=~\"current|available\"}[5m]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=~\"current|available\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=~\"current|available\"}[5m]) or \nmax_over_time(mongodb_connections{service_name=~\"$service\", state=~\"current|available\"}[$interval]) or \nmax_over_time(mongodb_connections{service_name=~\"$service\", state=~\"current|available\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$service - Cursors ",
   "type": "graph",
   "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mongodb_mongod_metrics_cursor_open{service_name=\"$service\"} or \nmongodb_mongod_cursors{service_name=\"$service\"} or \nmongodb_mongos_metrics_cursor_open{service_name=\"$service\"} or \nmongodb_mongos_cursors{service_name=\"$service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service - Cursors ",
   "type": "graph",
   "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mongodb_mongod_metrics_cursor_open{service_name=\"$service\"} or \nmongodb_mongod_cursors{service_name=\"$service\"} or \nmongodb_mongos_metrics_cursor_open{service_name=\"$service\"} or \nmongodb_mongos_cursors{service_name=\"$service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Query Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$service - Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "repeat": "service",
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\"}[$interval]) / rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service - Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\"}[$interval]) / rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service - Scan Ratios",
   "type": "graph",
   "description": "This panel shows how efficient the queries running against this instance are. If the *INDEX* counter is low while queries are running it means you could be missing indexes that would support your queries. If the *DOCUMENT* counter is high it means that there are a lot of documents being returned per query and you might need to check to make sure your queries are returning only the data they need to.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval]) or (irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) irate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval]) / ignoring(state)rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval]) or\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]) / ignoring(state)irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m])",
     "legendFormat": "Document"
    }
   ]
  },
  {
   "title": "$service - Scan Ratios",
   "type": "graph",
   "description": "This panel shows how efficient the queries running against this instance are. If the *INDEX* counter is low while queries are running it means you could be missing indexes that would support your queries. If the *DOCUMENT* counter is high it means that there are a lot of documents being returned per query and you might need to check to make sure your queries are returning only the data they need to.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval]) or (irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) irate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval]) / ignoring(state)rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval]) or\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]) / ignoring(state)irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m])",
     "legendFormat": "Document"
    }
   ]
  },
  {
   "title": "$service - Index Filtering Effectiveness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "repeat": "service",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects\"}) / ignoring(state)sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects|scanned\"})",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "$service - Index Filtering Effectiveness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects\"}) / ignoring(state)sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects|scanned\"})",
     "legendFormat": "Index"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "$service - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_op_counters_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_op_counters_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service - Document Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[5m])\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service - Document Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[5m])\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service -  Queued Operations",
   "type": "graph",
   "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}[$interval]) or max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service -  Queued Operations",
   "type": "graph",
   "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}[$interval]) or max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "$service - Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "repeat": "service",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(mongodb_memory{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mongodb_memory{service_name=~\"$service\"}[5m]) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service - Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(mongodb_memory{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mongodb_memory{service_name=~\"$service\"}[5m]) ",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}