{
 "title": "MongoDB RocksDB Details",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up,cluster)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mongodb_mongod_storage_engine{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",engine=\"rocksdb\"}, service_name)"
   },
   {
    "name": "level",
    "label": "RocksDB Level",
    "query": "label_values(mongodb_mongod_rocksdb_files{cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\",level!=\"total\"}, level)"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, service_name)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mongodb_up{node_name=\"$node_name\"},node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "RocksDB Memtable Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_rocksdb_memtable_bytes{service_name=~\"$service_name\", type=\"total\"}/67108864)"
    }
   ]
  },
  {
   "title": "RocksDB Block Cache Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_rocksdb_block_cache_bytes{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (node_name) (node_memory_Cached_bytes{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Document Activity",
   "type": "graph",
   "description": "Mixed metrics: Docs per second inserted, updated, deleted or returned on any type of node (primary or secondary); + replicated write Ops/sec; + TTL deletes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "ttl_deleted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"delete\"}[5m]))",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"insert\"}[5m]))",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type=\"update\"}[5m]))",
     "legendFormat": "repl_updated"
    }
   ]
  },
  {
   "title": "RocksDB Cache Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_rocksdb_memtable_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_memtable_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "memtable_{{type}}"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_rocksdb_block_cache_bytes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_block_cache_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "block_cache_total"
    }
   ]
  },
  {
   "title": "RocksDB Memtable Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_rocksdb_memtable_entries{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_memtable_entries{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Block Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_rocksdb_block_cache_hits_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_rocksdb_block_cache_hits_total{service_name=~\"$service_name\"}[5m])/(rate(mongodb_mongod_rocksdb_block_cache_misses_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_rocksdb_block_cache_misses_total{service_name=~\"$service_name\"}[5m])) > 0 )",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "RocksDB Write Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes / Sec" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_rocksdb_bytes_written_total{service_name=~\"$service_name\",type!=\"total\"}[$interval]) or irate(mongodb_mongod_rocksdb_bytes_written_total{service_name=~\"$service_name\",type!=\"total\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Read Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes / Sec" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_rocksdb_bytes_read_total{service_name=~\"$service_name\",type!=\"total\"}[$interval]) or irate(mongodb_mongod_rocksdb_bytes_read_total{service_name=~\"$service_name\",type!=\"total\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Level0 Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (max_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=\"L0\",type=~\"(avg|min|max|P99)\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=\"L0\",type=~\"(avg|min|max|P99)\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB LevelN Read Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=~\"$level\",level!=\"L0\",type=\"avg\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=~\"$level\",level!=\"L0\",type=\"avg\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB LevelN 99th Percentile Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=~\"$level\",level!=\"L0\",type=\"P99\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=~\"$level\",level!=\"L0\",type=\"P99\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB LevelN Maximum Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=~\"$level\",level!=\"L0\",type=~\"(max)\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_read_latency_microseconds{service_name=~\"$service_name\",level=~\"$level\",level!=\"L0\",type=~\"(max)\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (rate(mongodb_mongod_rocksdb_compaction_seconds_total{service_name=~\"$service_name\", level=~\"$level\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_seconds_total{service_name=~\"$service_name\", level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Write Amplification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_compaction_write_amplification{service_name=~\"$service_name\",level=~\"$level\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_compaction_write_amplification{service_name=~\"$service_name\",level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Read Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (rate(mongodb_mongod_rocksdb_compaction_bytes_per_second{service_name=~\"$service_name\", level=~\"$level\", type=~\"read.*\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_bytes_per_second{service_name=~\"$service_name\", level=~\"$level\", type=~\"read.*\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "New row",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_size_bytes{service_name=~\"$service_name\", level=~\"$level\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_size_bytes{service_name=~\"$service_name\", level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Key Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (rate(mongodb_mongod_rocksdb_compactions_total{service_name=~\"$service_name\", level=~\"$level\"}[$interval]) or irate(mongodb_mongod_rocksdb_compactions_total{service_name=~\"$service_name\", level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (rate(mongodb_mongod_rocksdb_compaction_bytes_per_second{service_name=~\"$service_name\", level=~\"$level\", type=~\"write.*\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_bytes_per_second{service_name=~\"$service_name\", level=~\"$level\", type=~\"write.*\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Level Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_files{service_name=~\"$service_name\", level=~\"$level\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_files{service_name=~\"$service_name\", level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level) (max_over_time(mongodb_mongod_rocksdb_compaction_file_threads{service_name=~\"$service_name\", level=~\"$level\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_compaction_file_threads{service_name=~\"$service_name\", level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Write Ahead Log Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_rocksdb_write_ahead_log_bytes_per_second{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_write_ahead_log_bytes_per_second{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Write Rate"
    }
   ]
  },
  {
   "title": "RocksDB Write Ahead Log Sync Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_rocksdb_write_ahead_log_writes_per_sync{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_write_ahead_log_writes_per_sync{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Writes per Sync"
    }
   ]
  },
  {
   "title": "RocksDB Flush Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,level,type) (rate(mongodb_mongod_rocksdb_compaction_bytes_per_second{service_name=~\"$service_name\",level=~\"$level\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_bytes_per_second{service_name=~\"$service_name\",level=~\"$level\"}[5m]))",
     "legendFormat": "{{level}}_{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Pending Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_rocksdb_pending_compactions{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_pending_compactions{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "compactions"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_rocksdb_pending_memtable_flushes{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_rocksdb_pending_memtable_flushes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "memtable_flushes"
    }
   ]
  },
  {
   "title": "RocksDB Stall Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_rocksdb_stalled_seconds_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_rocksdb_stalled_seconds_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Time Stalled"
    }
   ]
  },
  {
   "title": "RocksDB Stalls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_mongod_rocksdb_stalls_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_rocksdb_stalls_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Client Operations",
   "type": "graph",
   "description": "Ops and Replicated Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (rate(mongodb_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[5m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (service_name,type) (rate(mongodb_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[5m]))",
     "legendFormat": "repl_{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "Operations queued due to a lock.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,type) (mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "description": "This panel shows the number of objects (both data (scanned_objects) and index (scanned)) as well as the number of documents that were moved to a new location due to the size of the document growing. Moved documents only apply to the MMAPv1 storage engine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "Unix or Window memory page faults. Not necessarily from mongodb.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "MongoDB Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 119 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (service_name) (mongodb_instance_uptime_seconds{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 119 },
     "format": "ops",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (service_name) (sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]) or rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m])))"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 119 },
     "format": "µs",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0))"
      }
     ]
    },
    {
     "title": "Service",
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 119 },
     "content": "<h5><b><font color=#e68a00><center><a href=\"/graph/d/mongodb-instance-summary/mongodb-instance-summary?var-node_name=$node_name&var-service_name=$service_name\" target=\"_blank\">$crop_service...</a></center></font></b></h5>"
    },
    {
     "title": "Connections",
     "type": "graph",
     "description": "This shows the number of active connections on the server. Keep in mind the hard limit on the maximum number of connections set by your distribution.\n\nYou can read more about the [connection numbers](https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/#number-of-connections).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or \nmax_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[5m]))",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "Cursors",
     "type": "graph",
     "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,state) (max_over_time(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"}[5m]) or\nmax_over_time(mongodb_mongod_cursors{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_cursors{service_name=~\"$service_name\"}[5m]) or\nmax_over_time(mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"}[5m]) or\nmax_over_time(mongodb_mongos_cursors{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_mongos_cursors{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "singlestat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 120 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "singlestat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 120 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "singlestat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 120 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "singlestat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 120 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100)"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "singlestat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 120 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "singlestat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 120 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "singlestat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 120 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100)"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 120 },
     "content": "<h5><b><font color=#e68a00><center><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></center></font></b></h5>",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{service_name=~\"$service_name\"} "
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}