{
 "title": "MongoDB Services Overview",
 "tags": [
  "MongoDB",
  "Percona",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up,cluster)"
   },
   {
    "name": "host",
    "label": "Node Name",
    "query": "label_values(mongodb_up{cluster=~\"$cluster\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mongodb_up{cluster=~\"$cluster\",node_name=~\"$host\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(mongodb_up{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Min MongoDB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Max MongoDB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_instance_uptime_seconds{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_memory{service_name=~\"$service\",type=~\"resident|virtual\"})"
    }
   ]
  },
  {
   "title": "Total Used Mapped Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_memory{service_name=~\"$service\",type=~\"mapped|mapped_with_journal\"})"
    }
   ]
  },
  {
   "title": "Total Current QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\",type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[5m]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"} or\nmongodb_mongos_connections{service_name=~\"$service\", state=\"current\"} or\nmongodb_connections{service_name=~\"$service\", state=\"current\"})"
    }
   ]
  },
  {
   "title": "Top Opened Cursors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\"} or\nmongodb_mongod_cursors{service_name=~\"$service\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\"} or \nmongodb_mongos_cursors{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Min QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "format": "ops",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\",type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[$interval]) or\nirate(mongodb_op_counters_total{service_name=~\"$service\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "µs",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Connections Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Connections",
     "type": "graph",
     "description": "This shows the number of active connections on the server. Keep in mind the hard limit on the maximum number of connections set by your distribution.\n\nYou can read more about the [connection numbers](https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/#number-of-connections).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service\", state=\"current\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service\", state=\"current\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service\", state=\"current\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cursors Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Total Cursors",
     "type": "graph",
     "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"total\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"total\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"total\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"total\"}))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"total\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"total\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"total\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"total\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Total Cursors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"total\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"total\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"total\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"total\"}",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Pinned Cursors ",
     "type": "graph",
     "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"pinned\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"pinned\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"pinned\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"pinned\"}))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"pinned\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"pinned\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"pinned\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"pinned\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Pinned Cursors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"pinned\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"pinned\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"pinned\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"pinned\"}",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 noTimeout Cursors",
     "type": "graph",
     "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"noTimeout\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"noTimeout\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"noTimeout\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"noTimeout\"}))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"noTimeout\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"noTimeout\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"noTimeout\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"noTimeout\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "noTimeout Cursors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_open{service_name=~\"$service\", state=\"noTimeout\"} or\nmongodb_mongod_cursors{service_name=~\"$service\", state=\"noTimeout\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service\", state=\"noTimeout\"} or \nmongodb_mongos_cursors{service_name=~\"$service\", state=\"noTimeout\"}",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Command Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[5m])\n))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[5m])\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Command Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"command\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"command\"}[5m])\n",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"read\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"read\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"read\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"read\"}[5m])\n))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"read\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"read\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"read\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"read\"}[5m])\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"read\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"read\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"read\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"read\"}[5m])\n",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"write\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"write\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"write\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"write\"}[5m])\n))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"write\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"write\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"write\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"write\"}[5m])\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"write\"}[$interval]) / \nrate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"write\"}[$interval]) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service\",type=\"write\"}[5m]) / \nirate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service\",type=\"write\"}[5m])\n",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Min Index Scanned Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "format": "ops",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Max Index Scanned Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Min  Document Scanned Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
   "format": "ops",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max  Document Scanned Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m]))"
    }
   ]
  },
  {
   "title": "Query Efficiency Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Index Scan Ratios",
     "type": "graph",
     "description": "This panel shows how efficient the queries running against this instance are. If the *INDEX* counter is low while queries are running it means you could be missing indexes that would support your queries. If the *DOCUMENT* counter is high it means that there are a lot of documents being returned per query and you might need to check to make sure your queries are returning only the data they need to.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))\n))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Index Scan Ratios",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Scan Ratios",
     "type": "graph",
     "description": "This panel shows how efficient the queries running against this instance are. If the *INDEX* counter is low while queries are running it means you could be missing indexes that would support your queries. If the *DOCUMENT* counter is high it means that there are a lot of documents being returned per query and you might need to check to make sure your queries are returning only the data they need to.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Scan Ratios",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=\"scanned_objects\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Index Filtering Effectiveness",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects\"}) / ignoring(state)\nsum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects|scanned\"})))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects\"}) / ignoring(state)\nsum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects|scanned\"}))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Index Filtering Effectiveness",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects\"}) / ignoring(state)\nsum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service\", state=~\"scanned_objects|scanned\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Top Opcounters",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type!=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type!=\"command\"}[5m])) + \nsum(rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[5m]) or\nrate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[5m]) or \nrate(mongodb_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|query|getmore)\"}[5m])) +\nsum(rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service\"}[5m]) or\nrate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top Document Operations",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top Queued Operations",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total  Assert Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "format": "ops",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_asserts_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Opcounters Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Command Operations",
     "type": "graph",
     "description": "The average rate of commands performed per second over the selected sample period",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Command Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"command\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Getmore Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Getmore Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"getmore\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Delete Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Delete Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"delete\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Insert Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Insert Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"insert\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Update Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Update Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"update\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Query Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Query Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service\", type=\"query\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Document Operations Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Document Delete Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"deleted\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"deleted\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Delete Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"deleted\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Insert Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"inserted\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"inserted\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Insert Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"inserted\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Return Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"returned\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"returned\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Return Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"returned\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Update Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"updated\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"updated\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Update Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service\",state=\"updated\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queued Operations Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Queued Read Operations",
     "type": "graph",
     "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"reader\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"reader\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Queued Read Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"reader\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Queued Write Operations",
     "type": "graph",
     "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"writer\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"writer\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Queued Write Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service\",type=\"writer\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Assert Events Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Assert Msg Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert Msg Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"msg\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"msg\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert Regular Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": " Assert Regular Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"regular\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"regular\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert Rollovers Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert Rollovers Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"rollovers\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert User Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"user\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert User Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"user\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"user\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"user\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert Msg Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert Warning Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service\",type=\"warning\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service\",type=\"warning\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}