{
 "title": "MySQL Group Replication Summary",
 "tags": [
  "Percona",
  "MySQL_HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values(mysql_perf_schema_replication_group_member_info, replication_set)"
   },
   {
    "name": "channel_name",
    "label": "Channel Name",
    "query": "label_values(mysql_perf_schema_replication_group_member_info, channel_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mysql_perf_schema_replication_group_member_info{channel_name=~\"$channel_name\"}, service_name)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mysql_up{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "version",
    "query": "query_result(mysql_version_info{service_name=~\"$service_name\"})"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mysql_up{service_name=~\"$service_name\"}, service_name)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mysql_up{node_name=\"$node_name\"},node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "PRIMARY Service",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max by (service_name) (mysql_perf_schema_replication_group_member_info{member_role=\"PRIMARY\",replication_set=~\"$replication_set\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Group Replication Service States",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by (service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replication Group Members",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "mysql_perf_schema_replication_group_member_info{service_name=~\"$service_name\"}",
     "legendFormat": "{{Service_name}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions Details",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg_over_time(mysql_perf_schema_replication_group_worker_rep_delay_seconds{replication_set=~\"$replication_set\"}[$interval])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Applied Transactions ",
     "type": "graph",
     "description": "Number of transactions this member has received from the group and applied.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_remote_applied_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_remote_applied_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Sent Transactions ",
     "type": "graph",
     "description": "Number of transactions which originated on a member and were sent to the group.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_local_proposed_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_local_proposed_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Checked Transactions",
     "type": "graph",
     "description": "The number of transactions that have been checked for conflicts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_checked_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_checked_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Rolled Back Transactions ",
     "type": "graph",
     "description": "Number of transactions which originated on this member and were rolled back by the group.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_local_rollback_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_local_rollback_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transactions Row Validating",
     "type": "graph",
     "description": "Number of transaction rows which can be used for certification, but have not been garbage collected. Can be thought of as the current size of the conflict detection database against which each transaction is certified.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_rows_validating_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_rows_validating_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transactions in the Queue for Checking",
     "type": "graph",
     "description": "The number of transactions in the queue pending conflict detection checks. Once the transactions have been checked for conflicts, if they pass the check, they are queued to be applied as well.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (mysql_perf_schema_transactions_in_queue{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Received Transactions Queue",
     "type": "graph",
     "description": "The number of transactions that this member has received from the replication group which are waiting to be applied.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (mysql_perf_schema_transactions_remote_in_applier_queue{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detected Conflicts",
     "type": "graph",
     "description": "The number of transactions that have not passed the conflict detection check.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_conflicts_detected_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_conflicts_detected_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}