{
 "title": "MySQL TokuDB Details",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mysql_global_variables_tokudb_cache_size{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mysql_global_variables_tokudb_cache_size, service_name)"
   },
   {
    "name": "crop_service",
    "label": "Service Name",
    "query": "label_values(mysql_up{service_name=~\"$service_name\"}, service_name)"
   },
   {
    "name": "crop_host",
    "label": "Crop Node Name",
    "query": "label_values(mysql_up{node_name=\"$node_name\"},node_name)"
   },
   {
    "name": "version",
    "query": "query_result(mysql_version_info{service_name=~\"$service_name\"})"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "content": "<h1 style='color:#5991A7;font-weight:bold;text-align:center;font-style:italic'>Data for <span style='color:#e68a00'>$service_name</span> running on <span style='color:#e68a00'>$node_name</span> with <span style='color:#e68a00'>$interval</span> resolution</h1>"
  },
  {
   "title": "TokuDB Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_cache_size{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "TokuDB Block Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_block_size{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "TokuDB Block Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_read_block_size{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "TokuDB FanOut",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_fanout{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "TokuDB Checkpoint Period",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_checkpointing_period{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "TokuDB Flush Log on Commit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_commit_sync{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "TokuDB DirectIO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_variables_tokudb_directio{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Current Compression Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_global_status_tokudb_overall_node_compression_ratio{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_txn_begin{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_txn_begin{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Transactions Started "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_txn_begin_read_only{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_txn_begin_read_only{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Read Only Transactions Started"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_txn_commits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_txn_commits{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Transactons Committed"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_txn_aborts{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_txn_aborts{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Transactions Aborted"
      }
     ]
    },
    {
     "title": "TokuDB Messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops", "label": "Messages" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_messages_injected_at_root{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_messages_injected_at_root{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Normal Messages Injected"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_broadcase_messages_injected_at_root{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_broadcase_messages_injected_at_root{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Broadcase Messages Injected"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_messages_injected_at_root_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_messages_injected_at_root_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Total Size of Messages Injected"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_messages_flushed_from_h1_to_leaves_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_messages_flushed_from_h1_to_leaves_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Total Size of Messages Flushed to Leaves"
      }
     ]
    },
    {
     "title": "TokuDB Compression/Serialization Resource Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_compression_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_compression_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Compression Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_decompression_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_decompression_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Decompression Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_serialization_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_serialization_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Serialization Load "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_deserialization_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_deserialization_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Deserialization Load "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_compression_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_compression_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Compression Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_decompression_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_decompression_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Decompression Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_serialization_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_serialization_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Serialization Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_deserialization_to_memory_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_deserialization_to_memory_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Lead Deserialization"
      }
     ]
    },
    {
     "title": "TokuDB Injections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_injections_at_depth_0{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_0{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Depth  0 Injections"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_injections_at_depth_1{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_1{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Depth 1 Injections"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_injections_at_depth_2{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_2{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Depth 2 Injections"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_injections_at_depth_3{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_3{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Depth 3 Injections"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_injections_lower_than_depth_3{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_lower_than_depth_3{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Depth Lower than 3 Injections"
      }
     ]
    },
    {
     "title": "TokuDB Promotion Stopped Reason",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_stopped_nonempty_buffer{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_nonempty_buffer{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Empty Buffer"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_stopped_at_height_1{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_at_height_1{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Reached Height 1 "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_stopped_child_locked_or_not_in_memory{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_child_locked_or_not_in_memory{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Child Locked or Not in Memory"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_stopped_child_not_fully_in_memory{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_child_not_fully_in_memory{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Child Not Fully in Memory"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_promotion_stopped_after_locking_child{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_after_locking_child{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "After Locking Child"
      }
     ]
    },
    {
     "title": "TokuDB Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_nodes_created{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_created{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Nodes Created"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_nodes_created{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_created{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Nodes Created"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_nodes_destroyed{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_destroyed{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Nodes Destroyed"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_nodes_destroyed{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_destroyed{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Nodes Destroyed"
      }
     ]
    },
    {
     "title": "TokuDB Wasteful Activities",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_messages_ignored_by_leaf_due_to_msn{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_messages_ignored_by_leaf_due_to_msn{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Dupplicate Messages Delivered to Leaves"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cursor_skip_deleted_leaf_entry{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cursor_skip_deleted_leaf_entry{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Deleted Leaf Entries Scanned"
      },
      {
       "expr": "avg by (service_name) (1-rate(mysql_global_status_tokudb_leaf_entry_apply_gc_bytes_out{service_name=~\"$service_name\"}[1h])/rate(mysql_global_status_tokudb_leaf_entry_apply_gc_bytes_in{service_name=~\"$service_name\"}[1h]))",
       "legendFormat": "Leaves Garbage Percent (1h avg)"
      }
     ]
    },
    {
     "title": "TokuDB Open Databases",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_db_open_current{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_tokudb_db_open_current{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "TokuDB Databases Currently Open"
      },
      {
       "expr": "avg by (service_name) (mysql_global_status_tokudb_db_open_max{service_name=~\"$service_name\"})",
       "legendFormat": "Max TokuDB Open Databases"
      }
     ]
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB CacheTable Overview",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_limit{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_size_limit{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "CacheTable Size Limit"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_current{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_size_current{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "CacheTable Size Current"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_leaf{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_size_leaf{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Caching Leaf Data"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_nonleaf{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_size_nonleaf{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Caching Non Leaf Data"
      }
     ]
    },
    {
     "title": "TokuDB CacheTable Special",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_cloned{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_tokudb_cachetable_size_cloned{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Cloned CacheTable Size"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_rollback{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_tokudb_cachetable_size_rollback{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Rollback CacheTable Size"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_size_writing{service_name=~\"$service_name\"}[$interval]) or max_over_time(mysql_global_status_tokudb_cachetable_size_writing{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Writing CacheTable Size"
      }
     ]
    },
    {
     "title": "Cache Pressure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (mysql_global_status_tokudb_cachetable_size_cachepressure{service_name=~\"$service_name\"}/mysql_global_status_tokudb_cachetable_size_current{service_name=~\"$service_name\"})",
       "legendFormat": "Cache Pressure Ratio"
      }
     ]
    },
    {
     "title": "CacheTable Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Misses/Evictions" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_evictions{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_evictions{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Evictions"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_miss{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_miss{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Misses"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_miss_time{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_cachetable_miss_time{service_name=~\"$service_name\"}[5m])/100000)",
       "legendFormat": "Misses Load "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_prefetches{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_prefetches{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "Prefetches"
      }
     ]
    },
    {
     "title": "Partial Evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Eviction Counts" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_node_partial_evictions{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_node_partial_evictions{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Partial Evictions"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_node_partial_evictions{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_node_partial_evictions{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Partial Evictions"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_node_partial_evictions_bytes{service_name=~\"$service_name\"}[$interval]) + rate(mysql_global_status_tokudb_nonleaf_node_partial_evictions_bytes{service_name=~\"$service_name\"}[$interval])) or (irate(mysql_global_status_tokudb_leaf_node_partial_evictions_bytes{service_name=~\"$service_name\"}[5m]) + irate(mysql_global_status_tokudb_nonleaf_node_partial_evictions_bytes{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Evicted Bytes"
      }
     ]
    },
    {
     "title": "Full Evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Eviction Counts" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_node_full_evictions{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_node_full_evictions{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Full Evictions"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_node_full_evictions{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_node_full_evictions{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Full Evictions"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_node_full_evictions_bytes{service_name=~\"$service_name\"}[$interval]) + rate(mysql_global_status_tokudb_nonleaf_node_full_evictions_bytes{service_name=~\"$service_name\"}[$interval])) or (irate(mysql_global_status_tokudb_leaf_node_full_evictions_bytes{service_name=~\"$service_name\"}[5m]) + irate(mysql_global_status_tokudb_nonleaf_node_full_evictions_bytes{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Evicted Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpointing and Flushing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Checkpointing Summary",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Checkpoints Taken"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_checkpoint_duration{service_name=~\"$service_name\"}[1h]))",
       "legendFormat": "Avg Checkpoint Load (1h)"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_checkpoint_begin_time{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_checkpoint_begin_time{service_name=~\"$service_name\"}[5m])/1000000)",
       "legendFormat": "Critical Section (Begin) Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_checkpoint_end_time{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_checkpoint_end_time{service_name=~\"$service_name\"}[5m])/1000000)",
       "legendFormat": "Non Critical Section (End) Load"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{service_name=~\"$service_name\"}[$interval])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{service_name=~\"$service_name\"}[$interval])) or (irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{service_name=~\"$service_name\"}[5m])+irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Disk Flush Load"
      }
     ]
    },
    {
     "title": "TokuDB Checkpoint Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s", "label": "Avg Time" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_checkpoint_begin_time{service_name=~\"$service_name\"}[$interval])/1000000/rate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[$interval])) or (irate(mysql_global_status_tokudb_checkpoint_begin_time{service_name=~\"$service_name\"}[5m])/1000000/irate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Avg Critical Section Time"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_checkpoint_end_time{service_name=~\"$service_name\"}[$interval])/1000000/rate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[$interval])) or ((irate(mysql_global_status_tokudb_checkpoint_end_time{service_name=~\"$service_name\"}[5m])/1000000/irate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[5m]))))",
       "legendFormat": "Avg Non Critical Section Time"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{service_name=~\"$service_name\"}[1h])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{service_name=~\"$service_name\"}[1h]))/rate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[1h]))",
       "legendFormat": "Bytes Flushed Per Checkpoint (1h avg)"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_uncompressed_bytes{service_name=~\"$service_name\"}[1h])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_uncompressed_by{service_name=~\"$service_name\"}[1h]))/rate(mysql_global_status_tokudb_checkpoint_taken{service_name=~\"$service_name\"}[1h]))",
       "legendFormat": "Uncompressed Data Processed Per Checkpoint (1h avg)"
      }
     ]
    },
    {
     "title": "Checkpoint Flushing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Nodes Flushed Bytes"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Lead Nodes Flushed Bytes"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{service_name=~\"$service_name\"}[5m])) + (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Checkpoint Flushed Total"
      }
     ]
    },
    {
     "title": "Not-Checkpoint Flushing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Nodes Flushed Bytes"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Lead Nodes Flushed Bytes"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{service_name=~\"$service_name\"}[5m])) + (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Not Checkpoint Flushed Total"
      }
     ]
    },
    {
     "title": "Avg Flushed Node Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{service_name=~\"$service_name\"}[$interval])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]))/(rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint{service_name=~\"$service_name\"}[$interval])+rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint{service_name=~\"$service_name\"}[$interval])))",
       "legendFormat": "Flushed Non Leaf Node Size"
      },
      {
       "expr": "avg by (service_name) ((rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{service_name=~\"$service_name\"}[$interval])+rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{service_name=~\"$service_name\"}[$interval]))/(rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint{service_name=~\"$service_name\"}[$interval])+rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint{service_name=~\"$service_name\"}[$interval])))",
       "legendFormat": "Flushed Leaf Node Size"
      }
     ]
    },
    {
     "title": "Flushing Disk Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Nodes Checkpoint "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Nodes Checkpoint"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Leaf Nodes Not Checkpoint"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Non Leaf Nodes Not Checkpoint"
      }
     ]
    }
   ]
  },
  {
   "title": "Pivots, Basements, Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Pivots Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_pivots_fetched_for_query_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_query_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Query Pivots Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prefetch Pivots Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_pivots_fetched_for_write_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_write_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Write Pivots Size"
      }
     ]
    },
    {
     "title": "TokuDB Pivots Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_pivots_fetched_for_query_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_query_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Query Pivots Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prefetch Pivots Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_pivots_fetched_for_write_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_write_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Write Pivots Load"
      }
     ]
    },
    {
     "title": "TokuDB Basements Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_target_query_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_target_query_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Query Basements Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_prefetch_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prefetch_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prefetch Basements Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_for_write_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_for_write_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Write Basements Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_prelocked_range_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prelocked_range_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prelocked Range Basements Size"
      }
     ]
    },
    {
     "title": "TokuDB Basements Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_target_query_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_target_query_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Query Basements Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_prefetch_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prefetch_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prefetch Basements Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_for_write_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_for_write_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Write Basements Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_basements_fetched_prelocked_range_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prelocked_range_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prelocked Range Basements Load"
      }
     ]
    },
    {
     "title": "TokuDB Buffers Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_target_query_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_target_query_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Query Buffers Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_prefetch_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prefetch_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prefetch Buffers Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_for_write_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_for_write_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Write Buffers Size"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prelocked Range Buffers Size"
      }
     ]
    },
    {
     "title": "TokuDB Buffers Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_target_query_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_target_query_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Query Buffers Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_prefetch_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prefetch_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prefetch Buffers Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_for_write_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_for_write_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Write Buffers Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Fetched for Prelocked Range Buffers Load"
      }
     ]
    }
   ]
  },
  {
   "title": "Logger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Logger",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_logger_writes_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes_bytes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Data written to WAL"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_logger_writes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "WAL Writes"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_filesystem_fsync_num{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_filesystem_fsync_num{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Total Fsyncs  "
      }
     ]
    },
    {
     "title": "TokuDB Logger Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_logger_writes_seconds{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes_seconds{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Logger Load "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_filesystem_fsync_time{service_name=~\"$service_name\"}[$interval])/1000000  or irate(mysql_global_status_tokudb_filesystem_fsync_time{service_name=~\"$service_name\"}[5m])/1000000)",
       "legendFormat": "Fsync Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_filesystem_fsync_time{service_name=~\"$service_name\"}[$interval])/rate(mysql_global_status_tokudb_filesystem_fsync_num{service_name=~\"$service_name\"}[$interval])/1000000  or irate(mysql_global_status_tokudb_filesystem_fsync_time{service_name=~\"$service_name\"}[5m])/irate(mysql_global_status_tokudb_filesystem_fsync_num{service_name=~\"$service_name\"}[5m])/1000000)",
       "legendFormat": "Fsync Avg Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "LockTree",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB LockTree Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (mysql_global_status_tokudb_locktree_memory_size_limit{service_name=~\"$service_name\"})",
       "legendFormat": "LockTree Memory Limit"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_locktree_memory_size{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "Current LockTree Size "
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_locktree_open_current{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "Currently Open LockTrees"
      }
     ]
    },
    {
     "title": "TokuDB LockTree Waits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_locktree_pending_lock_requests{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "Pending Lock Requests"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_locktree_wait_count{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_locktree_wait_count{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Lock Waits "
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_locktree_wait_time{service_name=~\"$service_name\"}[$interval])/1000000 or irate(mysql_global_status_tokudb_locktree_wait_count{service_name=~\"$service_name\"}[5m])/1000000)",
       "legendFormat": "Lock Wait Load"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_locktree_timeout_count{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_locktree_timeout_count{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Lock Wait Timeouts"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Client Thread Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Client Thread Pool Size"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads_active{service_name=~\"$service_name\"}[$interval]) or\navg_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads_active{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Active"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads_active{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_pool_client_num_threads_active{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Active"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_client_queue_size{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_pool_client_queue_size{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Queue Size"
      }
     ]
    },
    {
     "title": "TokuDB CacheTable Thread Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "CacheTable Thread Pool Size"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads_active{service_name=~\"$service_name\"}[$interval]) or\navg_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads_active{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Active"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads_active{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_pool_cachetable_num_threads_active{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Active"
      }
     ]
    },
    {
     "title": "TokuDB Checkpoint Thread Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Checkpoint Thread Pool Size"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads_active{service_name=~\"$service_name\"}[$interval]) or\navg_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads_active{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Active"
      },
      {
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads_active{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_tokudb_cachetable_pool_checkpoint_num_threads_active{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Active"
      }
     ]
    },
    {
     "title": "TokuDB Background Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_cleaner_executions{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_cleaner_executions{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Cleaner Executions"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_pool_client_total_items_processed{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_pool_client_total_items_processed{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Client Items Processed"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_pool_cachetable_total_items_processed{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_pool_cachetable_total_items_processed{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Cachetable Items Processed"
      },
      {
       "expr": "avg by (service_name) (rate(mysql_global_status_tokudb_cachetable_pool_checkpoint_total_items_processed{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_pool_checkpoint_total_items_processed{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Checkpoint Items Processed"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Schema",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "TokuDB Top Wait Events (Count)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name,event_name) ((rate(mysql_perf_schema_events_waits_total{service_name=~\"$service_name\",event_name=~\".+/fti/.+|.+/tokudb/.+\"}[$interval]) or\nirate(mysql_perf_schema_events_waits_total{service_name=~\"$service_name\",event_name=~\".+/fti/.+|.+/tokudb/.+\"}[5m]))))",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "TokuDB Top Wait Events (Load)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name,event_name) ((rate(mysql_perf_schema_events_waits_seconds_total{service_name=~\"$service_name\",event_name=~\".+/fti/.+|.+/tokudb/.+\"}[$interval]) or\nirate(mysql_perf_schema_events_waits_seconds_total{service_name=~\"$service_name\",event_name=~\".+/fti/.+|.+/tokudb/.+\"}[5m]))))",
       "legendFormat": "{{event_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Uptime",
     "type": "singlestat",
     "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_status_uptime{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 15 },
     "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
    },
    {
     "title": "Current QPS",
     "type": "singlestat",
     "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 15 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (rate(mysql_global_status_queries{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_queries{service_name=~\"$service_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "File Handlers Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 15 },
     "format": "percentunit",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[5m]))) / (sum\r(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[5m]))\r)"
      }
     ]
    },
    {
     "title": "Table Open Cache Miss Ratio",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (1-((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[5m])))))"
      }
     ]
    },
    {
     "title": "Table Open Cache Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 15 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_open_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Table Definition Cache Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_definition_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Service",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 15 },
     "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/mysql-instance-summary/mysql-instance-summary?var-service_name=$service_name\" target=\"_blank\">$crop_service...</h5>",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{service_name=~\"$service_name\"} "
      }
     ]
    },
    {
     "title": "MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL Client Thread Activity",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Running"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "graph",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,handler) (rate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(10, avg by (service_name,command) (rate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[$interval]))>0 or \navg by (service_name,command) (irate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[5m]))>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "Process States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,state) (max_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "MySQL Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "singlestat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "singlestat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "singlestat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 16 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "singlestat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 16 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100)"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "singlestat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 16 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "singlestat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 16 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "singlestat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100)"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
     "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></h5>",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{service_name=~\"$service_name\"} "
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (sum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}