{
 "title": "MySQL Amazon Aurora Metrics",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Node Name",
    "query": "label_values(mysql_global_variables_aurora_lab_mode, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mysql_global_variables_aurora_lab_mode{node_name=~\"$host\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Amazon Aurora Transaction Commits",
   "type": "graph",
   "description": "This graph shows the number of Commits which Amazon Aurora engine performed as well as average commit latency. Graph Latency does not always correlate with the number of performed commits and can be quite high in certain situations.\n\n* **Number of Amazon Aurora Commits**: The average number of commit operations per second.\n\n* **Amazon Aurora Commit avg Latency**: The average amount of latency for commit operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commits{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_auroradb_commits{service_name=\"$service\"}[5m])",
     "legendFormat": "Number of Amazon Aurora Commits "
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commit_latency{service_name=\"$service\"}[$interval])/rate(mysql_global_status_auroradb_commits{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_auroradb_commit_latency{service_name=\"$service\"}[5m])/irate(mysql_global_status_auroradb_commits{service_name=\"$service\"}[5m])",
     "legendFormat": "Amazon Aurora Commit avg Latency"
    }
   ]
  },
  {
   "title": "Amazon Aurora Load",
   "type": "graph",
   "description": "This graph shows us what statements contribute most load on the system as well as what load corresponds to Amazon Aurora transaction commit.\n\n* **Write Transaction Commit Load**: Load in Average Active Sessions per second for COMMIT operations\n\n* **UPDATE load**: Load in Average Active Sessions per second for UPDATE queries\n\n* **SELECT load**: Load in Average Active Sessions per second for SELECT queries\n\n* **DELETE load**: Load in Average Active Sessions per second for DELETE queries\n\n* **INSERT load**: Load in Average Active Sessions per second for INSERT queries\n\nAn *active session* is a connection that has submitted work to the database engine and is waiting for a response from it. For example, if you submit an SQL query to the database engine, the database session is active while the database engine is processing that query.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commit_latency{service_name=\"$service\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_commit_latency{service_name=\"$service\"}[5m])/1000000",
     "legendFormat": "Write Transaction Commit Load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_ddl_stmt_duration{service_name=\"$service\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_ddl_stmt_duration{service_name=\"$service\"}[5m])/1000000",
     "legendFormat": "DDL Load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_select_stmt_duration{service_name=\"$service\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_select_stmt_duration{service_name=\"$service\"}[5m])/1000000",
     "legendFormat": "SELECT load "
    },
    {
     "expr": "rate(mysql_global_status_auroradb_insert_stmt_duration{service_name=\"$service\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_insert_stmt_duration{service_name=\"$service\"}[5m])/1000000",
     "legendFormat": "INSERT load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_update_stmt_duration{service_name=\"$service\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_update_stmt_duration{service_name=\"$service\"}[5m])/1000000",
     "legendFormat": "UPDATE load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_delete_stmt_duration{service_name=\"$service\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_delete_stmt_duration{service_name=\"$service\"}[5m])/1000000",
     "legendFormat": "DELETE load"
    }
   ]
  },
  {
   "title": "Aurora Memory Used",
   "type": "graph",
   "description": "This graph shows how much memory is used by Amazon Aurora lock manager as well as amount of memory used by Amazon Aurora to store Data Dictionary.\n\n* **Aurora Lock Manager Memory**: the amount of memory used by the Lock Manager, the module responsible for handling row lock requests for concurrent transactions.\n\n* **Aurora Dictionary Memory**: the amount of memory used by the Dictionary, the space that contains metadata used to keep track of database objects, such as tables and indexes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aurora_lockmgr_memory_used{service_name=\"$service\"}",
     "legendFormat": "Aurora Lock Manager Memory"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aurora_dict_sys_mem_size{service_name=\"$service\"}",
     "legendFormat": "Aurora Dictionary Memory "
    }
   ]
  },
  {
   "title": "Amazon Aurora Statement Latency",
   "type": "graph",
   "description": "This graph shows average latency for the most important types of statements. Latency spikes are often indicative of the instance overload.\n\n* **DDL Latency:** Average time to execute DDL queries\n\n* **DELETE Latency**: Average time to execute DELETE queries\n\n* **UPDATE Latency**: Average time to execute UPDATE queries\n\n* **SELECT Latency**: Average time to execute SELECT queries\n\n* **INSERT Latency**: Average time to execute INSERT queries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "(rate(mysql_global_status_auroradb_ddl_stmt_duration{service_name=\"$service\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=\"$service\",command=~'alter_table|create_index|drop_index|drop_table'}[$interval])) without(command)))",
     "legendFormat": "DDL Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_select_stmt_duration{service_name=\"$service\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=\"$service\",command='select'}[$interval])) without(command))+rate(mysql_global_status_qcache_hits{service_name=\"$service\"}[$interval]))",
     "legendFormat": "SELECT Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_insert_stmt_duration{service_name=\"$service\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=\"$service\",command=~'insert|insert_select'}[$interval])) without(command)))",
     "legendFormat": "INSERT Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_update_stmt_duration{service_name=\"$service\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=\"$service\",command=~'update|update_multi'}[$interval])) without(command)))",
     "legendFormat": "UPDATE Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_delete_stmt_duration{service_name=\"$service\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{service_name=\"$service\",command=~'delete|delete_multi'}[$interval])) without(command)))",
     "legendFormat": "DELETE Latency"
    }
   ]
  },
  {
   "title": "Amazon Aurora Special Command Counters",
   "type": "graph",
   "description": "Amazon Aurora MySQL allows a number of commands which are not available in standard MySQL. This graph shows usage of such commands.  Regular “unit_test” calls can be seen in default Amazon Aurora install,  the rest will depend on your workload.\n\n* `show_volume_status`: The number of executions per second of the command SHOW VOLUME STATUS. The SHOW VOLUME STATUS query returns two server status variables, Disks and Nodes. These variables represent the total number of logical blocks of data and storage nodes, respectively, for the DB cluster volume.\n\n* `awslambda`: The number of AWS Lambda calls per second. AWS Lambda is an event-drive, server-less computing platform provided by AWS. It is a compute service that run codes in response to an event. You can run any kind of code from Aurora invoking Lambda from a stored procedure or a trigger.\n\n* `alter_system`: The number of executions per second of the special query ALTER SYSTEM, that is a special query to simulate an instance crash, a disk failure, a disk congestion or a replica failure. It’s a useful query for testing the system.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{service_name=\"$service\",command=~'awslambda|alter_system|unit_test|show_volume_status'}[$interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Amazon Aurora Problems",
   "type": "graph",
   "description": "This graph shows different kinds of Internal Amazon Aurora MySQL Problems which general should be zero in normal operation.\n\nAnything non-zero is worth examining in greater depth.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_auroradb_thread_deadlocks{service_name=\"$service\"}[$interval])",
     "legendFormat": "Thread Deadlocks"
    },
    {
     "expr": "rate(mysql_global_status_aurora_missing_history_on_replica_incidents{service_name=\"$service\"}[$interval])",
     "legendFormat": "Missing History on Replica Incidents"
    },
    {
     "expr": "rate(mysql_global_status_aurora_reserved_mem_exceeded_incidents{service_name=\"$service\"}[$interval])",
     "legendFormat": "Reserved Mem Exceeded Incidents"
    }
   ]
  }
 ]
}