{
 "title": "MySQL Services Overview",
 "tags": [
  "Percona",
  "MySQL",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "region", "label": "Region", "query": "label_values(mysql_up, region)" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(mysql_up, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mysql_up, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication_Set",
    "query": "label_values(mysql_up, replication_set)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up{region=~\"$region\",environment=~\"$environment\",cluster=~\"$cluster\",replication_set=~\"$replication_set\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mysql_up{node_name=~\"$host\"}, service_name)"
   },
   {
    "name": "node_id",
    "label": "Node_ID",
    "query": "label_values(mysql_up{node_name=\"$host\"}, node_id)"
   },
   {
    "name": "agent_id",
    "label": "Agent_ID",
    "query": "label_values(mysql_up{node_name=\"$host\"}, instance)"
   },
   {
    "name": "service_id",
    "label": "Service_ID",
    "query": "label_values(mysql_up{service_name=~\"$service\"}, service_id)"
   },
   {
    "name": "az",
    "label": "Az",
    "query": "label_values(mysql_up{node_name=\"$host\"}, az)"
   },
   {
    "name": "node_type",
    "label": "Node_type",
    "query": "label_values(mysql_up{node_name=\"$host\"}, node_type)"
   },
   {
    "name": "node_model",
    "label": "Node_model",
    "query": "label_values(mysql_up{node_name=\"$host\"}, node_model)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "singlestat",
   "description": "Amount of monitored services",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(mysql_global_status_uptime{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Min MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(mysql_global_status_uptime{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Max MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(mysql_global_status_uptime{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(mysql_global_status_queries{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_queries{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total InnoDB Buffer Pool Size",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(mysql_global_variables_innodb_buffer_pool_size{service_name=~\"$service\"})"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top MySQL Used Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Used Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 4 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[5m])) / on (service_name)\nmysql_global_variables_max_connections{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Top MySQL Client  Threads Connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 4 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((max_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[5m])) / on (service_name)\nmysql_global_variables_max_connections{service_name=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Top MySQL Active Client Threads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 4 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(1 - (max_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top MySQL Thread Cached",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((max_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_thread_cache_size{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_thread_cache_size{service_name=~\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Connections details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 MySQL Used Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Used Connections",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service\"}[5m])) / on (service_name)\nmysql_global_variables_max_connections{service_name=~\"$service\"}),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Client  Threads Connected",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Client  Threads Connected",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[5m])) / on (service_name)\nmysql_global_variables_max_connections{service_name=~\"$service\"}),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Active Client Threads",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(max_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Idle Client  Threads",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "clamp_max((1 - (max_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service\"}[5m]))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Thread Cached",
     "type": "graph",
     "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(max_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of  Cached MySQL Threads",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_cached{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_thread_cache_size{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_thread_cache_size{service_name=~\"$service\"}[5m]))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Top MySQL Queries",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_queries{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_queries{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Questions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 8 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "clamp_max(max((rate(mysql_global_status_questions{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_questions{service_name=~\"$service\"}[5m])) / \n(rate(mysql_global_status_queries{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_queries{service_name=~\"$service\"}[5m]))),1)"
    }
   ]
  },
  {
   "title": "Top InnoDB I/O Data Reads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 8 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) / \n((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m]))\n))"
    }
   ]
  },
  {
   "title": "Top InnoDB I/O Data Writes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 8 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) / \n((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m]))\n))"
    }
   ]
  },
  {
   "title": "Top Data Fsyncs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 8 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m])) / \n((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m]))\n))"
    }
   ]
  },
  {
   "title": "Queries & Questions details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 MySQL Queries",
     "type": "graph",
     "description": "**MySQL Queries**\n\nThe number of statements executed by the server. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count  ``COM_PING`` or ``COM_STATISTICS``  commands.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_queries{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_queries{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL  QPS",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(mysql_global_status_queries{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_quesries{service_name=~\"$service\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Questions",
     "type": "graph",
     "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_questions{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_questions{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL  Questions in Queries",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "clamp_max((rate(mysql_global_status_questions{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_questions{service_name=~\"$service\"}[5m])) / \n(rate(mysql_global_status_queries{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_queries{service_name=~\"$service\"}[5m])),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB I/O details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Data Reads",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of Data Read",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "clamp_max(((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) / \n((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m]))\n)),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Data Writes",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of Data Writes",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "clamp_max(((rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) / \n((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m])))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Data Fsyncs",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of Data Fsyncs",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "clamp_max(((rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m])) / \n((rate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_reads{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_writes{service_name=~\"$service\"}[5m])) +\n(rate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_innodb_data_fsyncs{service_name=~\"$service\"}[5m])))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Top MySQL Questions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Selects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 13 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_select_full_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range_check{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range_check{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_scan{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Sorts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 13 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_sort_rows{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_rows{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_scan{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL  Aborted Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 13 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL  Table Locks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 13 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Temporary Objects details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Temporary Objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Temporary Objects",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "rate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_disk_tables{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_created_tmp_files{service_name=~\"$service\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Selects",
     "type": "graph",
     "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_select_full_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range_check{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range_check{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_scan{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_select_full_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range_check{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range_check{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_scan{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Selects",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(mysql_global_status_select_full_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_full_range_join{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_range_check{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_range_check{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_select_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_select_scan{service_name=~\"$service\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sorts details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 MySQL Sorts",
     "type": "graph",
     "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_sort_rows{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_rows{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_scan{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_sort_rows{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_rows{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_scan{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Sorts",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(mysql_global_status_sort_rows{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_rows{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_range{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_range{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_merge_passes{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_sort_scan{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_sort_scan{service_name=~\"$service\"}[5m])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Aborted Connections and Locks details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 MySQL Aborted Connections",
     "type": "graph",
     "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Aborted Connections",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "(rate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_connects{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_aborted_clients{service_name=~\"$service\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Table Locks",
     "type": "graph",
     "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "MySQL Table Locks",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "(rate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_immediate{service_name=~\"$service\"}[5m]) +\nrate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_locks_waited{service_name=~\"$service\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top MySQL Incoming Network Traffic",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "format": "Bps",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_bytes_received{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Outgoing Network Traffic",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 19 },
   "format": "Bps",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_bytes_sent{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Used Query Cache",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 19 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(1 - (max_over_time(mysql_global_status_qcache_free_memory{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_qcache_free_memory{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_query_cache_size{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_query_cache_size{service_name=~\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Percentage of File Openings to Opened Files",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 19 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((rate(mysql_global_status_opened_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_opened_files{service_name=~\"$service\"}[5m])) / \n(max_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Percentage of  Opened Files to the Limit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 19 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((max_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Network details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 MySQL Incoming Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_bytes_received{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_bytes_received{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Outgoing Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_bytes_sent{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_bytes_sent{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Cache details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Query Cache Size",
     "type": "graph",
     "description": "**MySQL Query Cache Memory**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n  ``query_cache_type=0``\n  ``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_variables_query_cache_size{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_query_cache_size{service_name=~\"$service\"}[5m]) ",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL Used Query Cache",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "clamp_max((1 - (max_over_time(mysql_global_status_qcache_free_memory{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_qcache_free_memory{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_query_cache_size{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_query_cache_size{service_name=~\"$service\"}[5m]))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Files details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 MySQL File Openings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(rate(mysql_global_status_opened_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_opened_files{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_opened_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_opened_files{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of File Openings to Opened Files",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "clamp_max(((rate(mysql_global_status_opened_files{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_opened_files{service_name=~\"$service\"}[5m])) / (max_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[5m]))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Opened Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(max_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of  Opened Files to the Limit",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_files{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service\"}[5m]))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Top Open Cache Miss Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 25 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(1 - (rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))/\n((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))+\n(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Min MySQL Opened Table Definitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 25 },
   "format": "bytes",
   "valueName": "min",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(max_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[5m]) )"
    }
   ]
  },
  {
   "title": "Top MySQL Opened Table Definitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 25 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(rate(mysql_global_status_opened_table_definitions{service_name=~\"$service\"}[$interval]) or \nrate(mysql_global_status_opened_table_definitions{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top MySQL Open Table Definitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 25 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top  Open Table Definitions to Definition Cache",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 25 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max((max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[5m])))"
    }
   ]
  },
  {
   "title": "Table Openings details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lowest 5 Open Cache Hit Ratio",
     "type": "graph",
     "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bottomk(5,((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))/\n((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))+\n(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[5m])))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))/\n((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))+\n(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[5m]))))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Open Cache Miss Ratio",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "clamp_max((1 - (rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))/\n((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_hits{service_name=~\"$service\"}[5m]))+\n(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[$interval]) or \nirate(mysql_global_status_table_open_cache_misses{service_name=~\"$service\"}[5m])))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL Open and Cached Table Definitions details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Table Definition Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[5m]) ",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Opened Table Definitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(rate(mysql_global_status_opened_table_definitions{service_name=~\"$service\"}[$interval]) or \nrate(mysql_global_status_opened_table_definitions{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mysql_global_status_opened_table_definitions{service_name=~\"$service\"}[$interval]) or \nrate(mysql_global_status_opened_table_definitions{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Top 5 MySQL Open Table Definitions",
     "type": "graph",
     "description": "Number of currently cached .frm files.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5,(max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Percentage of Open Table Definitions to Table Definition Cache",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "clamp_max(((max_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_open_table_definitions{service_name=~\"$service\"}[5m])) / on (service_name)\n(max_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_variables_table_definition_cache{service_name=~\"$service\"}[5m]))),1)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}