{
 "title": "NUMA Overview",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_memory_numa_MemTotal, node_name)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_memory_numa_numa_hit_total,node)"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(node_buddyinfo_blocks{node_name=~\"$host\"}, zone)"
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_MemTotal{node_name=~\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{node_name=~\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemUsed{node_name=~\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Free Memory Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{node_name=~\"$host\"}) * 100 /\nsum by (node) (node_memory_numa_MemTotal{node_name=~\"$host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "NUMA Memory Usage Types",
   "type": "graph",
   "description": "**Dirty** Memory waiting to be written back to disk\n\n**Bounce** Memory used for block device bounce buffers\n\n**Mapped** Files which have been mmaped, such as libraries\n\n**KernelStack** The memory the kernel stack uses. This is not reclaimable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(node_memory_numa_Active{node_name=~\"$host\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(node_memory_numa_Inactive{node_name=~\"$host\"})",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum(node_memory_numa_Dirty{node_name=~\"$host\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum(node_memory_numa_Bounce{node_name=~\"$host\"})",
     "legendFormat": "Bounce"
    },
    {
     "expr": "sum(node_memory_numa_Mapped{node_name=~\"$host\"})",
     "legendFormat": "Mapped"
    },
    {
     "expr": "sum(node_memory_numa_KernelStack{node_name=~\"$host\"})",
     "legendFormat": "KernelStack"
    }
   ]
  },
  {
   "title": "NUMA Allocation Hits",
   "type": "graph",
   "description": "Memory successfully allocated on this node as intended.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "NUMA Allocation Missed",
   "type": "graph",
   "description": "**Memory missed** is allocated on a node despite the process preferring some different node.\n\n**Memory foreign** is intended for a node, but actually allocated on some different node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Missed Node $node"
    },
    {
     "expr": "rate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[5m]) * 100 /\n(rate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[5m]) + \nrate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Missed ratio Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Total Missed"
    },
    {
     "expr": "sum(rate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[5m])) * 100 /\nsum((rate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_hit_total{node_name=~\"$host\"}[5m])) + \nsum(rate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_numa_miss_total{node_name=~\"$host\"}[5m])))",
     "legendFormat": "Total Missed Ratio"
    }
   ]
  },
  {
   "title": "Anonymous Memory",
   "type": "graph",
   "description": "**Active anonymous memory** that has been used more recently and usually not swapped out.\n\n**Inactive anonymous memory** that has not been used recently and can be swapped out.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(node_memory_numa_Active_anon{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_Inactive_anon{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "NUMA File (PageCache)",
   "type": "graph",
   "description": "**Active(file)** Pagecache memory that has been used more recently and usually not reclaimed until needed\n\n**Inactive(file)** Pagecache memory that can be reclaimed without huge performance impact",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(node_memory_numa_Active_file{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_Inactive_file{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "graph",
   "description": "**Shmem** Total used shared memory (shared between several processes, thus including RAM disks, SYS-V-IPC and BSD like SHMEM)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Shmem{node_name=~\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_ShmemHugePages{node_name=~\"$host\"})",
     "legendFormat": "HugePages"
    },
    {
     "expr": "sum by (node) (node_memory_numa_ShmemPmdMapped{node_name=~\"$host\"})",
     "legendFormat": "PmdMapped"
    }
   ]
  },
  {
   "title": "HugePages Statistic",
   "type": "graph",
   "description": "**Total** Number of hugepages being allocated by the kernel (Defined with vm.nr_hugepages)\n\n**Free** The number of hugepages not being allocated by a process\n\n**Surp**  The number of hugepages in the pool above the value in vm.nr_hugepages. The maximum number of surplus hugepages is controlled by vm.nr_overcommit_hugepages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Total{node_name=~\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Free{node_name=~\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Surp{node_name=~\"$host\"})",
     "legendFormat": "Surplus"
    }
   ]
  },
  {
   "title": "Local Processes",
   "type": "graph",
   "description": "Memory allocated on a node while a process was running on it.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_local_node_total{node_name=~\"$host\"}[$interval]) or\nirate(node_memory_numa_local_node_total{node_name=~\"$host\"}[$interval])",
     "legendFormat": "Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_local_node_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_local_node_total{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Remote Processes",
   "type": "graph",
   "description": "Memory allocated on a node while a process was running on some other node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Node $node"
    },
    {
     "expr": "sum(rate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[$interval])) or\nsum(irate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[$interval])) or\nsum(irate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[5m])) * 100 /\n(sum(rate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[$interval])) or\nsum(irate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[5m])) + \nsum(rate(node_memory_numa_local_node_total{node_name=~\"$host\"}[$interval])) or\nsum(irate(node_memory_numa_local_node_total{node_name=~\"$host\"}[$interval])))",
     "legendFormat": "Total remote processes rate"
    }
   ]
  },
  {
   "title": "Slab Memory",
   "type": "graph",
   "description": "**Slab** allocation is a memory management mechanism intended for the efficient memory allocation of kernel objects.\n\n**SReclaimable** The part of the Slab that might be reclaimed (such as caches).\n\n**SUnreclaim** The part of the Slab that can't be reclaimed under memory pressure",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(node_memory_numa_Slab{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_SReclaimable{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Reclaimable"
    },
    {
     "expr": "sum(avg_over_time(node_memory_numa_SUnreclaim{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Unreclaim"
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Node $node - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_MemTotal{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Total"
      },
      {
       "expr": "avg_over_time(node_memory_numa_MemFree{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Free"
      },
      {
       "expr": "avg_over_time(node_memory_numa_MemUsed{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Node $node - Free Memory Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_memory_numa_MemFree{node_name=~\"$host\", node=\"$node\"}) * 100 /\n(node_memory_numa_MemTotal{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Node $node - NUMA Memory Usage Types",
     "type": "graph",
     "description": "**Dirty** Memory waiting to be written back to disk\n\n**Bounce** Memory used for block device bounce buffers\n\n**Mapped** Files which have been mmaped, such as libraries\n\n**KernelStack** The memory the kernel stack uses. This is not reclaimable.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg_over_time(node_memory_numa_Active{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Inactive{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Inactive"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Dirty{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Dirty"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Bounce{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Bounce"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Mapped{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Mapped"
      },
      {
       "expr": "avg_over_time(node_memory_numa_KernelStack{node_name=~\"$host\"}[$interval])",
       "legendFormat": "KernelStack"
      }
     ]
    },
    {
     "title": "Node $node - NUMA Allocation Hits",
     "type": "graph",
     "description": "Memory successfully allocated on this node as intended.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_numa_hit_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{node_name=~\"$host\", node=\"$node\"}[5m])",
       "legendFormat": "Hit Total"
      }
     ]
    },
    {
     "title": "Node $node - NUMA Allocation Missed/Foreign",
     "type": "graph",
     "description": "**Memory missed** is allocated on a node despite the process preferring some different node.\n\n**Memory foreign** is intended for a node, but actually allocated on some different node.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_numa_miss_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{node_name=~\"$host\", node=\"$node\"}[5m])",
       "legendFormat": "Missed"
      },
      {
       "expr": "rate(node_memory_numa_numa_miss_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{node_name=~\"$host\", node=\"$node\"}[5m]) * 100 /\n(rate(node_memory_numa_numa_hit_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{node_name=~\"$host\", node=\"$node\"}[5m]) + \nrate(node_memory_numa_numa_miss_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{node_name=~\"$host\", node=\"$node\"}[5m]))",
       "legendFormat": "Missed ratio"
      }
     ]
    },
    {
     "title": "Node $node - Anonymous Memory",
     "type": "graph",
     "description": "**Active** Anonymous memory that has been used more recently and usually not swapped out\n\n**Inactive** Anonymous memory that has not been used recently and can be swapped out",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_Active_anon{node_name=~\"$host\",node=\"$node\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Inactive_anon{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Node $node - NUMA File (PageCache)",
     "type": "graph",
     "description": "**Active(file)** Pagecache memory that has been used more recently and usually not reclaimed until needed\n\n**Inactive(file)** Pagecache memory that can be reclaimed without huge performance impact",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_Active_file{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "avg_over_time(node_memory_numa_Inactive_file{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Node $node - Shared Memory",
     "type": "graph",
     "description": "**Shmem** Total used shared memory (shared between several processes, thus including RAM disks, SYS-V-IPC and BSD like SHMEM)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (node_memory_numa_Shmem{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (node_memory_numa_ShmemHugePages{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "HugePages"
      },
      {
       "expr": "sum by (node) (node_memory_numa_ShmemPmdMapped{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "PmdMapped"
      }
     ]
    },
    {
     "title": "Node $node - HugePages Statistic",
     "type": "graph",
     "description": "**Total** Number of hugepages being allocated by the kernel (Defined with vm.nr_hugepages)\n\n**Free** The number of hugepages not being allocated by a process\n\n**Surp**  The number of hugepages in the pool above the value in vm.nr_hugepages. The maximum number of surplus hugepages is controlled by vm.nr_overcommit_hugepages.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (node_memory_numa_HugePages_Total{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (node_memory_numa_HugePages_Free{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) (node_memory_numa_HugePages_Surp{node_name=~\"$host\", node=\"$node\"})",
       "legendFormat": "Surplus"
      }
     ]
    },
    {
     "title": "Node $node - Local Processes",
     "type": "graph",
     "description": "Memory allocated on this node while a process was running on it.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_local_node_total{node_name=~\"$host\",node=\"$node\"}[$interval]) or\nirate(node_memory_numa_local_node_total{node_name=~\"$host\",node=\"$node\"}[$interval])",
       "legendFormat": "Node $node"
      }
     ]
    },
    {
     "title": "Node $node - Remote Processes",
     "type": "graph",
     "description": "Memory allocated on this node while a process was running on some other node.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_other_node_total{node_name=~\"$host\", node=\"$node\"}[5m])",
       "legendFormat": "Node $node"
      }
     ]
    },
    {
     "title": "Node $node - Slab Memory",
     "type": "graph",
     "description": "**Slab** allocation is a memory management mechanism intended for the efficient memory allocation of kernel objects.\n\n**SReclaimable** The part of the Slab that might be reclaimed (such as caches).\n\n**SUnreclaim** The part of the Slab that can't be reclaimed under memory pressure",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_numa_Slab{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Total"
      },
      {
       "expr": "avg_over_time(node_memory_numa_SReclaimable{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Reclaimable"
      },
      {
       "expr": "avg_over_time(node_memory_numa_SUnreclaim{node_name=~\"$host\", node=\"$node\"}[$interval])",
       "legendFormat": "Unreclaim"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "description": "/proc/buddyinfo gives you an idea about the free memory fragments on your Linux box. You get to view the free fragments for each available order, for different zones of each numa node.\n\nNote: Non-Uniform Memory Access (NUMA) refers to multiprocessor systems whose memory is divided into multiple memory nodes.\n\nEach NUMA node is an entry in the kernel linked list pgdat_list. Each node is further divided into zones. Here are some example zone types:\n\nDMA Zone: Lower 16 MiB of RAM used by legacy devices that cannot address anything beyond the first 16MiB of RAM.\n\nDMA32 Zone (only on x86_64): Some devices can't address beyond the first 4GiB of RAM. On x86, this zone would probably be covered by Normal zone\n\nNormal Zone: Anything above zone DMA and doesn't require kernel tricks to be addressable. Typically on x86, this is 16MiB to 896MiB. Many kernel operations require that the memory being used be from this zone\n\nHighmem Zone (x86 only): Anything above 896MiB.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "content": "<h1><i><font color=#5991A7><b><center>Free Memory Pages</center></b></font></i></h1>\n\n\n"
  },
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zone $zone",
     "type": "graph",
     "description": "Formula for chunks of memory 2^(Size * PAGE_SIZE) ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "repeat": "zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node,zone,size) (node_buddyinfo_blocks{node_name=~\"$host\", zone=~\"$zone\"})",
       "legendFormat": "Size {{size}}"
      }
     ]
    },
    {
     "title": "Zone $zone",
     "type": "graph",
     "description": "Formula for chunks of memory 2^(Size * PAGE_SIZE) ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node,zone,size) (node_buddyinfo_blocks{node_name=~\"$host\", zone=~\"$zone\"})",
       "legendFormat": "Size {{size}}"
      }
     ]
    },
    {
     "title": "Zone $zone",
     "type": "graph",
     "description": "Formula for chunks of memory 2^(Size * PAGE_SIZE) ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node,zone,size) (node_buddyinfo_blocks{node_name=~\"$host\", zone=~\"$zone\"})",
       "legendFormat": "Size {{size}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Node $node - Zone $zone",
     "type": "graph",
     "description": "Formula for chunks of memory 2^(Size * PAGE_SIZE) ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "repeat": "zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node,zone,size) (node_buddyinfo_blocks{node_name=~\"$host\", node=\"$node\", zone=~\"$zone\"})",
       "legendFormat": "Size {{size}}"
      }
     ]
    },
    {
     "title": "Node $node - Zone $zone",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node,zone,size) (node_buddyinfo_blocks{node_name=~\"$host\", node=\"$node\", zone=~\"$zone\"})",
       "legendFormat": "Page Size {{size}}"
      }
     ]
    }
   ]
  }
 ]
}