{
 "title": "Overview NUMA metrics",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_filesystem_avail, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_memory_numa_numa_hit_total,node)"
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Size of  Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{instance=\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemUsed{instance=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{instance=\"$host\"}) + \nsum by (node) (node_memory_numa_MemUsed{instance=\"$host\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_MemFree{instance=\"$host\"}) * 100 /\nsum by (node) (node_memory_numa_MemTotal{instance=\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemUsed{instance=\"$host\"}) * 100 /\nsum by (node) (node_memory_numa_MemTotal{instance=\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "graph",
   "description": "**Dirty** Memory waiting to be written back to disk\n\n**Bounce** Memory used for block device bounce buffers\n\n**Mapped** Files which have been mmaped, such as libraries\n\n**KernelStack** The memory the kernel stack uses. This is not reclaimable.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (node) (node_memory_numa_Active{instance=\"$host\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Inactive{instance=\"$host\"})",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Dirty{instance=\"$host\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Bounce{instance=\"$host\"})",
     "legendFormat": "Bounce"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Mapped{instance=\"$host\"})",
     "legendFormat": "Mapped"
    },
    {
     "expr": "sum by (node) (node_memory_numa_KernelStack{instance=\"$host\"})",
     "legendFormat": "KernelStack"
    }
   ]
  },
  {
   "title": "Memory Hit",
   "type": "graph",
   "description": "Memory successfully allocated on this node as intended.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_numa_hit_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_hit_total{instance=\"$host\"}[5m])",
     "legendFormat": "Node $node"
    }
   ]
  },
  {
   "title": "Memory Missed / Foreign",
   "type": "graph",
   "description": "**Memory missed** is allocated on a node despite the process preferring some different node.\n\n**Memory foreign** is intended for a node, but actually allocated on some different node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_numa_miss_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_miss_total{instance=\"$host\"}[5m])",
     "legendFormat": "Missed Node $node"
    },
    {
     "expr": "rate(node_memory_numa_numa_foreign_total{instance=\"$host\"}[$interval]) or\nirate(node_memory_numa_numa_foreign_total{instance=\"$host\"}[5m])",
     "legendFormat": "Foreign Node $node"
    }
   ]
  },
  {
   "title": "Anonymous Memory Total",
   "type": "graph",
   "description": "**Active anonymous memory** that has been used more recently and usually not swapped out.\n\n**Inactive anonymous memory** that has not been used recently and can be swapped out.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Active_anon{instance=\"$host\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Inactive_anon{instance=\"$host\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Pagecache Memory Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Active_file{instance=\"$host\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Inactive_file{instance=\"$host\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "graph",
   "description": "**Shmem** Total used shared memory (shared between several processes, thus including RAM disks, SYS-V-IPC and BSD like SHMEM)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Shmem{instance=\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_ShmemHugePages{instance=\"$host\"})",
     "legendFormat": "HugePages"
    },
    {
     "expr": "sum by (node) (node_memory_numa_ShmemPmdMapped{instance=\"$host\"})",
     "legendFormat": "PmdMapped"
    }
   ]
  },
  {
   "title": "HugePages Statistic",
   "type": "graph",
   "description": "**Total** Number of hugepages being allocated by the kernel (Defined with vm.nr_hugepages)\n\n**Free** The number of hugepages not being allocated by a process\n\n**Surp**  The number of hugepages in the pool above the value in vm.nr_hugepages. The maximum number of surplus hugepages is controlled by vm.nr_overcommit_hugepages.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Total{instance=\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Free{instance=\"$host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_HugePages_Surp{instance=\"$host\"})",
     "legendFormat": "Surplus"
    }
   ]
  },
  {
   "title": "Slab Memory",
   "type": "graph",
   "description": "**Slab** allocation is a memory management mechanism intended for the efficient memory allocation of kernel objects.\n\n**SReclaimable** The part of the Slab that might be reclaimed (such as caches).\n\n**SUnreclaim** The part of the Slab that can't be reclaimed under memory pressure",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Slab{instance=\"$host\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node) (node_memory_numa_SReclaimable{instance=\"$host\"})",
     "legendFormat": "Reclaimable"
    },
    {
     "expr": "sum by (node) (node_memory_numa_SUnreclaim{instance=\"$host\"})",
     "legendFormat": "Unreclaim"
    }
   ]
  },
  { "title": "Node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "node" },
  {
   "title": "Size of Memory on Node $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_numa_MemFree{instance=\"$host\", node=\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (node) (node_memory_numa_MemUsed{instance=\"$host\", node=\"$node\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Usage on Node $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_numa_MemFree{instance=\"$host\", node=\"$node\"}) * 100 /\n(node_memory_numa_MemTotal{instance=\"$host\", node=\"$node\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_numa_MemUsed{instance=\"$host\", node=\"$node\"}) * 100 /\n(node_memory_numa_MemTotal{instance=\"$host\", node=\"$node\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Statistics Node $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_memory_numa_Active{instance=\"$host\", node=\"$node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_numa_Inactive{instance=\"$host\", node=\"$node\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_numa_Dirty{instance=\"$host\", node=\"$node\"}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "Anonymous Memory on Node $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_numa_Active_anon{instance=\"$host\",node=\"$node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_numa_Inactive_anon{instance=\"$host\", node=\"$node\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Pagecache Memory on Node $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (node_memory_numa_Active_file{instance=\"$host\", node=\"$node\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum by (node) (node_memory_numa_Inactive_file{instance=\"$host\", node=\"$node\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Local Processes on Node $node",
   "type": "graph",
   "description": "Memory allocated on this node while a process was running on it.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_local_node_total{instance=\"$host\",node=\"$node\"}[$interval]) or\nirate(node_memory_numa_local_node_total{instance=\"$host\",node=\"$node\"}[$interval])",
     "legendFormat": "Node $node"
    }
   ]
  },
  {
   "title": "Remote Processes",
   "type": "graph",
   "description": "Memory allocated on this node while a process was running on some other node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[$interval]) or\nirate(node_memory_numa_other_node_total{instance=\"$host\", node=\"$node\"}[5m])",
     "legendFormat": "Node $node"
    }
   ]
  }
 ]
}