{
 "title": "PostgreSQL Summary",
 "tags": [
  "Percona",
  "PostgreSQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "work_mem",
    "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service\"})"
   },
   { "name": "host", "label": "Node Name", "query": "label_values(pg_up,node_name)" },
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(pg_up{node_name=~\"$host\"}, service_name)"
   },
   {
    "name": "db",
    "label": "DB",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "version",
    "query": "label_values(pg_static{service_name=~\"$service\"},version)"
   },
   {
    "name": "max_connections",
    "query": "query_result(pg_settings_max_connections{service_name=~\"$service\"})"
   },
   {
    "name": "shared_buffers",
    "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "wal_buffers",
    "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "wal_segment_size",
    "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "maintenance_work_mem",
    "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "block_size",
    "query": "query_result(pg_settings_block_size{service_name=~\"$service\"})"
   },
   {
    "name": "checkpoint_segments",
    "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service\"})"
   },
   {
    "name": "checkpoint_timeout",
    "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "default_statistics_target",
    "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service\"})"
   },
   {
    "name": "seq_page_cost",
    "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service\"})"
   },
   {
    "name": "random_page_cost",
    "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service\"})"
   },
   {
    "name": "effective_cache_size",
    "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "effective_io_concurrency",
    "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service\"})"
   },
   {
    "name": "fsync",
    "query": "query_result(pg_settings_fsync{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum",
    "query": "query_result(pg_settings_autovacuum{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_max_workers",
    "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_naptime",
    "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service\"})"
   },
   {
    "name": "logging_collector",
    "query": "query_result(pg_settings_logging_collector{service_name=~\"$service\"})"
   },
   {
    "name": "log_min_duration_statement",
    "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "log_duration",
    "query": "query_result(pg_settings_log_duration{service_name=~\"$service\"})"
   },
   {
    "name": "log_lock_waits",
    "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service\"})"
   },
   {
    "name": "max_wal_senders",
    "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service\"})"
   },
   {
    "name": "max_wal_size",
    "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "min_wal_size",
    "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "wal_compression",
    "query": "query_result(pg_settings_wal_compression{service_name=~\"$service\"})"
   },
   {
    "name": "max_worker_processes",
    "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service\"})"
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service\"})"
   },
   {
    "name": "max_parallel_workers",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_work_mem",
    "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service\"})"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$service</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1><br>"
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "description": "Reports whether PMM Server can connect to the PostgreSQL instance.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_up{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 5 },
   "content": "<h4><b><font color=#e68a00><center><a href=\"/graph/d/qyzrQGHmk/system-overview?var-host=$host\" target=\"_blank\">$host</a></center></font></b></h4>\n\n\n"
  },
  {
   "title": "Version",
   "type": "text",
   "description": "The version of the PostgreSQL instance.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "content": "<h3><b><font color=#e68a00><center>$version</center></font></b></h3>"
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "description": "The maximum number of client connections allowed.  Change this value with care as there are some memory resources that are allocated on a per-client basis, so setting max_connections higher will generally increase overall PostgreSQL memory usage.",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_max_connections{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_max_connections{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[5m]) "
    }
   ]
  },
  {
   "title": "Disk-Page Buffers",
   "type": "singlestat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Size for each Sort",
   "type": "singlestat",
   "description": "The parameter work_mem defines the amount of memory assigned for internal sort operations and hash tables before writing to temporary disk files.  The default is 4MB.",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Cache Size",
   "type": "singlestat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Autovacuum",
   "type": "singlestat",
   "description": "Whether autovacuum process is enabled or not.  Generally the solution is to vacuum more often, not less.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\",datname=~\"$db\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\",datname=~\"$db\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\",datname=~\"$db\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\",datname=~\"$db\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_count{service_name=~\"$service\",datname=~\"$db\",state='active'}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\",datname=~\"$db\",state='active'}[5m])",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "max_over_time(pg_settings_max_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{service_name=~\"$service\"}[5m])",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  { "title": "Tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$host\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$host\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{datname=~\"$db\",service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{datname=~\"$db\",service_name=~\"$service\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=~\"$db\",service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",service_name=~\"$service\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{datname=~\"$db\",service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{datname=~\"$db\",service_name=~\"$service\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{datname=~\"$db\",service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "Tuples Changes by Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Temp Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Number of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Size of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Conflicts & Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$db\",service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{datname=~\"$db\",service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$db\",service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{datname=~\"$db\",service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "max_over_time(pg_locks_count{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or\nmax_over_time(pg_locks_count{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Buffers & Blocks Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*\"}) by (datname) + \nsum(pg_stat_database_blks_read{datname=~\"$db\",service_name=~\"$service\",datname!~\"template.*\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[5m])",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[5m])",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Settings",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 84 },
     "content": "<table style=\"width:100%; border: 2px solid grey;\">\n  <tr><td></td><td></td><td></td><td></td></tr>\n  <tr><td> The maximum number of concurrent connections </td><td>${max_connections}</td><td> Shared memory buffers (bytes) </td><td>${shared_buffers}</td></tr>\n  <tr><td> The maximum memory to be used for query workspaces (bytes)</td><td>${work_mem}</td><td> The number of disk-page buffers in shared memory for WAL (bytes)</td><td>${wal_buffers}</td></tr>\n  <tr><td> The number of pages per write ahead log segment (bytes) </td><td>${wal_segment_size}</td><td>The maximum memory to be used for query workspaces (bytes)</td><td>${maintenance_work_mem}</td></tr>\n  <tr><td> The block size in the write ahead log </td><td>${block_size}</td><td>The maximum distance in log segments between automatic WAL checkpoints</td><td>${checkpoint_segments}</td></tr>\n  <tr><td> Time spent flushing dirty buffers during checkpoint, as fraction of checkpoint interval </td><td>${checkpoint_timeout}</td><td>The maximum number of simultaneously running WAL sender processes</td><td>${max_wal_senders}</td></tr>\n  <tr><td> The minimum size to shrink the WAL to (bytes)</td><td>${min_wal_size}</td><td>The WAL size that triggers a checkpoint (bytes)</td><td>${max_wal_size}</td></tr>\n  <tr><td> Compresses full-page writes written in WAL file </td><td>${wal_compression}</td><td>Maximum number of concurrent worker processes</td><td>${max_worker_processes}</td></tr>\n  <tr><td> The maximum number of parallel processes per executor node </td><td>${max_parallel_workers_per_gather}</td><td>The maximum number of parallel processes per executor node</td><td>${max_parallel_workers}</td></tr>\n  <tr><td> The default statistics target </td><td>${default_statistics_target}</td><td>The planner's estimate of the cost of a sequentially fetched disk page </td><td>${seq_page_cost}</td></tr>\n  <tr><td> The planner's estimate of the cost of a nonsequentially fetched disk page </td><td>${random_page_cost}</td><td>The planner's assumption about the size of the disk cache</td><td>${effective_cache_size}</td></tr>\n  <tr><td> Number of simultaneous requests that can be handled efficiently by the disk subsystem </td><td>${effective_io_concurrency}</td><td>Forces synchronization of updates to disk </td><td>${fsync}</td></tr>\n  <tr><td> Starts the autovacuum subprocess </td><td>${autovacuum}</td><td>Number of tuple inserts, updates, or deletes prior to analyze as a fraction of reltuples</td><td>${autovacuum_analyze_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple inserts, updates, or deletes prior to analyze </td><td>${autovacuum_analyze_threshold}</td><td>Number of tuple updates or deletes prior to vacuum as a fraction of reltuples</td><td>${autovacuum_vacuum_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple updates or deletes prior to vacuum </td><td>${autovacuum_vacuum_threshold}</td><td>Vacuum cost amount available before napping, for autovacuum </td><td>${autovacuum_vacuum_cost_limit}</td></tr>\n  <tr><td> Vacuum cost delay in milliseconds, for autovacuum (seconds) </td><td>${autovacuum_vacuum_cost_delay}</td><td> The maximum number of simultaneously running autovacuum worker processes </td><td>${autovacuum_max_workers}</td></tr>\n  <tr><td> Time to sleep between autovacuum runs (seconds) </td><td>${autovacuum_naptime}</td><td>Age at which to autovacuum a table to prevent transaction ID wraparound </td><td>${autovacuum_freeze_max_age}</td></tr>\n  <tr><td> The maximum memory to be used by each autovacuum worker process (bytes)</td><td>${autovacuum_work_mem}</td><td>Multixact age at which to autovacuum a table to prevent multixact wraparound</td><td>${autovacuum_multixact_freeze_max_age}</td></tr>\n  <tr><td> Start a subprocess to capture stderr output and/or csvlogs into log files </td><td>${logging_collector}</td><td>Sets the minimum execution time above which statements will be logged (seconds) </td><td>${log_min_duration_statement}</td></tr>\n  <tr><td> Logs the duration of each completed SQL statement </td><td>${log_duration}</td><td>Logs long lock waits </td><td>${log_lock_waits}</td></tr>\n  <tr><td></td><td></td><td></td><td></td></tr>\n</table>\n\n"
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 88 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(node_time_seconds{node_name=~\"$host\"} - node_boot_time_seconds{node_name=~\"$host\"}) or (time() - node_boot_time_seconds{node_name=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Virtual CPUs",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 88 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(count(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{node_name=~\"$host\"} or up * 0)"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 88 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg_over_time(node_load1{node_name=~\"$host\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 88 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "singlestat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 88 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(node_memory_MemAvailable_bytes{node_name=~\"$host\"} or (node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\"} * 100"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "singlestat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 88 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}+node_memory_SwapTotal_bytes{node_name=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "singlestat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 88 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(avg(node_filesystem_size_bytes{node_name=~\"$host\",fstype=~\"(ext.|xfs|vfat)\"}) without (mountpoint)) without (device,fstype)"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "singlestat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 88 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(node_filesystem_free_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "(avg_over_time(node_procs_running{node_name=~\"$host\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})) or (avg_over_time(node_procs_running{node_name=~\"$host\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pgpgin{node_name=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$host\"}[5m]) * 1024",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "(rate(node_vmstat_pgpgout{node_name=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$host\"}[5m]) * 1024)",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "(rate(node_vmstat_pgpgin{node_name=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$host\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$host\"}[5m]) * 1024)",
       "legendFormat": "Total"
      },
      {
       "expr": "rate(node_vmstat_pswpin{node_name=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "rate(node_vmstat_pswpout{node_name=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_receive_bytes_total{node_name=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$host\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$host\"}[5m])) ",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_transmit_bytes_total{node_name=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$host\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}