{
 "title": "PostgreSQL Services Compare",
 "tags": [
  "Percona",
  "PostgreSQL_Compare"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "work_mem",
    "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service\"})"
   },
   { "name": "host", "label": "Host", "query": "label_values(pg_up,node_name)" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(pg_up{node_name=~\"$host\"}, service_name)"
   },
   {
    "name": "max_connections",
    "query": "query_result(pg_settings_max_connections{service_name=~\"$service\"})"
   },
   {
    "name": "shared_buffers",
    "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "wal_buffers",
    "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "wal_segment_size",
    "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "maintenance_work_mem",
    "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "block_size",
    "query": "query_result(pg_settings_block_size{service_name=~\"$service\"})"
   },
   {
    "name": "checkpoint_segments",
    "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service\"})"
   },
   {
    "name": "checkpoint_timeout",
    "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "default_statistics_target",
    "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service\"})"
   },
   {
    "name": "seq_page_cost",
    "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service\"})"
   },
   {
    "name": "random_page_cost",
    "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service\"})"
   },
   {
    "name": "effective_cache_size",
    "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "effective_io_concurrency",
    "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service\"})"
   },
   {
    "name": "fsync",
    "query": "query_result(pg_settings_fsync{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum",
    "query": "query_result(pg_settings_autovacuum{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_max_workers",
    "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_naptime",
    "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service\"})"
   },
   {
    "name": "logging_collector",
    "query": "query_result(pg_settings_logging_collector{service_name=~\"$service\"})"
   },
   {
    "name": "log_min_duration_statement",
    "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service\"})"
   },
   {
    "name": "log_duration",
    "query": "query_result(pg_settings_log_duration{service_name=~\"$service\"})"
   },
   {
    "name": "log_lock_waits",
    "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service\"})"
   },
   {
    "name": "max_wal_senders",
    "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service\"})"
   },
   {
    "name": "max_wal_size",
    "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "min_wal_size",
    "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "wal_compression",
    "query": "query_result(pg_settings_wal_compression{service_name=~\"$service\"})"
   },
   {
    "name": "max_worker_processes",
    "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service\"})"
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service\"})"
   },
   {
    "name": "max_parallel_workers",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_work_mem",
    "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service\"})"
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service\"})"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "content": "<h1><i><font color=#5991A7><b><center>Overview</center></b></font></i></h1>"
  },
  {
   "title": "$service - Service Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "repeat": "service",
   "targets": [
    {
     "expr": "pg_static{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Service Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "pg_static{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Service Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "pg_static{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Shared Buffers",
   "type": "singlestat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "repeat": "service",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[5m]) "
    }
   ]
  },
  {
   "title": "$service - Shared Buffers",
   "type": "singlestat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[5m]) "
    }
   ]
  },
  {
   "title": "$service - Shared Buffers",
   "type": "singlestat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service\"}[5m]) "
    }
   ]
  },
  {
   "title": "$service - Disk-Page Buffers",
   "type": "singlestat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 },
   "repeat": "service",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Disk-Page Buffers",
   "type": "singlestat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Disk-Page Buffers",
   "type": "singlestat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Memory Size for each Sort",
   "type": "singlestat",
   "description": "The parameter work_mem defines the amount of memory assigned for internal sort operations and hash tables before writing to temporary disk files.  The default is 4MB.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "repeat": "service",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Memory Size for each Sort",
   "type": "singlestat",
   "description": "The parameter work_mem defines the amount of memory assigned for internal sort operations and hash tables before writing to temporary disk files.  The default is 4MB.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Memory Size for each Sort",
   "type": "singlestat",
   "description": "The parameter work_mem defines the amount of memory assigned for internal sort operations and hash tables before writing to temporary disk files.  The default is 4MB.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Disk Cache Size",
   "type": "singlestat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 16 },
   "repeat": "service",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Disk Cache Size",
   "type": "singlestat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Disk Cache Size",
   "type": "singlestat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Autovacuum",
   "type": "singlestat",
   "description": "Whether autovacuum process is enabled or not.  Generally the solution is to vacuum more often, not less.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Autovacuum",
   "type": "singlestat",
   "description": "Whether autovacuum process is enabled or not.  Generally the solution is to vacuum more often, not less.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "$service - Autovacuum",
   "type": "singlestat",
   "description": "Whether autovacuum process is enabled or not.  Generally the solution is to vacuum more often, not less.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[$interval]) or max_over_time(pg_settings_autovacuum{service_name=~\"$service\"}[5m])"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "<h1><i><font color=#5991A7><b><center>Connections</center></b></font></i></h1>"
  },
  {
   "title": "$service - PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$service - PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$service - PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$service - Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_count{service_name=~\"$service\",state='active'}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\",state='active'}[5m])",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "max_over_time(pg_settings_max_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{service_name=~\"$service\"}[5m])",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  {
   "title": "$service - Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_count{service_name=~\"$service\",state='active'}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\",state='active'}[5m])",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "max_over_time(pg_settings_max_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{service_name=~\"$service\"}[5m])",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  {
   "title": "$service - Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_count{service_name=~\"$service\",state='active'}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service\",state='active'}[5m])",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "max_over_time(pg_settings_max_connections{service_name=~\"$service\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{service_name=~\"$service\"}[5m])",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "content": "<h1><i><font color=#5991A7><b><center>Tuples</center></b></font></i></h1>"
  },
  {
   "title": "$service - Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "$service - Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "$service - Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "$service - Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "$service - Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "$service - Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "$service - Tuples Changes by Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  {
   "title": "$service - Tuples Changes by Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  {
   "title": "$service - Tuples Changes by Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "content": "<h1><i><font color=#5991A7><b><center>Transactions</center></b></font></i></h1>"
  },
  {
   "title": "$service - Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "$service - Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "$service - Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "$service - Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "repeat": "service",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service - Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service - Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "content": "<h1><i><font color=#5991A7><b><center>Temp Files</center></b></font></i></h1>"
  },
  {
   "title": "$service - Number of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$service - Number of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$service - Number of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$service - Size of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "repeat": "service",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$service - Size of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$service - Size of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 105 },
   "content": "<h1><i><font color=#5991A7><b><center>Conflicts & Locks</center></b></font></i></h1>"
  },
  {
   "title": "$service - Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{service_name=~\"$service\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{service_name=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "max_over_time(pg_locks_count{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or\nmax_over_time(pg_locks_count{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "max_over_time(pg_locks_count{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or\nmax_over_time(pg_locks_count{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "max_over_time(pg_locks_count{service_name=~\"$service\",datname!~\"template.*\"}[$interval]) or\nmax_over_time(pg_locks_count{service_name=~\"$service\",datname!~\"template.*\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 124 },
   "content": "<h1><i><font color=#5991A7><b><center>Buffers & Blocks Operations</center></b></font></i></h1>"
  },
  {
   "title": "$service - Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "repeat": "service",
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "$service - Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 126 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "$service - Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 126 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{service_name=~\"$service\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "$service - Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 134 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$service - Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 143 },
   "content": "<h1><i><font color=#5991A7><b><center>Others</center></b></font></i></h1>"
  },
  {
   "title": "$service - Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "$service - Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "$service - Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "$service - Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 153 },
   "repeat": "service",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{service_name=~\"$service\",datname!~\"template.*\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{service_name=~\"$service\",datname!~\"template.*\"}) by (datname) + \nsum(pg_stat_database_blks_read{service_name=~\"$service\",datname!~\"template.*\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "$service - Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 153 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{service_name=~\"$service\",datname!~\"template.*\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{service_name=~\"$service\",datname!~\"template.*\"}) by (datname) + \nsum(pg_stat_database_blks_read{service_name=~\"$service\",datname!~\"template.*\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "$service - Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 153 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{service_name=~\"$service\",datname!~\"template.*\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{service_name=~\"$service\",datname!~\"template.*\"}) by (datname) + \nsum(pg_stat_database_blks_read{service_name=~\"$service\",datname!~\"template.*\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "$service - Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 161 },
   "repeat": "service",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[5m])",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[5m])",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "$service - Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 161 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[5m])",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[5m])",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "$service - Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 161 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service'}[5m])",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service'}[5m])",
     "legendFormat": "Written Files to disk"
    }
   ]
  }
 ]
}