{
 "title": "Processes Overview",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"},node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of PIDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "max_over_time(node_processes_pids{node_name=~\"$host\"}[$interval]) or max_over_time(node_processes_pids{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Max PIDs Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(max_over_time(node_processes_pids{node_name=~\"$host\"}[$interval]) or \nmax_over_time(node_processes_pids{node_name=~\"$host\"}[5m]))/\n(max_over_time(node_processes_max_processes{node_name=~\"$host\"}[$interval]) or \nmax_over_time(node_processes_max_processes{node_name=~\"$host\"}[5m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "max_over_time(node_processes_threads{node_name=~\"$host\"}[$interval]) or max_over_time(node_processes_threads{node_name=~\"$host\"}[5m]) ",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Max Threads Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(max_over_time(node_processes_threads{node_name=~\"$host\"}[$interval]) or \nmax_over_time(node_processes_threads{node_name=~\"$host\"}[$interval]))/\n(max_over_time(node_processes_max_threads{node_name=~\"$host\"}[$interval]) or \nmax_over_time(node_processes_max_threads{node_name=~\"$host\"}[5m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Runnable Processes",
   "type": "graph",
   "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(node_procs_running{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_running{node_name=~\"$host\"}[5m]) ",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_procs_running{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_running{node_name=~\"$host\"}[5m]) )",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Blocked Processes Waiting for I/O ",
   "type": "graph",
   "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or max_over_time(node_procs_blocked{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Sleeping Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m])",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m])",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Disk Sleep Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m])",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Stopped Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Zombie Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m])",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Dead Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m])",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg(max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{node_name=~\"$host\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{node_name=~\"$host\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "States of Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m])",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m])",
       "legendFormat": "Running"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m])",
       "legendFormat": "Disk sleep"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m])",
       "legendFormat": "Stopped"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m])",
       "legendFormat": "Zombie"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m])",
       "legendFormat": "Dead"
      }
     ]
    },
    {
     "title": "Number of PIDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      },
      {
       "expr": "node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max PIDs limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}/node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    },
    {
     "title": "Number of Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max threads limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}/node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{node_name=~\"$host\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{node_name=~\"$host\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "States of Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m])",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m])",
       "legendFormat": "Running"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m])",
       "legendFormat": "Disk sleep"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m])",
       "legendFormat": "Stopped"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m])",
       "legendFormat": "Zombie"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m])",
       "legendFormat": "Dead"
      }
     ]
    },
    {
     "title": "Number of PIDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      },
      {
       "expr": "node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max PIDs limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}/node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    },
    {
     "title": "Number of Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max threads limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}/node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{node_name=~\"$host\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{node_name=~\"$host\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "States of Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m])",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m])",
       "legendFormat": "Running"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m])",
       "legendFormat": "Disk sleep"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m])",
       "legendFormat": "Stopped"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m])",
       "legendFormat": "Zombie"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m])",
       "legendFormat": "Dead"
      }
     ]
    },
    {
     "title": "Number of PIDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      },
      {
       "expr": "node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max PIDs limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}/node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    },
    {
     "title": "Number of Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max threads limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}/node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{node_name=~\"$host\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{node_name=~\"$host\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "States of Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m])",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m])",
       "legendFormat": "Running"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m])",
       "legendFormat": "Disk sleep"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m])",
       "legendFormat": "Stopped"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m])",
       "legendFormat": "Zombie"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m])",
       "legendFormat": "Dead"
      }
     ]
    },
    {
     "title": "Number of PIDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      },
      {
       "expr": "node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max PIDs limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}/node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    },
    {
     "title": "Number of Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max threads limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}/node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "description": "**Processes**\n\nThe Processes graph shows how many processes/threads are either in the kernel run queue (runnable state) or in the blocked queue (waiting for I/O).  When the number of process in the runnable state is constantly higher than the number of CPU cores available, the load is CPU bound.  When the number of process blocked waiting for I/O is large, the load is disk bound.  The running average of the sum of these two quantities is the basis of the loadavg metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{node_name=~\"$host\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{node_name=~\"$host\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "States of Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"S\"}[5m])",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"R\"}[5m])",
       "legendFormat": "Running"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"D\"}[5m])",
       "legendFormat": "Disk sleep"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"T\"}[5m])",
       "legendFormat": "Stopped"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"Z\"}[5m])",
       "legendFormat": "Zombie"
      },
      {
       "expr": "max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[$interval]) or max_over_time(node_processes_state{node_name=~\"$host\",state=\"X\"}[5m])",
       "legendFormat": "Dead"
      }
     ]
    },
    {
     "title": "Number of PIDs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      },
      {
       "expr": "node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max PIDs limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_pids{node_name=\"$host\"}/node_processes_max_processes{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    },
    {
     "title": "Number of Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Percentage of max threads limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_processes_threads{node_name=\"$host\"}/node_processes_max_threads{node_name=\"$host\"}",
       "legendFormat": "PIDs"
      }
     ]
    }
   ]
  }
 ]
}