{
 "title": "Prometheus Alerts",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"critical\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"warning\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"info\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "None",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"none\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Firing",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "ALERTS{alertstate='firing',instance=~\"$host\"} > 0"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "host" },
  {
   "title": "Active MySQL Connections $host",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighMySQLConnections\",instance=~\"$host\",job=\"mysql\",severity=\"critical\"} or\n(1-absent(ALERTS{alertname=\"HighMySQLConnections\",instance=~\"$host\",job=\"mysql\",severity=\"critical\"}))"
    }
   ]
  },
  {
   "title": "Job/Jobs Down on $host",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{alertname=\"InstanceDown\",instance=~\"$host\",severity=\"critical\"} or\n(1-absent(ALERTS{alertname=\"InstanceDown\",instance=~\"$host\",severity=\"critical\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Medium CPU Usage $host",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{alertname=\"MediumCPUUsage\",instance=~\"$host\",severity=\"warning\"} or\n(1-absent(ALERTS{alertname=\"MediumCPUUsage\",instance=~\"$host\",severity=\"warning\"}))"
    }
   ]
  },
  {
   "title": "High CPU Usage$host",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighCPUUsage\",instance=~\"$host\",severity=\"critical\"} or\n(1-absent(ALERTS{alertname=\"HighCPUUsage\",instance=~\"$host\",severity=\"critical\"}))"
    }
   ]
  }
 ]
}