{
 "title": "Prometheus",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "pmmhost", "query": "pmm-server" },
   {
    "name": "scrapingInterval",
    "query": "label_values({__name__=~\"node_time_seconds\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>PMM Server</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  { "title": "Prometheus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "description": "CPU Usage by Prometheus Process Only",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=\"prometheus\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{job=\"prometheus\"}[5m])) by ()) / count(node_cpu_seconds_total{mode=\"user\", node_name=\"pmm-server\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Memory Allocated and In use by Prometheus Process Only",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*sum(go_memstats_alloc_bytes{job=\"prometheus\"}+go_memstats_stack_inuse_bytes{job=\"prometheus\"}) by () / \nsum(node_memory_MemTotal_bytes{node_name=\"pmm-server\"}) by ()"
    }
   ]
  },
  {
   "title": "Active Series",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "series" }
   ]
  },
  {
   "title": "Scrapes Performed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_interval_length_seconds_count[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Samples Ingested",
   "type": "singlestat",
   "description": "Samples Ingested per second through scraping activity",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[$interval]) or irate(prometheus_tsdb_head_samples_appended_total[5m])"
    }
   ]
  },
  {
   "title": "Capacity Usage",
   "type": "singlestat",
   "description": "Estimated usage of Memory Resources based on current Ingest rate",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(prometheus_tsdb_head_samples_appended_total[15m])) by () *10800*3) / ((sum(node_memory_MemTotal_bytes{node_name=\"pmm-server\"}) by ()-419430400)*0.35)*100"
    }
   ]
  },
  {
   "title": "Time before run out of space",
   "type": "singlestat",
   "description": "Estimated time of Disk usage based on trend",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{node_name=\"pmm-server\",mountpoint=~\"/srv|/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})/\nclamp_min(sum(node_filesystem_free_bytes{node_name=\"pmm-server\",mountpoint=~\"/srv|/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} - \npredict_linear(node_filesystem_free_bytes{node_name=\"pmm-server\", mountpoint=~\"/srv|/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[1h], 1 * 3600)),0)\n"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (rate(process_cpu_seconds_total{job=\"prometheus\"}[$interval]) or irate(process_cpu_seconds_total{job=\"prometheus\"}[5m]))",
       "legendFormat": "CPU Cores Used"
      },
      {
       "expr": "count(node_cpu_seconds_total{mode=\"user\", node_name=\"pmm-server\"})",
       "legendFormat": "CPU Cores Total"
      },
      {
       "expr": "count(node_cpu_seconds_total{mode=\"user\", node_name=\"pmm-server\"})*0.75",
       "legendFormat": "Recommended Limit"
      }
     ]
    },
    {
     "title": "Prometheus Process Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}+go_memstats_stack_inuse_bytes{job=\"prometheus\"}",
       "legendFormat": "Go Memory Allocated and In Use"
      },
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=\"pmm-server\"})",
       "legendFormat": "Total System Memory"
      }
     ]
    },
    {
     "title": "Disk Space Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (node_filesystem_size_bytes{node_name=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_size_bytes{node_name=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})",
       "legendFormat": "Total Disk Space"
      },
      {
       "expr": "avg by (node_name) ((node_filesystem_size_bytes{node_name=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_size_bytes{node_name=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} ) - \n(node_filesystem_free_bytes{node_name=\"pmm-server\",mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_free_bytes{node_name=\"pmm-server\",mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}))",
       "legendFormat": "Used Disk Space"
      },
      {
       "expr": "avg by (node_name) (node_filesystem_free_bytes{node_name=\"pmm-server\", mountpoint=\"/srv\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} or \nnode_filesystem_free_bytes{node_name=\"pmm-server\", mountpoint=\"/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})",
       "legendFormat": "Free Disk Space"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage (TSDB) Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Chunk Time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_compaction_chunk_range_seconds_sum[6h])/rate(prometheus_tsdb_compaction_chunk_range_seconds_count[6h]))"
      }
     ]
    },
    {
     "title": "Samples Per Chunk",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_compaction_chunk_samples_sum[6h])/rate(prometheus_tsdb_compaction_chunk_samples_count[6h]))",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "Avg Chunk Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 10, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[6h])/rate(prometheus_tsdb_compaction_chunk_size_bytes_count[6h]))",
       "legendFormat": "Series"
      }
     ]
    },
    {
     "title": "Bytes/Sample",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 15, "y": 9 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) ((rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[6h])/rate(prometheus_tsdb_compaction_chunk_size_bytes_count[6h]))/\n(rate(prometheus_tsdb_compaction_chunk_samples_sum[6h])/rate(prometheus_tsdb_compaction_chunk_samples_count[6h])))",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "WAL Fsync Time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_wal_fsync_duration_seconds_sum[6h])/rate(prometheus_tsdb_wal_fsync_duration_seconds_count[6h]))"
      }
     ]
    },
    {
     "title": "Active Data blocks",
     "type": "singlestat",
     "description": "Number of currently loaded data blocks",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (prometheus_tsdb_blocks_loaded)"
      }
     ]
    },
    {
     "title": "Head Block Retention",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (prometheus_tsdb_head_max_time - prometheus_tsdb_head_min_time)"
      }
     ]
    },
    {
     "title": "Head Block Size",
     "type": "singlestat",
     "description": "Head Block Size (Estimated)",
     "gridPos": { "h": 2, "w": 5, "x": 10, "y": 11 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum[6h])/\nrate(prometheus_tsdb_compaction_chunk_size_bytes_count[6h])*\n(max_over_time(prometheus_tsdb_head_chunks[$interval]) or max_over_time(prometheus_tsdb_head_chunks[5m])))",
       "legendFormat": "series"
      }
     ]
    },
    {
     "title": "Head GC Latency",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 15, "y": 11 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_head_gc_duration_seconds_sum[6h])/rate(prometheus_tsdb_head_gc_duration_seconds_count[6h]))"
      }
     ]
    },
    {
     "title": "Avg Compaction Time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (rate(prometheus_tsdb_compaction_duration_seconds_sum[6h])/rate(prometheus_tsdb_compaction_duration_seconds_count[6h]))"
      }
     ]
    },
    {
     "title": "Active Data Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(prometheus_tsdb_blocks_loaded[$interval])",
       "legendFormat": "Active (Loaded) Data Blocks"
      }
     ]
    },
    {
     "title": "Head Block",
     "type": "graph",
     "description": "The Head Block is kept in memory. Older blocks are accessed through mmap().\n\nThis eliminates the need to configure cache separately, but also means you need to allocate plenty of memory for OS Cache if you want to query data older than fits in the Head Block.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(prometheus_tsdb_head_chunks[$interval]) ",
       "legendFormat": "Chunks"
      },
      {
       "expr": "max_over_time(prometheus_tsdb_head_series[$interval]) ",
       "legendFormat": "Series "
      },
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum[6h])/rate(prometheus_tsdb_compaction_chunk_size_count[6h])*(max_over_time(prometheus_tsdb_head_chunks[$interval]) )",
       "legendFormat": "Size (Estimated)"
      }
     ]
    },
    {
     "title": "Chunk Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total[$interval]) or irate(prometheus_tsdb_head_chunks_created_total[5m])",
       "legendFormat": "Chunks Created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total[$interval]) or irate(prometheus_tsdb_head_chunks_removed_total[5m])",
       "legendFormat": "Chunks Removed"
      }
     ]
    },
    {
     "title": "Reload block data from disk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_tsdb_reloads_total[$interval]) - rate(prometheus_tsdb_reloads_failures_total[$interval])) or (irate(prometheus_tsdb_reloads_total[5m]) - irate(prometheus_tsdb_reloads_failures_total[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total[$interval]) or irate(prometheus_tsdb_reloads_failures_total[5m])",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_total[$interval])",
       "legendFormat": "Compactions Performed"
      },
      {
       "expr": "increase(prometheus_tsdb_compactions_failed_total[$interval]) ",
       "legendFormat": "Compactions Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_interval_length_seconds_count[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Scrapes Performed"
      },
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total[$interval]) or irate(prometheus_tsdb_head_samples_appended_total[5m])",
       "legendFormat": "Samples appended in the head block"
      }
     ]
    },
    {
     "title": "Prometheus Targets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "count(up)", "legendFormat": "Targets Configured" },
      {
       "expr": "sum(avg_over_time(up[$interval])) or  sum(avg_over_time(up[5m]))",
       "legendFormat": "Avg Succesfully Scraped Targets"
      },
      {
       "expr": "sum(min_over_time(up[$interval])) or  sum(min_over_time(up[5m]))",
       "legendFormat": "Min Successfully Scraped Targets"
      }
     ]
    },
    {
     "title": "Scraped Target by Job",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (label_replace(\nsum(avg_over_time(up{service_type=\"mysql\"}[$interval])) by (job,service_name) or \nsum(avg_over_time(up{service_type=\"mysql\"}[5m])) by (job,service_name),\n\"job\", \"$2\", \"job\", \"mysqld_(.*)_(.*)\"))",
       "legendFormat": "mysqld_exporter_{{job}}"
      },
      {
       "expr": "sum by (job) (label_replace(sum(avg_over_time(up{service_type=\"mongodb\"}[$interval])) by (job,service_name) or sum(avg_over_time(up{service_type=\"mongodb\"}[5m])) by (job,service_name),\"job\", \"$2\", \"job\", \"mongodb_(.*)_(.*)\"))",
       "legendFormat": "mongodb_exporter_{{job}}"
      },
      {
       "expr": "sum by (job) (label_replace(sum(avg_over_time(up{service_type=\"postgresql\"}[$interval])) by (job,service_name) or sum(avg_over_time(up{service_type=\"postgresql\"}[5m])) by (job,service_name),\"job\", \"$2\", \"job\", \"postgres_(.*)_(.*)\"))",
       "legendFormat": "postgresql_exporter_{{job}}"
      },
      {
       "expr": "sum by (job) (label_replace(sum(avg_over_time(up{service_type=\"proxysql\"}[$interval])) by (job,service_name) or sum(avg_over_time(up{service_type=\"proxysql\"}[5m])) by (job,service_name),\"job\", \"$2\", \"job\", \"proxysql_(.*)_(.*)\"))",
       "legendFormat": "proxysql_exporter_{{job}}"
      },
      {
       "expr": "sum by (job) (label_replace(sum(avg_over_time(up{instance=~\"127\\\\.0\\\\.0\\\\.1.*\"}[$interval])) by (job,service_name) or sum(avg_over_time(up{instance=~\"127\\\\.0\\\\.0\\\\.1.*\"}[5m])) by (job,service_name),\"job\", \"$2\", \"job\", \"rds_exporter_(.*)_(.*)\"))",
       "legendFormat": "rds_exporter_{{job}}"
      },
      {
       "expr": "sum(avg_over_time(up{instance=\"pmm-server\"}[$interval])) by (job) or sum(avg_over_time(up{instance=\"pmm-server\"}[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Job",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace( \n(avg(avg_over_time(scrape_duration_seconds{service_type=\"mysql\"}[$interval])) by (job,service_name) or \navg(avg_over_time(scrape_duration_seconds{service_type=\"mysql\"}[5m])) by (job,service_name)), \n\"job\", \"$2\", \"job\", \"mysqld_(.*)_(.*)\")",
       "legendFormat": "{{service_name}} - mysqld_exporter - {{job}}"
      },
      {
       "expr": "label_replace( (avg(avg_over_time(scrape_duration_seconds{service_type=\"rds\"}[$interval])) by (job,service_name) or avg(avg_over_time(scrape_duration_seconds{service_type=\"rds\"}[5m])) by (job,service_name)), \"job\", \"$2\", \"job\", \"rds_(.*)_(.*)\")",
       "legendFormat": "{{service_name}} - rds_exporter - {{job}}"
      },
      {
       "expr": "label_replace( (avg(avg_over_time(scrape_duration_seconds{service_type=\"proxysql\"}[$interval])) by (job,service_name) or avg(avg_over_time(scrape_duration_seconds{service_type=\"proxysql\"}[5m])) by (job,service_name)), \"job\", \"$2\", \"job\", \"proxysql_(.*)_(.*)\")",
       "legendFormat": "{{service_name}} - proxysql_exporter - {{job}}"
      },
      {
       "expr": "label_replace( (avg(avg_over_time(scrape_duration_seconds{service_type=\"postgresql\"}[$interval])) by (job,service_name) or avg(avg_over_time(scrape_duration_seconds{service_type=\"postgresql\"}[5m])) by (job,service_name)), \"job\", \"$2\", \"job\", \"postgres_(.*)_(.*)\")",
       "legendFormat": "{{service_name}} - postgres_exporter - {{job}}"
      },
      {
       "expr": "label_replace( (avg(avg_over_time(scrape_duration_seconds{service_type=\"mongodb\"}[$interval])) by (job,service_name) or avg(avg_over_time(scrape_duration_seconds{service_type=\"mongodb\"}[5m])) by (job,service_name)), \"job\", \"$2\", \"job\", \"mongodb_(.*)_(.*)\")",
       "legendFormat": "{{service_name}} - mongodb_exporter - {{job}}"
      },
      {
       "expr": "label_replace( (avg(avg_over_time(scrape_duration_seconds{agent_type=\"node_exporter\",instance!=\"pmm-server\"}[$interval])) by (job,node_name) or avg(avg_over_time(scrape_duration_seconds{agent_type=\"node_exporter\",instance!=\"pmm-server\"}[5m])) by (job,node_name)), \"job\", \"$2\", \"job\", \"node_(.*)_(.*)\")",
       "legendFormat": "{{node_name}} - node_exporter - {{job}}"
      },
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds{instance=\"pmm-server\"}[$interval])) by (job,service_name) or \navg(avg_over_time(scrape_duration_seconds{instance=\"pmm-server\"}[5m])) by (job,service_name)",
       "legendFormat": "pmm-server - {{job}}"
      }
     ]
    },
    {
     "title": "Scraped Target by Instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(up{instance!~\"pmm-server|127\\\\.0\\\\.0\\\\.1.*\",node_name!=\"pmm-server\"}[$interval])) by (node_name) or \nsum(avg_over_time(up{instance!~\"pmm-server|127\\\\.0\\\\.0\\\\.1.*\",node_name!=\"pmm-server\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "sum(\nsum(avg_over_time(up{node_name=\"pmm-server\"}[$interval])) by (node_name) or\nsum(avg_over_time(up{instance=~\"pmm-server|127\\\\.0\\\\.0\\\\.1.*\"}[$interval])) by (instance) or\nsum(avg_over_time(up{node_name=\"pmm-server\"}[5m])) by (node_name) or\nsum(avg_over_time(up{instance=~\"pmm-server|127\\\\.0\\\\.0\\\\.1.*\"}[5m])) by (instance)\n)",
       "legendFormat": "pmm-server"
      }
     ]
    },
    {
     "title": "Scrape Time by Instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds{instance!~\"pmm-server|127.0.0.1.*\",node_name!=\"pmm-server\"}[$interval])) by (node_name) or \navg(avg_over_time(scrape_duration_seconds{instance!~\"pmm-server|127.0.0.1.*\",node_name!=\"pmm-server\"}[5m])) by (node_name) ",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds{node_name=~\"pmm-server|127.0.0.1.*\"}[$interval]) or \navg_over_time(scrape_duration_seconds{instance=~\"pmm-server|127.0.0.1.*\"}[$interval])) or \navg(avg_over_time(scrape_duration_seconds{node_name=~\"pmm-server|127.0.0.1.*\"}[5m]) or \navg_over_time(scrape_duration_seconds{instance=~\"pmm-server|127.0.0.1.*\"}[5m]))",
       "legendFormat": "pmm-server"
      }
     ]
    },
    {
     "title": "Scrapes by Target Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[$interval]) or irate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "Rate of {{interval}} scrapes"
      }
     ]
    },
    {
     "title": "Scrape Frequency Versus Target",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_target_interval_length_seconds_sum[$interval]) / (rate(prometheus_target_interval_length_seconds_count[$interval]) > 0)) or (irate(prometheus_target_interval_length_seconds_sum[5m]) / (irate(prometheus_target_interval_length_seconds_count[5m]) > 0))",
       "legendFormat": "Actual  {{interval}} scrape interval  length"
      }
     ]
    },
    {
     "title": "Scraping Time Drift",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "clamp_min((time() - max by (node_name) (node_time_seconds)) - scalar(prometheus_target_interval_length_seconds{quantile=\"0.99\",interval=~\"$scrapingInterval\"}),0)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Prometheus Scrape Interval Variance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1s\",job=\"prometheus\",quantile=\"0.99\"}) by () - \nsum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/1",
       "legendFormat": "1sec  Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"5s\",job=\"prometheus\",quantile=\"0.99\"}) by () - \nsum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"5s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/5",
       "legendFormat": "5sec Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1m0s\",job=\"prometheus\",quantile=\"0.99\"}) by () - \nsum(prometheus_target_interval_length_seconds{instance=\"pmm-server\",interval=\"1m0s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/60",
       "legendFormat": "1min Target Interval Variance"
      }
     ]
    },
    {
     "title": "Slowest Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10,(\nlabel_join((max_over_time(scrape_duration_seconds{instance=\"pmm-server\"}[$interval]) or \nmax_over_time(scrape_duration_seconds{instance=\"pmm-server\"}[5m])), \"node_name\", \",\",\"instance\") or\nlabel_replace((max_over_time(scrape_duration_seconds{service_type=\"mysql\"}[$interval]) or \nmax_over_time(scrape_duration_seconds{service_type=\"mysql\"}[5m])),\"job\", \"mysqld_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace((max_over_time(scrape_duration_seconds{service_type=\"postgresql\"}[$interval]) or \nmax_over_time(scrape_duration_seconds{service_type=\"postgresql\"}[5m])),\"job\", \"postgres_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace((max_over_time(scrape_duration_seconds{service_type=\"mongodb\"}[$interval]) or max_over_time(scrape_duration_seconds{service_type=\"mongodb\"}[5m])),\"job\", \"mongodb_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace((max_over_time(scrape_duration_seconds{service_type=\"proxysql\"}[$interval]) or max_over_time(scrape_duration_seconds{service_type=\"proxysql\"}[5m])),\"job\", \"proxysql_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace(label_replace((max_over_time(scrape_duration_seconds{instance=~\"127\\\\.0\\\\.0\\\\.1.*\"}[$interval]) or \nmax_over_time(scrape_duration_seconds{instance=~\"127\\\\.0\\\\.0\\\\.1.*\"}[5m])),\"job\", \"rds_exporter_$2\", \"job\", \"rds_exporter_(.*)_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\")\n))",
       "legendFormat": "{{job}} at {{node_name}}"
      }
     ]
    },
    {
     "title": "Largest Samples Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,(label_join((max_over_time(scrape_samples_scraped{instance=\"pmm-server\"}[$interval]) or \nmax_over_time(scrape_samples_scraped{instance=\"pmm-server\"}[5m])), \"service_name\", \",\",\"instance\") or\nlabel_replace((max_over_time(scrape_samples_scraped{service_type=\"mysql\"}[$interval]) or \nmax_over_time(scrape_samples_scraped{service_type=\"mysql\"}[5m])),\"job\", \"mysqld_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace((max_over_time(scrape_samples_scraped{service_type=\"mongodb\"}[$interval]) or \nmax_over_time(scrape_samples_scraped{service_type=\"mongodb\"}[5m])),\"job\", \"mongodb_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace((max_over_time(scrape_samples_scraped{service_type=\"postgresql\"}[$interval]) or \nmax_over_time(scrape_samples_scraped{service_type=\"postgresql\"}[5m])),\"job\", \"postgresql_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace((max_over_time(scrape_samples_scraped{service_type=\"proxysql\"}[$interval]) or max_over_time(scrape_samples_scraped{service_type=\"proxysql\"}[5m])),\"job\", \"proxysql_exporter_$3\", \"job\", \"(.*)_agent_id_(.*)_(.*)\") or\nlabel_replace(label_replace((max_over_time(scrape_samples_scraped{instance=~\"127\\\\.0\\\\.0\\\\.1.*\"}[$interval]) or \nmax_over_time(scrape_samples_scraped{instance=~\"127\\\\.0\\\\.0\\\\.1.*\"}[5m])),\"job\", \"rds_exporter_$2\", \"job\", \"rds_exporter_(.*)_(.*)\"),\"service_name\",\"pmm-server\",\"\",\"\")\n))",
       "legendFormat": "{{job}} - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(prometheus_engine_queries[$interval]) or avg_over_time(prometheus_engine_queries[5m])",
       "legendFormat": "Avg Queries Active"
      },
      {
       "expr": "max_over_time(prometheus_engine_queries[$interval]) or max_over_time(prometheus_engine_queries[5m])",
       "legendFormat": "Max Queries Active"
      },
      {
       "expr": "prometheus_engine_queries_concurrent_max",
       "legendFormat": "Maximum Queries Permitted"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_count[$interval]) or irate(prometheus_engine_query_duration_seconds_count[$interval]) ",
       "legendFormat": "{{slice}} - Executed"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_engine_query_duration_seconds_sum[$interval])/(rate(prometheus_engine_query_duration_seconds_count[$interval]) > 0)) or (irate(prometheus_engine_query_duration_seconds_sum[$interval])/(irate(prometheus_engine_query_duration_seconds_count[$interval]) > 0))",
       "legendFormat": "{{slice}} - Avg Time"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum[$interval])",
       "legendFormat": "{{slice}} - Load"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests duration by Handler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum[$interval]) or \nirate(prometheus_http_request_duration_seconds_sum[5m])\n",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP Response Average Size by Handler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_response_size_bytes_sum[$interval]) or\nirate(prometheus_http_response_size_bytes_sum[5m])",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 metrics by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "topk(10, count({__name__=~\".+\"})  by (__name__))",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "Top 10 hosts by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "topk(10, sum by (node_name) (count({__name__=~\".+\",instance!=\"pmm-server\"})  by (node_name) or \nlabel_replace(\nlabel_join(count({__name__=~\".+\",instance=\"pmm-server\"})  by (instance,node_name), \"node_name\", \",\",\"instance\"),\n\"node_name\", \"pmm-server\", \"node_name\", \"pmm-server\")\n))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "clamp_max(avg by (instance) (sum by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=\"pmm-server\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or  (clamp_max(irate(node_cpu_seconds_total{node_name=\"pmm-server\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100"
      }
     ]
    },
    {
     "title": "Mem Avail",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 14 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=\"pmm-server\"} or (node_memory_MemFree_bytes{node_name=\"pmm-server\"} + node_memory_Buffers_bytes{node_name=\"pmm-server\"} + node_memory_Cached_bytes{node_name=\"pmm-server\"})) / node_memory_MemTotal_bytes{node_name=\"pmm-server\"} * 100)"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 14 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"pmm-server\"}[5m]) * 1024)"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgout{node_name=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"pmm-server\"}[5m]) * 1024)"
      }
     ]
    },
    {
     "title": "Network IO",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 14 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((sum(rate(node_network_receive_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[5m]))) + (sum(rate(node_network_transmit_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[5m]))))"
      }
     ]
    },
    {
     "title": "Sys Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) (node_time_seconds{node_name=\"pmm-server\"} - node_boot_time_seconds{node_name=\"pmm-server\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PMM Server Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
     "content": "<br><br> Please go to <a href='/graph/d/pmm-settings/pmm-settings'>PMM Settings page</a> to get Diagnostic data"
    }
   ]
  }
 ]
}