{
 "title": "Prometheus Exporter Status",
 "tags": [
  "Insight",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds|pg_exporter_scrapes_total\", node_name=\"$node_name\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{node_name=~\"$node_name\",job=~\"node_exporter_.*\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{node_name=~\"$node_name\",job=~\"node_exporter_.*\"}[5m])) by ()) / count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (node_name) (process_resident_memory_bytes{node_name=\"$node_name\",job=~\"node_exporter_.*\"})"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (node_name) (process_open_fds{node_name=\"$node_name\",job=~\"node_exporter_.*\"})"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "time() - avg by (node_name) (process_start_time_seconds{node_name=\"$node_name\",job=~\"node_exporter_.*\"})"
    }
   ]
  },
  {
   "title": "Collector Scrape Successful",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "avg by (node_name,collector) (min_over_time(node_scrape_collector_success{node_name=~\"$node_name\"}[$interval]) or \nmin_over_time(node_scrape_collector_success{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Collector Execution Time (Log Scale)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "avg by (node_name,collector) (avg_over_time(node_scrape_collector_duration_seconds{node_name=\"$node_name\"}[$interval]) or \navg_over_time(node_scrape_collector_duration_seconds{node_name=\"$node_name\"}[5m]))",
     "legendFormat": "{{collector}}"
    },
    {
     "expr": "sum(avg_over_time(node_scrape_collector_duration_seconds{node_name=\"$node_name\"}[$interval])) or \nsum(avg_over_time(node_scrape_collector_duration_seconds{node_name=\"$node_name\"}[5m]))",
     "legendFormat": "Total Load"
    }
   ]
  },
  {
   "title": "MySQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=\"$node_name\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(process_open_fds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter.*\"})"
      }
     ]
    },
    {
     "title": "Collector Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,collector,service_name) (avg_over_time(mysql_exporter_collector_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\"}[$interval]) or \navg_over_time(mysql_exporter_collector_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{collector}} - {{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (max_over_time(mysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_hr.*\"}[$interval]) or \nmax_over_time(mysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_hr.*\"}[5m]))",
       "legendFormat": "High Resolution - {{service_name}}"
      },
      {
       "expr": "avg by (node_name,service_name) (max_over_time(mysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_mr.*\"}[$interval]) or \nmax_over_time(mysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_mr.*\"}[5m]))",
       "legendFormat": "Medium Resolution {{service_name}}"
      },
      {
       "expr": "avg by (node_name,service_name) (max_over_time(mysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_lr.*\"}[$interval]) or \nmax_over_time(mysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_lr.*\"}[5m]))",
       "legendFormat": "Low Resolution - {{service_name}}"
      }
     ]
    },
    {
     "title": "Rate of Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (rate(mysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_hr.*\"}[$interval]) or \nirate(mysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_hr.*\"}[5m]))",
       "legendFormat": "High Resolution - {{service_name}}"
      },
      {
       "expr": "avg by (node_name,service_name) (rate(mysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_mr.*\"}[$interval]) or \nirate(mysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_mr.*\"}[5m]))",
       "legendFormat": "Medium Resolution - {{service_name}}"
      },
      {
       "expr": "avg by (node_name,service_name) (rate(mysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_lr.*\"}[$interval]) or \nirate(mysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_agent_id_.*_lr.*\"}[5m]))",
       "legendFormat": "Low Resolution - {{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (min_over_time(mysql_up{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_.*_hr.*\"}[$interval]) or \nmin_over_time(mysql_up{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mysqld_exporter_.*_hr.*\"}[5m]))",
       "legendFormat": "MySQL Up - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=\"$node_name\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_resident_memory_bytes{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 15 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 15 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"})"
      }
     ]
    },
    {
     "title": "MongoDB Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (avg_over_time(mongodb_exporter_last_scrape_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[$interval]) or\navg_over_time(mongodb_exporter_last_scrape_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[5m]))",
       "legendFormat": "Avg Scrape Time - {{service_name}}"
      }
     ]
    },
    {
     "title": "MongoDB Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (max_over_time(mongodb_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[$interval]) or \nmax_over_time(mongodb_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[5m]))",
       "legendFormat": "MongoDB Exporter Errors  - {{service_name}}"
      }
     ]
    },
    {
     "title": "Rate of Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (rate(mongodb_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[$interval]) or \nirate(mongodb_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[5m]))",
       "legendFormat": "Scrapes Rate  - {{service_name}}"
      }
     ]
    },
    {
     "title": "MongoDB up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,service_name) (min_over_time(mongodb_up{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[$interval]) or \nmin_over_time(mongodb_up{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"mongodb.*\"}[5m]))",
       "legendFormat": "MongoDB Up"
      }
     ]
    }
   ]
  },
  {
   "title": "ProxySQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[5m])) by ()) / count(node_cpu_seconds_total{mode=\"user\",node_name=\"$node_name\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_resident_memory_bytes{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 16 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"})"
      }
     ]
    },
    {
     "title": "ProxySQL Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (avg_over_time(proxysql_exporter_last_scrape_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[$interval]) or \navg_over_time(proxysql_exporter_last_scrape_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[5m]))",
       "legendFormat": "Avg Scrape Time  - {{service_name}}"
      }
     ]
    },
    {
     "title": "ProxySQL Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (max_over_time(proxysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[$interval]) or \nmax_over_time(proxysql_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[5m]))",
       "legendFormat": "ProxySQL Exporter Errors  - {{service_name}}"
      }
     ]
    },
    {
     "title": "Rate of Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (rate(proxysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[$interval]) or \nirate(proxysql_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[5m]))",
       "legendFormat": "Scrapes Rate - {{service_name}}"
      }
     ]
    },
    {
     "title": "ProxySQL up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (min_over_time(proxysql_up{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[$interval]) or \nmin_over_time(proxysql_up{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"proxysql.*\"}[5m]))",
       "legendFormat": "ProxySQL Up  - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 17 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[5m])) by ()) / count(node_cpu_seconds_total{mode=\"user\",node_name=\"$node_name\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_resident_memory_bytes{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 17 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 17 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"})"
      }
     ]
    },
    {
     "title": "Rate of Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg by (node_name,service_name) (rate(pg_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[$interval]) or \nirate(pg_exporter_scrapes_total{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[5m]))",
       "legendFormat": "Total  - {{service_name}}"
      },
      {
       "expr": "avg by (node_name,service_name) (max_over_time(pg_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[$interval]) or\nmax_over_time(pg_exporter_last_scrape_error{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[5m]))",
       "legendFormat": "Failed  - {{service_name}}"
      }
     ]
    },
    {
     "title": "Scrape Durations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,service_name) (sum_over_time(pg_exporter_last_scrape_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[$interval]) or\nsum_over_time(pg_exporter_last_scrape_duration_seconds{node_name=\"$node_name\",service_name=~\"$service_name\",job=~\"postgres.*\"}[5m]))",
       "legendFormat": "Duration  - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name,service_name) ((sum(label_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[$interval]),\"node_name\", \"pmm-server\", \"\", \"\")) by () or sum(label_replace(irate(process_cpu_seconds_total{job=~\"rds.*\"}[5m]),\"node_name\", \"pmm-server\", \"\", \"\")) by ()) / count(node_cpu_seconds_total{mode=\"user\",node_name=\"pmm-server\"})*100 * count by () (process_resident_memory_bytes{instance=\"$node_name\",job=\"prometheus\"}))"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 18 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum by () (label_replace(process_resident_memory_bytes{job=~\"rds.*\"},\"node_name\", \"pmm-server\", \"\", \"\")) * count by () (process_resident_memory_bytes{instance=\"$node_name\",job=\"prometheus\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{job=~\"rds.*\"}) * count by () (process_resident_memory_bytes{instance=\"$node_name\",job=\"prometheus\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 18 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name,service_name) ((time() - avg(process_start_time_seconds{job=~\"rds.*\"})) * count by () (process_resident_memory_bytes{instance=\"$node_name\",job=\"prometheus\"}))"
      }
     ]
    },
    {
     "title": "Rate of Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "sum by (job) (avg by (job) (label_replace((rate(rds_exporter_requests_total{job=~\"rds.*\"}[$interval]) or \nirate(rds_exporter_requests_total{job=~\"rds.*\"}[5m])),\"job\", \"rds_exporter_$2\", \"job\", \"rds_exporter_(.*)_(.*)\"))) * ignoring (job) count by () (process_resident_memory_bytes{instance=\"$node_name\",job=\"prometheus\"})",
       "legendFormat": "rds_exporter"
      }
     ]
    },
    {
     "title": "Scrape Durations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (label_replace(avg by (instance) (sum_over_time(rds_exporter_scrape_duration_seconds{job=~\"rds.*\"}[$interval]) or\nsum_over_time(rds_exporter_scrape_duration_seconds{job=~\"rds.*\"}[5m])),\"job\", \"rds_exporter_$2\", \"job\", \"rds_exporter_(.*)_(.*)\")) * ignoring (job) count by () (process_resident_memory_bytes{instance=\"$node_name\",job=\"prometheus\"})",
       "legendFormat": "rds_exporter"
      }
     ]
    }
   ]
  }
 ]
}