{
 "title": "Temperature Details",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Node Name",
    "query": "label_values(node_hwmon_chip_names, node_name)"
   },
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Temperature Sensors",
   "type": "table",
   "description": "Hardware monitoring devices let you monitor the hardware health of a system. Most modern motherboards include such a device. It can include temperature sensors, voltage sensors, fan speed sensors and various additional features such as the ability to control the speed of the fans. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count by (node_name) ((count by (sensor,node_name) (node_hwmon_temp_celsius{node_name=~\"$host\"})) * on(node_name,sensor) group_left(label) (node_hwmon_sensor_label{node_name=~\"$host\",label=~\"core.*\"}))",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count by (node_name) ((node_hwmon_temp_celsius{node_name=~\"$host\"}) * on(node_name,sensor) group_left(label) (node_hwmon_sensor_label{node_name=~\"$host\",label!~\"core.*\"}))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Cores Temperature",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "(sum by (sensor,node_name) (node_hwmon_temp_celsius{node_name=~\"$host\"})) * on(node_name,sensor) group_left(label) (node_hwmon_sensor_label{node_name=~\"$host\",label=~\"core.*\"})",
     "legendFormat": "{{node_name}} - {{label}}"
    }
   ]
  },
  {
   "title": "Fan Rotation Speeds",
   "type": "graph",
   "description": "Fan rotation speeds are reported in RPM (rotations per minute).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(node_hwmon_fan_rpm{node_name=~\"$host\"}[$interval]) or max_over_time(node_hwmon_fan_rpm{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{node_name}} - {{sensor}}"
    },
    {
     "expr": "avg(max_over_time(node_hwmon_fan_rpm{node_name=~\"$host\"}[$interval]) or max_over_time(node_hwmon_fan_rpm{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Nodes Chips Temperature",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{node_name=~\"$host\"}) * on(node_name,sensor) group_left(label) (node_hwmon_sensor_label{node_name=~\"$host\",label!~\"core.*\"})",
     "legendFormat": "{{node_name}} - {{chip}}"
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Cores Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(sum by (sensor,node_name) (node_hwmon_temp_celsius{node_name=\"$host\"})) * on(sensor) group_left(label) (node_hwmon_sensor_label{node_name=\"$host\",label=~\"core.*\"})",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "$host - Chips Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(node_hwmon_temp_celsius{node_name=\"$host\"}) * on(sensor) group_left(label) (node_hwmon_sensor_label{node_name=\"$host\",label!~\"core.*\"})",
       "legendFormat": "{{chip}}"
      }
     ]
    },
    {
     "title": "$host - Fan Rotation Speeds",
     "type": "graph",
     "description": "Fan rotation speeds are reported in RPM (rotations per minute).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(node_hwmon_fan_rpm{node_name=\"$host\"}[$interval]) or max_over_time(node_hwmon_fan_rpm{node_name=\"$host\"}[5m])",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "$host - Fan Power Usage",
     "type": "graph",
     "description": "Pulse width modulation fan control. PWM operates like a switch which constantly cycles on and off, thereby regulating the amount of power the fan or pump motor gains.  255 is max or 100%.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(max_over_time(node_hwmon_pwm{node_name=~\"$host\"}[$interval]) or max_over_time(node_hwmon_pwm{node_name=~\"$host\"}[5m]))/255",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Cores Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(sum by (sensor,node_name) (node_hwmon_temp_celsius{node_name=\"$host\"})) * on(sensor) group_left(label) (node_hwmon_sensor_label{node_name=\"$host\",label=~\"core.*\"})",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "$host - Chips Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(node_hwmon_temp_celsius{node_name=\"$host\"}) * on(sensor) group_left(label) (node_hwmon_sensor_label{node_name=\"$host\",label!~\"core.*\"})",
       "legendFormat": "{{chip}}"
      }
     ]
    },
    {
     "title": "$host - Fan Rotation Speeds",
     "type": "graph",
     "description": "Fan rotation speeds are reported in RPM (rotations per minute).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(node_hwmon_fan_rpm{node_name=\"$host\"}[$interval]) or max_over_time(node_hwmon_fan_rpm{node_name=\"$host\"}[5m])",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "$host - Fan Power Usage",
     "type": "graph",
     "description": "Pulse width modulation fan control. PWM operates like a switch which constantly cycles on and off, thereby regulating the amount of power the fan or pump motor gains.  255 is max or 100%.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(max_over_time(node_hwmon_pwm{node_name=~\"$host\"}[$interval]) or max_over_time(node_hwmon_pwm{node_name=~\"$host\"}[5m]))/255",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}