{
 "title": "MongoDB Collections Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\"}, service_name)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(mongodb_top_commands_count, database)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(mongodb_top_commands_count{database=~\"$database\"}, collection)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hottest Collections by Read  Total (Instance)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk (5,sum by (collection) (mongodb_top_queries_count))"
    }
   ]
  },
  {
   "title": "Hottest Collections by Write Total (Instance)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(5,sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_remove_count)+sum by (collection) (mongodb_top_update_count))"
    }
   ]
  },
  {
   "title": "Hottest Collections by Read (Instance) (Var 2)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, rate(sum by (collection) (mongodb_top_queries_count)[$interval]))",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Hottest Collections by Write (Instance) (Var 2)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, rate(sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_remove_count)+sum by (collection) (mongodb_top_update_count)))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Database Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Collections statistics  from $database (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "Database",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sum by (database) (mongodb_top_commands_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Commands"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_insert_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_update_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Update"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_remove_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Remove"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_getmore_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Getmore"
    }
   ]
  },
  {
   "title": "Collections statistics  from $database (summary)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (mongodb_top_commands_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Commands"
    },
    {
     "expr": "sum by (database) (mongodb_top_insert_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum by (database) (mongodb_top_update_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Update"
    },
    {
     "expr": "sum by (database) (mongodb_top_remove_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Remove"
    },
    {
     "expr": "sum by (database) (mongodb_top_getmore_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Getmore"
    }
   ]
  },
  {
   "title": "Collections statistics  $database",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (collection) (mongodb_top_queries_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_insert_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_remove_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_update_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_getmore_count {database=~\"$database\"})"
    }
   ]
  }
 ]
}