{
 "title": "DBaaS Cluster Summary",
 "tags": [ "Percona" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname{namespace=\"$namespace\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WARNING! Experimental Dashboard. Expand to read more.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experimental Dashboard",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## Disclaimer \n\nThis Experimental Dashboard is not a part of the official Percona Monitoring and Management (PMM) deployment and might be updated. \nWe ship this Dashboard to obtain feedback from our users. \n\nOnce we officially release this Dashboard, it will be moved to the appropriate folder. \n\n## About Dashboard\n\nThis Dashboard is a part of the [DBaaS solution](https://www.percona.com/doc/percona-monitoring-and-management/2.x/using/dbaas.html) in PMM.\nThis Dashboard displays the resource consumption in the K8s Cluster.\n\nTo provide feedback on the Dashboard, visit [our forum](https://forums.percona.com/c/percona-monitoring-and-management-pmm/pmm-unofficial-dashboards-and-plugins/67)."
     }
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU and Memory % ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$node_name\"}[$interval])) / sum (machine_cpu_cores{node=~\"$node_name\"}) * 100",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$node_name\"}) / sum (machine_memory_bytes{node=~\"$node_name\"}) * 100",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\",node=~\"$node_name\"}) / sum(machine_cpu_cores{node=~\"$node_name\"}) * 100",
     "legendFormat": "CPU Request %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\",node=~\"$node_name\"}) / sum(machine_cpu_cores{node=~\"$node_name\"}) * 100",
     "legendFormat": "CPU Limit %"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\",node=~\"$node_name\"}) / sum(machine_memory_bytes{node=~\"$node_name\"}) * 100",
     "legendFormat": "Memory Requests % "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\",node=~\"$node_name\"}) / sum(machine_memory_bytes{node=~\"$node_name\"}) * 100",
     "legendFormat": "Memory Limit  %"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",node=~\"$node_name\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\",node=~\"$node_name\"})",
     "legendFormat": "NotReady"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{node=~\"$node_name\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(kube_job_status_succeeded{node=~\"$node_name\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_job_status_failed{node=~\"$node_name\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{node=~\"$node_name\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{node=~\"$node_name\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{node=~\"$node_name\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{node=~\"$node_name\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{node=~\"$node_name\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Cluster Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\"$node_name\"})[$interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{node=~\"$node_name\"})[$interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "PV and PVC Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Bound\"})",
     "legendFormat": "PVC Bound"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Pending\"})",
     "legendFormat": "PVC Pending"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Lost\"})",
     "legendFormat": "PVC Lost"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Available\"})",
     "legendFormat": "PV Available"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Bound\"})",
     "legendFormat": "PV Bound"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Pending\"})",
     "legendFormat": "PV Pending"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Released\"})",
     "legendFormat": "PV Released"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{namespace=~\"$namespace\",phase=\"Failed\"})",
     "legendFormat": "PV Failed"
    }
   ]
  },
  {
   "title": "PVC Capacity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}({{namespace}})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase='Running'})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=~\"$namespace\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{namespace=~\"$namespace\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=~\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "PVC Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 49 },
   "targets": [
    {
     "expr": "kube_storageclass_info{namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}