{
 "title": "MongoDB ReplSet Summary (New)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "rs_nm",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "service_name",
    "label": "Node",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$rs_nm\"}, service_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{cluster=~\"$cluster\",service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": {
     "query": "query_result(mongodb_mongod_replset_my_state{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(mongodb_up{service_name=~\"$service_name\"}, service_id)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(up{service_name=~\"$service_name\"},service_name)"
    }
   },
   {
    "name": "secondary",
    "query": {
     "query": "query_result(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$rs_nm\"}==2)"
    }
   },
   {
    "name": "mountpoint",
    "query": {
     "query": "label_values(node_filesystem_avail_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "⚠️ Disclaimer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 193 },
     "options": {
      "content": "#### 🛎️ Important\n\nThis Dashboard is an experimental MongoDB Instance Summary dashboard in Percona Monitoring and Management (PMM) that is not a part of the official PMM deployment and might be updated.\nWe ship this Dashboard to obtain feedback from our users. Once we officially release this Dashboard, it will be moved to the appropriate folder. \n\nTo provide feedback on the Dashboard, please use [our](https://forums.percona.com) forum.🙏"
     }
    }
   ]
  },
  { "title": "Overview - $service_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "service_name" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{node_name=\"$node_name\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "Estimated how much memory can be used without swapping",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"})/ avg(node_memory_MemTotal_bytes{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "gauge",
   "description": "Shows disk Utilization as a percentage of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. The graph augments the IO latency and Disk Load Graphs, allowing to determine if the disk load was evenly distributed in time or consuming the IO momentarily. Higher utilization increases the likeliness of IO queuing. Always consider this metric along with response time and IO queue depth.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (rate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "gauge",
   "description": "Shows information about the disk space usage of the specified mountpoint.\n\n**Used** is the amount of space used.\n\n**Free** is the amount of space not in use.\n\n**Used+Free** is the total disk space allocated to the mountpoint.\n\nHaving *Free* close to 0 B is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case Free is close to 0 B consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_dbstats_fsUsedSize{service_name=~\"$service_name\"})/ avg (mongodb_dbstats_fsTotalSize{service_name=~\"$service_name\"})",
     "legendFormat": "Total Size"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "stat",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m]))\n))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) \n))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or sum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or sum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or sum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or sum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or sum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (node_name)  (time() - container_start_time_seconds{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name,mongodb) (mongodb_version_info{service_name=~\"$service_name\"})",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  { "title": "Node States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ReplSet States",
   "type": "state-timeline",
   "description": "ReplSet statuses during the select time range.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\", cluster=~\"$cluster\", set=~\"$rs_nm\", service_name=~\"$service_name\"})",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Command Operations",
     "type": "graph",
     "description": "Ops or Replicated Ops/sec classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name, legacy_op_type) (rate(mongodb_ss_opcountersRepl{service_name=~\"$service_name\", legacy_op_type!~\"(command|query|getmore)\"}[$interval]))",
       "legendFormat": "repl_{{legacy_op_type}} - {{ service_name }}"
      },
      {
       "expr": "avg by (service_name) (rate(mongodb_ss_metrics_ttl_deletedDocuments{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "ttl_delete - {{ service_name }}"
      },
      {
       "expr": "avg by (service_name, legacy_op_type) (rate(mongodb_ss_opcounters{service_name=~\"$service_name\", legacy_op_type!=\"command\"}[$interval]))",
       "legendFormat": "{{legacy_op_type}} - {{ service_name }}"
      }
     ]
    },
    {
     "title": "Top Hottest Collections by Read",
     "type": "bargauge",
     "description": "Show the 5 collections that are most frequently read.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk (5,sum by (service_name,database,collection) (irate(mongodb_top_queries_count{service_name=~\"$service_name\"})[$interval]))",
       "legendFormat": "{{service_name}} - {{database}}.{{collection}}"
      }
     ]
    },
    {
     "title": "Query execution times",
     "type": "graph",
     "description": "Average latency of operations (classified by read, write, or (other) command)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,op_type) (rate(mongodb_ss_opLatencies_latency{service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_ss_opLatencies_ops{service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_ss_opLatencies_latency{service_name=~\"$service_name\"}[5m]) / (irate(mongodb_ss_opLatencies_ops{service_name=~\"$service_name\"}[5m]) > 0))",
       "legendFormat": "{{op_type}} - {{ service_name }}"
      }
     ]
    },
    {
     "title": "Top Hottest Collections by Write",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk (5,sum by (service_name,database,collection) (irate(mongodb_top_insert_count{service_name=~\"$service_name\"}+mongodb_top_remove_count{service_name=~\"$service_name\"}+mongodb_top_update_count{service_name=~\"$service_name\"})[1m]))",
       "legendFormat": "{{service_name}} - {{database}}.{{collection}}"
      }
     ]
    },
    {
     "title": "Query Efficiency",
     "type": "timeseries",
     "description": "Ratio of Documents (or Index entries) scanned / documents returned. A value of 1 means all documents returned exactly match query criteria for the sample period. A value of 100 means on average for the sample period, a query scans 100 documents to find one that is returned.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum by (service_name)(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval])) /\nsum(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval]))\nor\nsum by (service_name)(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m])) /\nsum(irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])))",
       "legendFormat": "Scanned objects / returned - {{ service_name }}"
      },
      {
       "expr": "(sum by (service_name)(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval])) /\nsum(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval]))\nor\nsum by (service_name)(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m])) /\nsum(irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])))",
       "legendFormat": "Scanned idx / returned - {{ service_name }}"
      }
     ]
    },
    {
     "title": "Queued Operations",
     "type": "graph",
     "description": "Operations queued due to a lock.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,type) (mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"})",
       "legendFormat": "{{type}} - {{ service_name }}"
      }
     ]
    },
    {
     "title": "Reads & Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_ss_globalLock_activeClients_readers{service_name=~\"$service_name\"}",
       "legendFormat": "Active Readers - {{ service_name }}"
      },
      {
       "expr": "mongodb_ss_globalLock_activeClients_writers{service_name=~\"$service_name\"}",
       "legendFormat": "Active Writers - {{ service_name }}"
      },
      {
       "expr": "mongodb_ss_globalLock_currentQueue{service_name=~\"$service_name\",count_type=\"readers\"}",
       "legendFormat": "Queued Readers - {{ service_name }}"
      },
      {
       "expr": "mongodb_ss_globalLock_currentQueue{service_name=~\"$service_name\",count_type=\"writers\"}",
       "legendFormat": "Queued Writers - {{ service_name }}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "MongoDB Connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{service_name=~\"$service_name\",conn_type=~\"current\"}",
       "legendFormat": "{{ service_name}} - Current"
      },
      {
       "expr": "mongodb_ss_connections{service_name=~\"$service_name\",conn_type=~\"available\"}",
       "legendFormat": "{{ service_name}} - Available"
      }
     ]
    }
   ]
  },
  {
   "title": "Collection Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of Collections",
     "type": "table",
     "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (environment,cluster,rs_nm, collection) (mongodb_collstats_storageStats_storageSize{cluster=~\"$cluster\",rs_nm=~\"$rs_nm\",db!~\"admin|config\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Number of Collections",
     "type": "table",
     "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
     "targets": [
      {
       "expr": "max by (environment,cluster,rs_nm) (mongodb_mongod_db_collections_total{cluster=~\"$cluster\",rs_nm=~\"$rs_nm\",db!~\"admin|config\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag",
     "type": "graph",
     "description": "MongoDB replication lag occurs when the secondary node cannot replicate data fast enough to keep up with the rate that data is being written to the primary node. It could be caused by something as simple as network latency, packet loss within your network, or a routing issue.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mongodb_mongod_replset_member_replication_lag{environment=~\"$environment\",cluster=~\"$cluster\",set=\"$rs_nm\",service_name=~\"$secondary\"}[$interval]) > 0 ",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Oplog Recovery Window",
     "type": "timeseries",
     "description": "Timespan 'window' between newest and the oldest op in the Oplog collection.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mongodb_mongod_replset_oplog_head_timestamp{service_name=~\"$service_name\"}-mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service_name\"}",
       "legendFormat": "Oplog Range - {{ service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Control",
     "type": "graph",
     "description": "Average latency of operations (classified by read, write, or (other) command)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_ss_flowControl_isLaggedCount{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "fc_count {{ service_name }}"
      },
      {
       "expr": "avg by (service_name) (rate(mongodb_ss_flowControl_isLaggedTimeMicros{service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "fc_time {{ service_name }}"
      }
     ]
    },
    {
     "title": "WiredTiger Concurrency Tickets Available",
     "type": "graph",
     "description": "A WT 'ticket' is assigned out for every operation running simultaneously in the WT storage engine. \"Available\" = hardcoded high value - \"Out\".",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,type) ((max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\",txn_rw=\"read\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\",txn_rw=\"read\"}[5m])) -\n(max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\",txn_rw=\"read\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\",txn_rw=\"read\"}[5m])))",
       "legendFormat": "read -  {{ service_name }}"
      },
      {
       "expr": "avg by (service_name,type) ((max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\",txn_rw=\"write\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=~\"$service_name\",txn_rw=\"write\"}[5m])) -\n(max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\",txn_rw=\"write\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=~\"$service_name\",txn_rw=\"write\"}[5m])))",
       "legendFormat": "write -  {{ service_name }}"
      }
     ]
    }
   ]
  }
 ]
}