{
 "title": "MongoDB Overview",
 "tags": [
  "MongoDB",
  "Percona",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "mongos",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state,node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by (cluster) (mongodb_mongod_replset_my_state) == 8)"
    },
    {
     "expr": "count (group by (cluster) (mongodb_mongod_replset_my_state) == 1) or count (avg by (cluster) (mongodb_mongod_replset_my_state) == 2)"
    },
    {
     "expr": "count (group by (cluster) (mongodb_mongod_replset_my_state) == 6)"
    }
   ]
  },
  {
   "title": "Node States",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by (service_name) ((mongodb_mongod_replset_my_state) == 8))"
    },
    {
     "expr": "count (group by (service_name) ((mongodb_mongod_replset_my_state) == 3))"
    },
    {
     "expr": "count (group by (service_name) ((mongodb_mongod_replset_my_state) == 6))"
    },
    {
     "expr": "count (group by (service_name) ((mongodb_mongod_replset_my_state) == 5))"
    },
    {
     "expr": "count (group by (service_name) ((mongodb_mongod_replset_my_state) == 9))"
    },
    {
     "expr": "count (group by (service_name) ((mongodb_mongod_replset_my_state) == 10))"
    }
   ]
  },
  {
   "title": "States",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (service_name) (mongodb_mongod_replset_my_state) ",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Sharding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "options": {
    "content": "# State of Config Servers\n\nState of config servers (how many offline, based on the Mongod process)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
   "options": {
    "content": "# State of Routers\n\nState of routers (how many running, based on the Mongod process)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "# State of Balancer\n\nState of the balancer (how many running, how many offline, based on the results of Sh.status() command)"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 2) + count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 6)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {node_name=~\"$mongos\"}) == 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {node_name=~\"$mongos\"}) == 6)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {node_name=~\"$mongos\"}) == 5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 2) + count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 6)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (max by (service_name) (mongodb_mongod_replset_my_state {set=~\"cfg\"}) == 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "MongoDB Version",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (mongodb) (mongodb_version_info)",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (name) (node_os_version)",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Kubernetes Version",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (git_version) (kubernetes_build_info)",
     "legendFormat": "{{git_version}}"
    }
   ]
  },
  {
   "title": "Operator Version",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (git_version) (kubernetes_build_info)",
     "legendFormat": "{{git_version}}"
    }
   ]
  }
 ]
}