{
 "title": "MongoDB Collections Overview",
 "tags": [
  "Percona",
  "MongoDB_HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\"}, service_name)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_top_commands_count{cluster=~\"$cluster\"}, database)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(mongodb_top_commands_count{database=~\"$database\"}, collection)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Datasize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 5 Databases By Size",
   "type": "timeseries",
   "description": "Show the 5 largest databases in an instance according to info pulled from dbStats.dataSize. This reflects the size of uncompressed data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (database) (topk(5, mongodb_dbstats_dataSize{rs_state=\"1\",cluster=~\"$cluster\"})/1024/1024)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Collections in Database ($database)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mongodb_top_commands_time{database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Indexes in Database ($database)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexes{database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Avg Object Size in Database ($database)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_avgObjSize{database=~\"$database\"})",
     "legendFormat": "$database"
    }
   ]
  },
  {
   "title": "Index Size in Database ($database)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexSize{database=~\"$database\"})",
     "legendFormat": "$database"
    }
   ]
  },
  {
   "title": "Data Size for Database ($database)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_dataSize{database=~\"$database\"})",
     "legendFormat": "$database"
    }
   ]
  },
  { "title": "Instance Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Top 5 Hottest Collections by Read  (Total)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk (5,sum by (collection) (mongodb_top_queries_count))"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Write (Total)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "topk(5,sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_remove_count)+sum by (collection) (mongodb_top_update_count))"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Read (Rate)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, rate(sum by (collection) (mongodb_top_queries_count)[$interval]))",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Write (Rate)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5, rate(sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_insert_count)+sum by (collection) (mongodb_top_remove_count)+sum by (collection) (mongodb_top_update_count)))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Database Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Collections statistics  from $database (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "repeat": "Database",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sum by (database) (mongodb_top_commands_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Commands"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_insert_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_update_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Update"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_remove_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Remove"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_getmore_count {database=~\"$database\"}[$interval]))",
     "legendFormat": "Getmore"
    }
   ]
  },
  {
   "title": "Collections statistics  from $database (summary)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (mongodb_top_commands_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Commands"
    },
    {
     "expr": "sum by (database) (mongodb_top_insert_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum by (database) (mongodb_top_update_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Update"
    },
    {
     "expr": "sum by (database) (mongodb_top_remove_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Remove"
    },
    {
     "expr": "sum by (database) (mongodb_top_getmore_count {database=~\"$database\"}[$interval])",
     "legendFormat": "Getmore"
    }
   ]
  },
  {
   "title": "Collections statistics  $database",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (collection) (mongodb_top_queries_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_insert_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_remove_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_update_count {database=~\"$database\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_getmore_count {database=~\"$database\"})"
    }
   ]
  }
 ]
}